### PR TITLE
Data Access: Modifies entity repository sibling queries to support custom database p[oviders (closes #21852)

### LINKED ISSUE #21852: SQL Syntax Issues
### Which Umbraco version are you using?

17.3.0-rc.preview

### Bug summary

This is hopefully the final part of issues that need to be fixed for external database providers like PostgreSQL.
The closing PR #21671 is ready and contains all details summarised by Copilot:

**_Pull request overview_**
_This PR implements SqlSyntax and NPoco changes to enable custom PostgreSQL database provider support, addressing issue https://github.com/umbraco/Umbraco-CMS/issues/21675. The changes add case-insensitive string comparison logic, update test infrastructure for database portability, and introduce new interface members for database-specific features like sequences and auto-increment handling._
_**Changes:**_
_Modified WhereIn extension to apply case-insensitive comparisons for string values using LOWER() function
Added new ISqlSyntaxProvider interface members: StringLengthUnicodeColumnDefinitionFormat and InsertWithSpecialAutoInkrement() (note: contains typo)
Updated integration tests to use helper methods (QTab, QCol, QName) for database-agnostic identifier quoting_ 
_**Reviewed changes**_
_Copilot reviewed 11 out of 11 changed files in this pull request and generated 8 comments._

### Specifics

_No response_

### Steps to reproduce

Like the all the other issues, these will only occur in custom provider like PostgreSQL.

### Expected result / actual result

_No response_

### PR DESCRIPTION
**Pull request by idseefeld**
This is "hopefully" the last PR to make a custom PostgreSQL database provider possible.
This fixes #21852.

All test must succeed and table sql must be unchanged.

### CODE REVIEW

**Comment by idseefeld** [comment]
@AndyButland This is currently the last PR to enable my PostgreSQL provider. I have not found any further issues with Umbraco CMS yet.

But I noticed issues with the Forms package. Probably it does not use the API consistently or the test coverage is not sufficient.

There might be other Umbraco packages which are not open source and won't work out of the box.

Time shall show.

**Comment by AndyButland** [comment]
OK @idseefeld.  Before I look to review, please can you first go over the automated review comments and either act on them or justify they they are incorrect.  I'd also appreciate if you can review to ensure all changes you are proposing are necessary, and that it will be clear to me - and any future reviewer - why they are (either with code comments, or by providing more detail in the PR description).  Thanks.

**Comment by idseefeld** [comment]
@AndyButland I have resolved all Copilot comments and double checked every change is necessary.
There are code comments where appropriate and hopefully all new settings, property or method names are meaningful and expressive.

**Comment by idseefeld** [comment]
Maybe the _CodeScene_ finding could be suppressed for `NPocoSqlExtensions.cs` with an explanation like:

_This is a known issue and shall be addressed in a dedicated PR if ever. Because the planned replacement of **NPoco** by **EF Core** will probably solve this issue._
😉

File: src/Umbraco.Infrastructure/Persistence/SqlSyntax/ISqlSyntaxProvider.cs [hunk 1]
```diff
@@ -180,6 +185,22 @@ DatabaseType GetUpdatedDatabaseType(DatabaseType current, string? connectionStri
...
 
+    /// <summary>
+    /// This is an additional setting for databases that use auto-increment columns but require special handling during insert operations.
+    /// </summary>
+    /// <returns>true if the provider requires special handling for auto-increment inserts; otherwise, false.</returns>
+    /// <remarks>
+    /// Use case PostgreSQL which uses sequences for auto-incrementing columns but may require specific insert logic.
+    /// After inserting a dedicated value the sequence needs to be updated to avoid conflicts.
+    /// </remarks>
+    bool InsertWithSpecialAutoIncrement() => false;
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/SqlSyntax/ISqlSyntaxProvider.cs]: Do we need this as well as `SupportsSequences`?  Seems they are both either `false` (SQL Server, SQLite) or `true` (Postgres) so we could have just the one property.

File: src/Umbraco.Infrastructure/Persistence/NPocoSqlExtensions.cs [hunk 2]
```diff
@@ -87,7 +87,26 @@ public static Sql<ISqlContext> Where<TDto1, TDto2, TDto3>(this Sql<ISqlContext>
...
+
             var fieldName = sql.SqlContext.SqlSyntax.GetFieldName(field);
+
+            if (sql.SqlContext.SqlSyntax.IsCaseSensitive())
+            {
+                // If the database is case sensitive, we need to convert the values to lower case and use LOWER() in the SQL to ensure case insensitive comparison.
+                string[] stringValues = [.. values.OfType<string>()];
+                if (stringValues.Length > 0)
+                {
+                    values = stringValues.Select(v => v?.ToLower());
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/NPocoSqlExtensions.cs]:
```suggestion
                    values = stringValues.Select(v => v?.ToLowerInvariant());
```

File: src/Umbraco.Infrastructure/Persistence/NPocoSqlExtensions.cs [hunk 3]
```diff
@@ -87,7 +87,26 @@ public static Sql<ISqlContext> Where<TDto1, TDto2, TDto3>(this Sql<ISqlContext>
...
+            {
+                return sql;
+            }
+
             var fieldName = sql.SqlContext.SqlSyntax.GetFieldName(field);
+
+            if (sql.SqlContext.SqlSyntax.IsCaseSensitive())
+            {
+                // If the database is case sensitive, we need to convert the values to lower case and use LOWER() in the SQL to ensure case insensitive comparison.
+                string[] stringValues = [.. values.OfType<string>()];
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/NPocoSqlExtensions.cs]: If the `IEnumerable` is mixed-type, non-string items are silently dropped here. This could produce wrong results (fewer items in the IN clause than the caller expects).

Worth checking that we only call this with `string` types in Umbraco, but even then it's a change for anyone using this extension from Umbraco implementations.  Perhaps better to `ToString()` on other primitive types that could be passed here, like numerical types?

File: tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/NPocoTests/NPocoFetchTests.cs [hunk 4]
```diff
@@ -435,12 +436,12 @@ public class Thing2Dto
         [Column("name")]
         public string Name { get; set; }
 
-        [Column("thingId")]
+        [Column("thingid")]
```
Comment (AndyButland) [inline tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/NPocoTests/NPocoFetchTests.cs]: What's the need for lower-casing these columns?  If it's to get tests to pass, am concerned this might be hiding something in production code/database, where column names are mixed case.

File: src/Umbraco.Infrastructure/Persistence/SqlSyntax/ISqlSyntaxProvider.cs (hunk 1 above)
Comment (idseefeld) [reply src/Umbraco.Infrastructure/Persistence/SqlSyntax/ISqlSyntaxProvider.cs]: Checked again and no we don't need it. I'll remove it.

File: src/Umbraco.Infrastructure/Persistence/NPocoSqlExtensions.cs (hunk 3 above)
Comment (idseefeld) [reply src/Umbraco.Infrastructure/Persistence/NPocoSqlExtensions.cs]: I have not found a case of mixed value types, but your are right, these are possible.
So, I have refined this method to handle mixed value cases.

Comment (idseefeld) [reply src/Umbraco.Infrastructure/Persistence/NPocoSqlExtensions.cs]: This one was tricky. After implementing your suggestion I realised: In case of multi types in the `IEnumerable? values` parameter, the resulting sql statement would be invalid. First I thought an additional validation would be useful, but that would mean a performance degradation and if some tries to use mixed value types the sql execution will fail anyways. But for the `IsCaseSensitive` clause I need to check this or `.ToString()` would hide the wrong (not string) values.

File: src/Umbraco.Infrastructure/Persistence/NPocoSqlExtensions.cs (hunk 2 above)
Comment (idseefeld) [reply src/Umbraco.Infrastructure/Persistence/NPocoSqlExtensions.cs]: changed

File: tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/NPocoTests/NPocoFetchTests.cs (hunk 4 above)
Comment (idseefeld) [reply tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/NPocoTests/NPocoFetchTests.cs]: reverted

**Comment by idseefeld** [comment]
@AndyButland now I have reduced this PR to its minimum I need. Three simple one liners and an overhauled method where the changes are depending on the new condition `IsCaseSensitive()`.

File: src/Umbraco.Infrastructure/Persistence/NPocoSqlExtensions.cs [hunk 5]
```diff
@@ -85,13 +85,46 @@ public static Sql<ISqlContext> Where<TDto1, TDto2, TDto3>(this Sql<ISqlContext>
         /// <param name="field">An expression specifying the field.</param>
         /// <param name="values">The values.</param>
         /// <returns>The Sql statement.</returns>
+        /// <remarks>IEnumerable? values may contain nullable values of different types like int, Guid, DateTime or string. For performance reasons, this case is not checked here. But be aware that mixing typs result in an invalid sql statement.</remarks>
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/NPocoSqlExtensions.cs]:
```suggestion
        /// <remarks>IEnumerable? values may contain nullable values of different types like int, Guid, DateTime or string. For performance reasons, this case is not checked here. But be aware that mixing types result in an invalid sql statement.</remarks>
```

I've fixed the typo, but this need a further look.  What does "For performance reasons, this case is not checked here." refer to here?

File: src/Umbraco.Infrastructure/Persistence/NPocoSqlExtensions.cs [hunk 6]
```diff
@@ -85,13 +85,46 @@ public static Sql<ISqlContext> Where<TDto1, TDto2, TDto3>(this Sql<ISqlContext>
...
         public static Sql<ISqlContext> WhereIn<TDto>(this Sql<ISqlContext> sql, Expression<Func<TDto, object?>> field, IEnumerable? values)
         {
+            if (values == null)
+            {
+                return sql;
+            }
+
             var fieldName = sql.SqlContext.SqlSyntax.GetFieldName(field);
+
+            if (sql.SqlContext.SqlSyntax.IsCaseSensitive())
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/NPocoSqlExtensions.cs]: Although this won't impact core supported databases since it's gated behind the `IsCaseSensitive()` check, there are performance concerns with this as by using `LOWER` there won't be benefit from indexes.

File: src/Umbraco.Infrastructure/Persistence/SqlSyntax/ISqlSyntaxProvider.cs [hunk 7]
```diff
@@ -85,6 +85,11 @@ public interface ISqlSyntaxProvider
 
     string DbProvider { get; }
 
+    /// <summary>
+    /// Returns the format for a string column definition with a specified length for Unicode text types (e.g. NVARCHAR in SQL Server). The format should include a placeholder for the length, such as "NVARCHAR({0})". This is used when generating SQL for string columns that require a length specification.
+    /// </summary>
+    string StringLengthUnicodeColumnDefinitionFormat => "NVARCHAR({0})";
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/SqlSyntax/ISqlSyntaxProvider.cs]: It doesn't appear that this is used, so let's remove.

File: src/Umbraco.Infrastructure/Persistence/Repositories/Implement/EntityRepository.cs [hunk 8]
```diff
@@ -294,15 +296,14 @@ private Sql<ISqlContext> SiblingsSql(
...
-        // use all lower case alias names to avoid sql syntax issues
         string targetAlias = "target";
 
         // Find the specific row number of the target node.
         // We need this to determine the bounds of the row numbers to select.
         Sql<ISqlContext> targetRowSql = Sql()
             .Select("rn")
             .From().AppendSubQuery(rowNumberSql, targetAlias)
-            .Where<NodeDto>(x => x.UniqueId == targetKey, targetAlias);
+            .Where($"{QuoteTableName(targetAlias)}.{quotedImplicitUniqueIdAlias} IN (@0)", [targetKey]); // cannot use generic .Where<T> here because of the implicit alias "UniqueId" in the subquery
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/Repositories/Implement/EntityRepository.cs]: This looks concerning.  It's replace a strongly-typed query for a single value - i.e. with `=` - with a raw SQL `IN` statement.  Maybe you can find a different way to solve whatever the issue is here.

File: src/Umbraco.Infrastructure/Persistence/NPocoSqlExtensions.cs [hunk 9]
```diff
@@ -85,13 +85,46 @@ public static Sql<ISqlContext> Where<TDto1, TDto2, TDto3>(this Sql<ISqlContext>
...
             sql.Where($"{fieldName} IN (@values)", new { values });
             return sql;
         }
 
+        private static string? EnsureLowerStringValue(object? value)
+        {
+            if (value == null || value is not string)
+            {
+                throw new ArgumentException("All values must be of type string when the database is case sensitive and the field is a string.");
+            }
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/NPocoSqlExtensions.cs]: Again this is gated, but it throws on null which doesn't seem right, given nulls are accepted in the `IEnumerable? values` parameter.

File: src/Umbraco.Infrastructure/Persistence/NPocoSqlExtensions.cs (hunk 6 above)
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/NPocoSqlExtensions.cs]: This has been updated for this overload of `WhereIn`, but there are other methods and overloads (another `WhereIn`, `WhereInOr`) that now won't be consistent and may have the same problem.

File: src/Umbraco.Infrastructure/Persistence/NPocoSqlExtensions.cs (hunk 5 above)
Comment (idseefeld) [reply src/Umbraco.Infrastructure/Persistence/NPocoSqlExtensions.cs]: I'll extend the explanation.

File: src/Umbraco.Infrastructure/Persistence/SqlSyntax/ISqlSyntaxProvider.cs (hunk 7 above)
Comment (idseefeld) [reply src/Umbraco.Infrastructure/Persistence/SqlSyntax/ISqlSyntaxProvider.cs]: It will be used in the PostgreSQL provider. There it becomes: `public override string StringLengthUnicodeColumnDefinitionFormat { get; } = "NATIONAL CHARACTER VARYING({0})";`

File: src/Umbraco.Infrastructure/Persistence/NPocoSqlExtensions.cs (hunk 6 above)
Comment (idseefeld) [reply src/Umbraco.Infrastructure/Persistence/NPocoSqlExtensions.cs]: removed

File: src/Umbraco.Infrastructure/Persistence/Repositories/Implement/EntityRepository.cs (hunk 8 above)
Comment (idseefeld) [reply src/Umbraco.Infrastructure/Persistence/Repositories/Implement/EntityRepository.cs]: Indeed, this is necessary. I tried to explain in the comment. Here are the complete details: 
1. subquery in line 277 `rowNumberSql` in line 277 uses `.AndSelect<NodeDto>(n => n.UniqueId)`
2. `.AndSelect()` uses internally `sql.GetColumns(columnExpressions: fields)));`
3. `.GetColumns()` uses in line 1562 of file `src\Umbraco.Infrastructure\Persistence\NPocoSqlExtensions.cs`:
```
return withAlias ? 
    (string.IsNullOrEmpty(column.ColumnAlias) 
        ? column.MemberInfoKey
        : column.ColumnAlias) 
    : null;
```
4. The property `column.MemberInfoKey` is the root cause of this issue as it should be `column.ColumnName`. 
5. I tried to fix this, but that lead to several bugs in different places.

File: src/Umbraco.Infrastructure/Persistence/NPocoSqlExtensions.cs (hunk 9 above)
Comment (idseefeld) [reply src/Umbraco.Infrastructure/Persistence/NPocoSqlExtensions.cs]: removed

File: src/Umbraco.Infrastructure/Persistence/NPocoSqlExtensions.cs (hunk 6 above)
Comment (idseefeld) [reply src/Umbraco.Infrastructure/Persistence/NPocoSqlExtensions.cs]: removed

**Comment by idseefeld** [comment]
> I'm afraid I'm still seeing some concerns with this @idseefeld. Is another approach you could take here just to have the Postgres database created with case insensitivity, so it behaves like SQL Server does. I don't know the platform, but I read it's possible with a "case insensitive collation". Maybe that would be a better approach to take here.

@AndyButland I have checked again and found actually only one test that fails. See comment in file `tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/MemberServiceTests.cs` in line 530.
I am not sure the case insensitivity needs to be ensured. And if so why does this only matter in case of member groups? 
If you agree, that this is probably just an edge case of somehow misusing the API, I can resolve the "_LOWER() sql issue_".

In the backoffice I could not see any issue in the Members section.

File: src/Umbraco.Infrastructure/Persistence/SqlSyntax/ISqlSyntaxProvider.cs (hunk 7 above)
Comment (idseefeld) [reply src/Umbraco.Infrastructure/Persistence/SqlSyntax/ISqlSyntaxProvider.cs]: It is not enough, that `SqlSyntaxProviderBase` contains it, because this methods needs to be part of the public interface too.

**Comment by idseefeld** [comment]
I have found another solution for the `EntityRepository.SiblingsSql(...)` issue. It eliminates some hard code strings (spread over two methods), some raw sql statements and an extra database query execution for `parentId` (resolving a commented issue).

To make this possible, I added another overload of `public static Sql<ISqlContext> AndSelect<TDto>(this Sql<ISqlContext> sql, bool withAlias = true, params Expression<Func<TDto, object?>>[] fields)` to file `src\Umbraco.Infrastructure\Persistence\NPocoSqlExtensions.cs`.

File: src/Umbraco.Infrastructure/Persistence/SqlSyntax/ISqlSyntaxProvider.cs (hunk 7 above)
Comment (AndyButland) [reply src/Umbraco.Infrastructure/Persistence/SqlSyntax/ISqlSyntaxProvider.cs]: If we aren't calling it in core repositories though, and you only need it in your package code, then I would have thought you could define it there.  I'm questioning why does it need to be on `ISqlSyntaxProvider` at all?

File: src/Umbraco.Infrastructure/Persistence/Repositories/Implement/EntityRepository.cs [hunk 10]
```diff
@@ -25,6 +25,10 @@ namespace Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement;
 /// </remarks>
 internal sealed class EntityRepository : RepositoryBase, IEntityRepositoryExtended
 {
+    private const string mainSiblingsSqlAlias = "nn";
+    private const string mainSiblingsSqlTargetAlias = "target";
+    private const string mainSiblingsSqlRowNumberAlias = "rn";
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/Repositories/Implement/EntityRepository.cs]: I'm not sure declaring these constants, particular at class level, adds much value. As each are only used a few times in tightly coupled code, I'd suggest just inlining them again, also removing unnecessary change in this PR.

File: src/Umbraco.Infrastructure/Persistence/Repositories/Implement/EntityRepository.cs [hunk 11]
```diff
@@ -275,10 +276,11 @@ private Sql<ISqlContext> SiblingsSql(
...
         // These row numbers are important, we need them to select the "before" and "after" siblings of the target node.
         Sql<ISqlContext> rowNumberSql = Sql()
-            .Select($"ROW_NUMBER() OVER ({orderingSql.SQL}) AS rn")
-            .AndSelect<NodeDto>(n => n.UniqueId)
+            .Select($"ROW_NUMBER() OVER ({orderingSql.SQL}) AS {mainSiblingsSqlRowNumberAlias}")
+            .AndSelect<NodeDto>(withAlias: false, n => n.UniqueId)
             .From<NodeDto>()
-            .Where<NodeDto>(x => x.ParentId == parentId && x.Trashed == isTrashed)
+            .Where<NodeDto>(x => x.Trashed == isTrashed)
+            .WhereIn<NodeDto>(x => x.ParentId, parentIdQuery)
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/Repositories/Implement/EntityRepository.cs:285]: This looks good to me.  It's not necessary, but does save a second query for the parent ID, as is noted in the removed comment.  And it doesn't make the code any less clear.

File: tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/MemberServiceTests.cs [hunk 12]
```diff
@@ -527,7 +527,7 @@ public async Task Associate_Members_To_Roles_With_Member_Id_Casing()
         Assert.IsNotNull(MemberService.GetById(member1.Id));
         Assert.IsNotNull(MemberService.GetById(member2.Id));
 
-        MemberService.AssignRoles(new[] { member1.Id, member2.Id }, new[] { "mytestrole1" });
+        MemberService.AssignRoles(new[] { member1.Id, member2.Id }, new[] { "mytestrole1" }); // Why is this test needed? In production you should ensure the role exists and is correct casing, but this is to ensure that the role lookup is case-insensitive
```
Comment (AndyButland) [inline tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/MemberServiceTests.cs]: Suggest to remove this comment.

If this isn't something we can easily support on Postgres, and we don't really need it, suggest adding a check like I suggest in another comment that this test is just skipped unless it's a core supported database.

I.e. add:

```
        if ((IsSqlite() || IsSqlServer()) is false)
        {
            Assert.Ignore("This test requires SqlLite or SQL Server as only these platforms are expected to support case insensitivity.");
            return;
        }
```

File: src/Umbraco.Infrastructure/Persistence/Repositories/Implement/EntityRepository.cs (hunk 11 above)
Comment (AndyButland) [reply src/Umbraco.Infrastructure/Persistence/Repositories/Implement/EntityRepository.cs:285]: We have good test coverage for this query too.

**Review by AndyButland — CHANGES_REQUESTED** [review]

File: src/Umbraco.Infrastructure/Persistence/Repositories/Implement/EntityRepository.cs (hunk 10 above)
Comment (idseefeld) [reply src/Umbraco.Infrastructure/Persistence/Repositories/Implement/EntityRepository.cs]: I just thought, this makes it clearer. But I inline them again. Probably they won't be changed.

File: tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/MemberServiceTests.cs (hunk 12 above)
Comment (idseefeld) [reply tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/MemberServiceTests.cs]: I have to change integration test anyway for my project, so it does not matter to do this for this test too.

Comment (idseefeld) [reply tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/MemberServiceTests.cs]: The same is true for the `StringLengthUnicodeColumnDefinitionFormat` issue. I use it only in custom tests and can remove it from `ISqlSyntaxProvider` interface.

Btw. there is an override in `SqliteSyntaxProvider`. I wonder why it does not matter?

**Comment by idseefeld** [comment]
@AndyButland the last checks failed due to an repository checkout issue. I don't know how to restart the checks without adding a new commit.

I have investigate the `` issue a little further, because I wanted to understand why SQLite overrides it but does not fail the tests.
Referring to [SQLite documentation](https://www.sqlite.org/datatype3.html) the answer is:

SQLite converts any text based traditional sql database types like `VARCHAR(XX), NVARCHAR(xx)` etc. into `text` from any `CREATE` statement. It ignores the size parameter.
Thus tests like `Umbraco.Cms.Tests.Integration.Umbraco.Infrastructure.Migrations.AdvancedMigrationTests.AddColumnAsync()` would not show the actual schema. 

I am satisfied with this findings. All what I have done in my PostgreSQL provider handles this properly, as there is no such magic in PostgreSQL.
