### PR TITLE
Long Running Operations:  Increase `type` column length and handle rebuilds of Examine indexes with long names (closes #21666)

### LINKED ISSUE #21666: Unable to rebuild custom examine index due db column length limit
### Which Umbraco version are you using?

17.1.0

### Bug summary

The error has occurred during rebuilding custom index wit long name:

> "Microsoft.Data.SqlClient.SqlException (0x80131904): String or binary data would be truncated in table 'UmbracoProject.dbo.umbracoLongRunningOperation', column 'type'. Truncated value: 'RebuildExamineIndex-My-Custom_index-Long-Name-That'.
> The statement has been terminated."

Image

Image

### Specifics

My index setup for test:
```c#
[ComposeAfter(typeof(AddExamineComposer))]
public class ExamineComposer : IComposer
{
    public void Compose(IUmbracoBuilder builder)
    {
        builder.Services.AddExamineLuceneIndex<MyIndex, ConfigurationEnabledDirectoryFactory>(MyIndex.NAME);

        builder.Services.ConfigureOptions<ConfigureBookIndexOptions>();

        builder.Services.AddSingleton<IIndexPopulator, BookIndexPopulator>();
    }
}

public class MyIndex : LuceneIndex
{
    public const string NAME = "My-Custom_index-Long-Name-That-Is-More-Than-umbracoLongRunningOperation.Type-Column-Length";

    public MyIndex(
        ILoggerFactory loggerFactory,
        string name,
        IOptionsMonitor<LuceneDirectoryIndexOptions> indexOptions)
        : base(loggerFactory, name, indexOptions)
    {
    }
}

public class ConfigureBookIndexOptions : IConfigureNamedOptions<LuceneDirectoryIndexOptions>
{
    public void Configure(string? name, LuceneDirectoryIndexOptions options)
    {
    }

    public void Configure(LuceneDirectoryIndexOptions options)
        => Configure(string.Empty, options);
}

public class BookIndexPopulator : IndexPopulator
{
    public BookIndexPopulator()
    {
        RegisterIndex(MyIndex.NAME);
    }

    protected override void PopulateIndexes(IReadOnlyList<IIndex> indexes)
    {
    }
}
```

### Steps to reproduce

1. Create umbraco project
2. Add index setup from above
3. Try to rebuild the custom index via UI

### Expected result / actual result

Actual: an error occurred, the index has not been rebuilt
Expected: there is no error, the index should rebuild successfully

**Note**: I have used a long name to show the issue. In my real-world scenario, the longest index name has 40 characters.

---
_This item has been added to our backlog AB#64696_

### PR DESCRIPTION
**Pull request by NguyenThuyLan**
### Description
Issue: https://github.com/umbraco/Umbraco-CMS/issues/21666
- Added a database migration (V_17_3_0) to increase the type column in `umbracoLongRunningOperation `from `nvarchar(50)` to `nvarchar(200)` on SQL Server _(SQLite already uses unlimited text)_
- Updated `LongRunningOperationDto `to reflect the new column length ([Length(200)])
- Added truncation guard in ExamineIndexRebuilder.GetRebuildOperationTypeName to ensure generated type names never exceed 200 characters

  **Test plan**
  - Verify the migration runs successfully on SQL Server (column changes from nvarchar(50) to nvarchar(200))
  - Verify rebuilding a custom Examine index with a moderately long name no longer causes a truncation error

### CODE REVIEW

File: src/Umbraco.Infrastructure/Examine/ExamineIndexRebuilder.cs [hunk 1]
```diff
@@ -130,7 +130,11 @@ public virtual async Task<Attempt<IndexRebuildResult>> RebuildIndexesAsync(bool
     public async Task<bool> IsRebuildingAsync(string indexName)
         => (await _longRunningOperationService.GetByTypeAsync(GetRebuildOperationTypeName(indexName), 0, 0)).Total != 0;
 
-    private static string GetRebuildOperationTypeName(string indexName) => $"RebuildExamineIndex-{indexName}";
+    private static string GetRebuildOperationTypeName(string indexName)
+    {
+        var typeName = $"RebuildExamineIndex-{indexName}";
+        return typeName.Length > 200 ? typeName[..200] : typeName;
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Examine/ExamineIndexRebuilder.cs]:
```suggestion
        // Truncate to a maximum of 200 characters to ensure the type name doesn't overflow the database field.
        const int TypeFieldSize = 200;
        var typeName = $"RebuildExamineIndex-{indexName}";
        return typeName.Length > TypeFieldSize ? typeName[..TypeFieldSize] : typeName;
```
