### PR TITLE
Redirects: Fix self referencing redirects for 13

### LINKED ISSUE #20139: Self-referencing redirects can be generated when a node is renamed and then changed back to the original name
### Which Umbraco version are you using?

13.10.0

### Bug summary

If a user renames a page and publishes it, then changes the name back and publishes it again - a self referencing redirect is created. 

### Specifics

We have our own custom `IRedirectUrlService` (cloned from the Umbraco source) so that we can trigger webhook notifications when new urls are registered since the feature is missing currently in Umbraco 13.x.x. Using the method above to replicate this issue means we end up with 2 redirects which results in this situation.

```
        {
            "key": "f222be25-2369-412b-b09a-83ee769821d3",
            "sourceUrl": "https://example.com/another-redirect-test/",
            "targetUrl": "https://example.com/another-redirect-test-2/",
            "permanent": true,
            "retainQuerystring": false,
            "force": false,
            "created": "2025-09-15T15:56:23.49Z",
            "updated": "2025-09-15T15:56:23.49Z"
        },
        {
            "key": "5f0841b9-55c6-4197-9a13-1a14000826e4",
            "sourceUrl": "https://example.com/another-redirect-test-2/",
            "targetUrl": "https://example.com/another-redirect-test-2/",
            "permanent": true,
            "retainQuerystring": false,
            "force": false,
            "created": "2025-09-15T15:56:11.043Z",
            "updated": "2025-09-15T15:56:11.043Z"
        }
```

We have tried to cancel the registration of the 2nd redirect, however, the method is never called when the node is renamed back to the original name.

### Steps to reproduce

1. Create a node
2. Publish the node
3. Change the name of the node
4. Publish the node
5. Change the name of the node back to what it was originally
6. Publish the node

### Expected result / actual result

A redirect should not be created that would result in both the source and target urls being the same.

---
_This item has been added to our backlog AB#61504_

### PR DESCRIPTION
**Pull request by NillasKA**
Closes #20139

### Description
A bug was found, where if you name a document something, that it has previously been named a self referencing redirect is made.

This PR makes a check, that sees if a redirect is being made that references to the current document URL. If there is, we'll remove that redirect since its not needed.

### CODE REVIEW

File: src/Umbraco.Infrastructure/Routing/RedirectTracker.cs [hunk 1]
```diff
@@ -93,24 +96,21 @@ public void CreateRedirects(IDictionary<(int ContentId, string Culture), (Guid C
...
-                _logger.LogWarning("Could not track redirects because there is no published content cache available on the current published snapshot.");
-                return;
-            }
-
             foreach (((int contentId, string culture), (Guid contentKey, string oldRoute)) in oldRoutes)
             {
                 try
                 {
-                    var newRoute = contentCache.GetRouteById(contentId, culture);
+                    var newRoute = _publishedUrlProvider.GetUrl(contentKey, UrlMode.Relative, culture).TrimEnd(Constants.CharArrays.ForwardSlash);
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Routing/RedirectTracker.cs]: We should revert this change and continue to use `contentCache.GetRouteById`, just so we are only addressing the specific point of the bug fix.  I believe making this change would lead to a similar issue as that I was recently fixing for the latest Umbraco in https://github.com/umbraco/Umbraco-CMS/pull/20900.

Doing so will likely break your tests, but I think you could potentially mock `IUmbracoContextFactory` and `IPublishedContentCache` in a similar way to how you have done with `IPublishedUrlProvider`.

Comment (NillasKA) [reply src/Umbraco.Infrastructure/Routing/RedirectTracker.cs]: So you'd want me to inject IPublishedContentCache into the constructor, as to mock it? Or am i misunderstanding

Comment (AndyButland) [reply src/Umbraco.Infrastructure/Routing/RedirectTracker.cs]: No, I don't think so.  Given this is a fix for an issue in the LTS I just want to be very careful about changing anything that's not required to implement the fix.  Out of concern of introducing some other unexpected behaviour change.  

So what I'm saying really is that we shouldn't change anything in the production code that's not necessary (even if it makes testing easier).  And it's up to the test code to mock what it needs in order to verify the functionality.

Here we have this code:

```
using UmbracoContextReference reference = _umbracoContextFactory.EnsureUmbracoContext();
IPublishedContentCache? contentCache = reference.UmbracoContext.Content;
```

So it looks like you could:

- Mock `IUmbracoContextFactory` in your test, that is already injected in the constructor.
- Set that up to return an `UmbracoContextReference` that you create using it's constructor, passing a mocked `IUmbracoContext`.
- Set up the mocked `IUmbracoContext` to return a mocked `IPublishedContentCache`
- Set up that such that it returns what you need in the call to `GetRouteById`
