### PR TITLE
Distributed Background Jobs: Preventing Jobs From Running When Database Is Read-Only

### LINKED ISSUE #22191: Subscriber servers - Read-only database access does not work (distributed jobs)
### Which Umbraco version are you using?

17.3.0-RC

### Which Umbraco version are you using?

17.3.0-RC (and previous versions)

### Bug summary
I've previously created issue #21783  which is already solved in 17.3.0-RC but there seems to be another issue regarding this, and that's because the DistributedBackgroundJobHostedService is running distributed jobs on the Subscriber instances even tough that they don't have to run there. 

When running Umbraco as a Subscriber with a read only database, the application is throwing errors that it cannot write to the database and stops functioning.

```
An exception occurred while attempting to run a distributed background job.
Microsoft.Data.SqlClient.SqlException (0x80131904): Failed to update database "XXXX" because the database is read-only.
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, SqlCommand command, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   at NPoco.Database.Execute(String sql, CommandType commandType, Object[] args)
   at Umbraco.Cms.Persistence.SqlServer.Services.SqlServerDistributedLockingMechanism.SqlServerDistributedLock.ObtainWriteLock()
   at Umbraco.Cms.Core.Scoping.LockingMechanism.LockInner(Guid instanceId, Dictionary`2& locks, HashSet`1& locksSet, Action`2 obtainLock, Nullable`1 timeout, Int32 lockId)
   at Umbraco.Cms.Infrastructure.Services.Implement.DistributedJobService.TryTakeRunnableAsync()
   at Umbraco.Cms.Infrastructure.BackgroundJobs.DistributedBackgroundJobHostedService.RunRunnableJob()
   at Umbraco.Cms.Infrastructure.BackgroundJobs.DistributedBackgroundJobHostedService.ExecuteAsync(CancellationToken stoppingToken)
```

### Specifics

_No response_

### Steps to reproduce

- Create an empty Umbraco Project using ```dotnet new umbraco -n MyCustomUmbracoProject```
- Start the project and make sure you select SQL Server as a database
- Finish the installation process and login
- Terminate the application
- Add the code to promote the instance to Subscriber as specified in the docs (https://docs.umbraco.com/umbraco-cms/fundamentals/setup/server-setup/load-balancing/flexible-advanced#explicit-schedulingpublisher-server)
- Set the database to read-only (ALTER DATABASE [YOURDB] SET READ_ONLY WITH NO_WAIT)
- Start the application and notice the errors.

### Expected result / actual result

The application should run without errors and should not require write access to the database.

### PR DESCRIPTION
**Pull request by NillasKA**
Closes #22191

### Description
This PR aims to prevent Distributed Background Jobs from running when the database is set to read-only.

From the recent implementation of https://github.com/umbraco/Umbraco-CMS/pull/22145 a `IDatabaseReadOnlyAccessor` was created and this PR makes use of this change to check if the database is Read-Only, and then simply returns when attempting to run any Distributed Background Jobs.

Due to Distributed Background Jobs attempting to run before the application is fully up and running, and before the database is ready, this check needs to be after the already implemented checks to see if the application is running.

I decided on not to add any logging or message when it skips a distributed background job, as to not flood the logging.

### CODE REVIEW

File: src/Umbraco.Infrastructure/BackgroundJobs/DistributedBackgroundJobHostedService.cs [hunk 1]
```diff
@@ -35,8 +37,27 @@ public DistributedBackgroundJobHostedService(
...
+        IRuntimeState runtimeState,
+        IDistributedJobService distributedJobService,
+        IOptionsMonitor<DistributedJobSettings> distributedJobSettings)
+        : this(
+            logger,
+            runtimeState,
+            distributedJobService,
+            distributedJobSettings,
+            StaticServiceProvider.Instance.GetRequiredService<IDatabaseReadOnlyAccessor>()
+            )
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/BackgroundJobs/DistributedBackgroundJobHostedService.cs]:
```suggestion
            StaticServiceProvider.Instance.GetRequiredService<IDatabaseReadOnlyAccessor>())
```

File: src/Umbraco.Infrastructure/BackgroundJobs/DistributedBackgroundJobHostedService.cs [hunk 2]
```diff
@@ -13,19 +16,18 @@ namespace Umbraco.Cms.Infrastructure.BackgroundJobs;
...
 {
+    private readonly IDatabaseReadOnlyAccessor _databaseReadOnlyAccessor;
     private readonly ILogger<DistributedBackgroundJobHostedService> _logger;
     private readonly IRuntimeState _runtimeState;
     private readonly IDistributedJobService _distributedJobService;
     private DistributedJobSettings _distributedJobSettings;
 
-    /// <summary>
-    /// Initializes a new instance of the <see cref="DistributedBackgroundJobHostedService"/> class.
-    /// </summary>
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/BackgroundJobs/DistributedBackgroundJobHostedService.cs:23]: Should keep this.  It doesn't add much value, but at least for consistency, and we have it on the obsolete constructor.

File: src/Umbraco.Infrastructure/BackgroundJobs/DistributedBackgroundJobHostedService.cs [hunk 3]
```diff
@@ -13,19 +16,18 @@ namespace Umbraco.Cms.Infrastructure.BackgroundJobs;
 /// </summary>
 public class DistributedBackgroundJobHostedService : BackgroundService
 {
+    private readonly IDatabaseReadOnlyAccessor _databaseReadOnlyAccessor;
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/BackgroundJobs/DistributedBackgroundJobHostedService.cs]: Suggest to put this below `private readonly IDistributedJobService _distributedJobService` on line 23.  Just to align with the constructor parameters.

File: src/Umbraco.Infrastructure/BackgroundJobs/DistributedBackgroundJobHostedService.cs [hunk 4]
```diff
@@ -35,8 +37,27 @@ public DistributedBackgroundJobHostedService(
         {
             _distributedJobSettings = options;
         });
+        _databaseReadOnlyAccessor = databaseReadOnlyAccessor;
     }
 
+    /// <summary>
+    /// Initializes a new instance of the <see cref="DistributedBackgroundJobHostedService"/> class.
+    /// </summary>
+    [Obsolete("Please use the constructor taking all parameters. Scheduled for removal in V19")]
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/BackgroundJobs/DistributedBackgroundJobHostedService.cs]:
```suggestion
    [Obsolete("Please use the constructor taking all parameters. Scheduled for removal in Umbraco 19.")]
```

For consistency - just in case we search for these messages.

File: src/Umbraco.Infrastructure/BackgroundJobs/DistributedBackgroundJobHostedService.cs [hunk 5]
```diff
@@ -47,6 +68,11 @@ protected override async Task ExecuteAsync(CancellationToken stoppingToken)
             await Task.Delay(_distributedJobSettings.Delay, stoppingToken);
         }
 
+        if (_databaseReadOnlyAccessor.IsReadOnly())
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/BackgroundJobs/DistributedBackgroundJobHostedService.cs:76]:
```suggestion
        // Distributed background jobs require write access to the database (e.g., to acquire locks, update job state).
        if (_databaseReadOnlyAccessor.IsReadOnly())
```

Would suggest we add a comment here, explaining why we have this check.
