### PR TITLE
Database Providers: Add support for providers offering sequence and null casting support (closes #21418)

### LINKED ISSUE #21418: NPoco DTO Features Instead of RAW SQL Statements (Part of #20453)
### Which Umbraco version are you using?

17.2.0-rc.preview.122

### Bug summary

There are some raw sql statements that should be replaced by _**NPoco**_'s features / methods..
This way we avoid naming issues and use typed objects.

This solves more requirements to solve #20453. 

### Specifics

This should not change existing behaviour!

### Steps to reproduce

All test must succeed.

### Expected result / actual result

_No response_

### PR DESCRIPTION
**Pull request by idseefeld**
All unit and integration test must succeed. Generated scripts for database must equal main branch.

### CODE REVIEW

**Comment by idseefeld** [comment]
@AndyButland The build errors are all about new methods in the `ISqlSyntaxProvider` which extend the interface for necessary features I need in my PostgreSql provider. `SqlSyntaxProviderBase` implements these in a simple way that should not change the behaviour for the existing database providers. The check complains a difference to the base NuGet package.
So I think this is nothing I could handle.

**Comment by AndyButland** [comment]
To avoid this @idseefeld, anything you add to an interface needs to have a default implementation - either a sensible default, or if there isn't a good one, throwing a `NotImplementationException`.

File: src/Umbraco.Infrastructure/Migrations/Install/DatabaseSchemaCreator.cs [hunk 1]
```diff
@@ -253,38 +293,52 @@ private void ValidateDbConstraints(DatabaseSchemaResult result)
...
         {
             result.ValidConstraints.Add(primaryKey);
         }
+    }
+
+    private static void AddErrorsForInvalidPrimaryKeys(DatabaseSchemaResult result, List<string> primaryKeysInDatabase, List<string?> primaryKeysInSchema)
+    {
+        IEnumerable<string> invalidPrimaryKeyDifferences = primaryKeysInDatabase!
+            .Except(primaryKeysInSchema, StringComparer.InvariantCultureIgnoreCase)!
+            .Union(primaryKeysInSchema.Except(primaryKeysInDatabase, StringComparer.InvariantCultureIgnoreCase))!;
```
[the remark this answers is not in the document]
Comment (idseefeld) [reply src/Umbraco.Infrastructure/Migrations/Install/DatabaseSchemaCreator.cs]: done

File: src/Umbraco.PublishedCache.HybridCache/Persistence/DatabaseCacheRepository.cs [hunk 2]
```diff
@@ -312,20 +312,30 @@ public async Task<IEnumerable<ContentCacheNode>> GetMediaSourcesAsync(IEnumerabl
...
+        else
+        {
+            Sql<ISqlContext> updateSql = Sql()
+                .Update<ContentNuDto>(u => u
+                    .Set(d => d.Data, newOrCachedEntity.Data)
+                    .Set(rd => rd.RawData, newOrCachedEntity.RawData)
+                    .Set(v => v.Rv, newOrCachedEntity.Rv))
+                .Where<ContentNuDto>(x => x.NodeId == newOrCachedEntity.NodeId && x.Published == newOrCachedEntity.Published);
+            await Database.ExecuteAsync(updateSql);
+        }
```
[the remark this answers is not in the document]
Comment (idseefeld) [reply src/Umbraco.PublishedCache.HybridCache/Persistence/DatabaseCacheRepository.cs]: reverted

File: src/Umbraco.Infrastructure/Migrations/Install/DatabaseSchemaCreator.cs [hunk 3]
```diff
@@ -223,25 +223,65 @@ internal DatabaseSchemaResult ValidateSchema(IEnumerable<Type> orderedTables)
...
+            .SelectMany(x =>
+                x.Columns
+                .Where(x => x.PrimaryKeyName.IsNullOrWhiteSpace() == false)
+                .Select(y => SqlSyntax.TruncateConstraintName<ColumnDefinition>(y.PrimaryKeyName)))
+            .ToList();
 
         // Add valid and invalid foreign key differences to the result object
         // We'll need to do invariant contains with case insensitivity because foreign key, primary key is not standardized
         // In theory you could have: FK_ or fk_ ...or really any standard that your development department (or developer) chooses to use.
+        HandleUnknowConstraints(result, unknownConstraintsInDatabase, foreignKeysInSchema, primaryKeysInSchema);
```
[the remark this answers is not in the document]
Comment (idseefeld) [reply src/Umbraco.Infrastructure/Migrations/Install/DatabaseSchemaCreator.cs]: done

File: src/Umbraco.Infrastructure/Migrations/Install/DatabaseSchemaCreator.cs [hunk 4]
```diff
@@ -223,25 +223,65 @@ internal DatabaseSchemaResult ValidateSchema(IEnumerable<Type> orderedTables)
...
+            .SelectMany(x =>
+                x.ForeignKeys
+                .Where(x => x is not null)
+                .Select(y => SqlSyntax.TruncateConstraintName<ForeignKeyDefinition>(y.Name)))
+            .ToList();
+
+        var primaryKeysInSchema = result.TableDefinitions
+            .SelectMany(x =>
+                x.Columns
+                .Where(x => x.PrimaryKeyName.IsNullOrWhiteSpace() == false)
```
[the remark this answers is not in the document]
Comment (idseefeld) [reply src/Umbraco.Infrastructure/Migrations/Install/DatabaseSchemaCreator.cs]: done

File: src/Umbraco.Infrastructure/Migrations/Install/DatabaseSchemaCreator.cs [hunk 5]
```diff
@@ -253,38 +293,52 @@ private void ValidateDbConstraints(DatabaseSchemaResult result)
...
-        IEnumerable<string?> invalidForeignKeyDifferences = foreignKeysInDatabase
-            .Except(foreignKeysInSchema, StringComparer.InvariantCultureIgnoreCase)
-            .Union(foreignKeysInSchema.Except(foreignKeysInDatabase, StringComparer.InvariantCultureIgnoreCase));
-        foreach (var foreignKey in invalidForeignKeyDifferences)
-        {
-            result.Errors.Add(new Tuple<string, string>("Constraint", foreignKey ?? "NULL"));
-        }
+    private static void AddValidPrimaryKeys(DatabaseSchemaResult result, List<string> primaryKeysInDatabase, List<string?> primaryKeysInSchema)
+    {
+        IEnumerable<string> validPrimaryKeyDifferences = primaryKeysInDatabase!
```
[the remark this answers is not in the document]
Comment (idseefeld) [reply src/Umbraco.Infrastructure/Migrations/Install/DatabaseSchemaCreator.cs]: done

File: src/Umbraco.PublishedCache.HybridCache/Persistence/DatabaseCacheRepository.cs [hunk 6]
```diff
@@ -312,20 +312,30 @@ public async Task<IEnumerable<ContentCacheNode>> GetMediaSourcesAsync(IEnumerabl
...
+        {
+            await Database.InsertAsync(newOrCachedEntity);
+        }
+        else
+        {
+            Sql<ISqlContext> updateSql = Sql()
+                .Update<ContentNuDto>(u => u
+                    .Set(d => d.Data, newOrCachedEntity.Data)
+                    .Set(rd => rd.RawData, newOrCachedEntity.RawData)
+                    .Set(v => v.Rv, newOrCachedEntity.Rv))
```
[the remark this answers is not in the document]
Comment (idseefeld) [reply src/Umbraco.PublishedCache.HybridCache/Persistence/DatabaseCacheRepository.cs]: reverted, see above

File: src/Umbraco.Infrastructure/Persistence/SqlSyntax/ISqlSyntaxProvider.cs [hunk 7]
```diff
@@ -115,6 +115,17 @@ DatabaseType GetUpdatedDatabaseType(DatabaseType current, string? connectionStri
...
 
+    /// <summary>
+    /// Gets the file extension associated with a null value for the specified type parameter.
+    /// </summary>
+    /// <remarks>This method is useful when generating SQL queries that require explicit type casting of NULL
+    /// values, such as in PostgreSQL. The returned string can be used directly in SQL statements for type-safe
+    /// comparisons or assignments.</remarks>
+    /// <typeparam name="T">The type for which to retrieve the null value file extension.</typeparam>
+    /// <returns>A string containing the file extension that represents a null value for type T, or an empty string if no
+    /// extension is defined.</returns>
```
[the remark this answers is not in the document]
Comment (idseefeld) [reply src/Umbraco.Infrastructure/Persistence/SqlSyntax/ISqlSyntaxProvider.cs]: good point

File: src/Umbraco.Infrastructure/Migrations/Install/DatabaseSchemaCreator.cs [hunk 8]
```diff
@@ -223,25 +223,65 @@ internal DatabaseSchemaResult ValidateSchema(IEnumerable<Type> orderedTables)
...
+        AddErrorsForInvalidForeignKeys(result, foreignKeysInDatabase, foreignKeysInSchema);
+
+        // Primary keys:
+        // Add valid and invalid primary key differences to the result object
+        AddValidPrimaryKeys(result, primaryKeysInDatabase, primaryKeysInSchema);
+
+        AddErrorsForInvalidPrimaryKeys(result, primaryKeysInDatabase, primaryKeysInSchema);
+    }
+
+    private static void HandleUnknowConstraints(DatabaseSchemaResult result, List<string> unknownConstraintsInDatabase, List<string?> foreignKeysInSchema, List<string?> primaryKeysInSchema)
```
[the remark this answers is not in the document]
Comment (idseefeld) [reply src/Umbraco.Infrastructure/Migrations/Install/DatabaseSchemaCreator.cs]: duplicate

File: src/Umbraco.Infrastructure/Migrations/Install/DatabaseSchemaCreator.cs (hunk 4 above)
[the remark this answers is not in the document]
Comment (idseefeld) [reply src/Umbraco.Infrastructure/Migrations/Install/DatabaseSchemaCreator.cs]: duplicate

**Comment by idseefeld** [comment]
@AndyButland  Thanks for the hint!
💡I must have missed, that you can now provide such default implementation in interfaces. 🙄😁

File: src/Umbraco.Infrastructure/Migrations/Install/DatabaseSchemaCreator.cs [hunk 9]
```diff
@@ -103,22 +103,22 @@ public class DatabaseSchemaCreator
...
-            _installDefaultDataSettings = defaultDataCreationSettings;  // TODO (V13): Rename this parameter to installDefaultDataSettings.
-
-        if (_database?.SqlContext?.SqlSyntax == null)
+    public DatabaseSchemaCreator(
+        IUmbracoDatabase? database,
+        ILogger<DatabaseSchemaCreator> logger,
+        ILoggerFactory loggerFactory,
+        IUmbracoVersion umbracoVersion,
+        IEventAggregator eventAggregator,
+        IOptionsMonitor<InstallDefaultDataSettings> installDefaultDataSettings)
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Migrations/Install/DatabaseSchemaCreator.cs]: Being very strict, but this could be a breaking change for a caller, if they were using named parameters in constructing this class.  Super unlikely, but possible, so we should avoid.  I think you will have to leave as is, and restore and change the comment to `// TODO (V18): Rename this parameter to installDefaultDataSettings`.
```suggestion
        IOptionsMonitor<InstallDefaultDataSettings> defaultDataCreationSettings)
```

File: src/Umbraco.Infrastructure/Migrations/Install/DatabaseSchemaCreator.cs [hunk 10]
```diff
@@ -103,22 +103,22 @@ public class DatabaseSchemaCreator
...
+    {
+        _database = database ?? throw new ArgumentNullException(nameof(database));
+        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
+        _loggerFactory = loggerFactory ?? throw new ArgumentNullException(nameof(loggerFactory));
+        _umbracoVersion = umbracoVersion ?? throw new ArgumentNullException(nameof(umbracoVersion));
+        _eventAggregator = eventAggregator;
+        _installDefaultDataSettings = installDefaultDataSettings;
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Migrations/Install/DatabaseSchemaCreator.cs]:
```suggestion
        _installDefaultDataSettings = defaultDataCreationSettings;  // TODO (V18): Rename this parameter to installDefaultDataSettings
```

File: src/Umbraco.Infrastructure/Migrations/Install/DatabaseSchemaCreator.cs [hunk 11]
```diff
@@ -223,25 +223,65 @@ internal DatabaseSchemaResult ValidateSchema(IEnumerable<Type> orderedTables)
...
+
+        var primaryKeysInDatabase = allConstraintsInDatabase
+            .Where(x => x.InvariantStartsWith("PK_"))
+            .ToList();
+
+        var unknownConstraintsInDatabase = allConstraintsInDatabase
+            .Where(
+            x => x.InvariantStartsWith("FK_") == false
+                && x.InvariantStartsWith("PK_") == false
+                && x.InvariantStartsWith("IX_") == false).ToList();
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Migrations/Install/DatabaseSchemaCreator.cs]:
```suggestion
        var unknownConstraintsInDatabase = allConstraintsInDatabase
            .Where( x => x.InvariantStartsWith("FK_") == false &&
                         x.InvariantStartsWith("PK_") == false &&
                         x.InvariantStartsWith("IX_") == false)
            .ToList();
```

File: src/Umbraco.Infrastructure/Migrations/Install/DatabaseSchemaCreator.cs [hunk 12]
```diff
@@ -223,25 +223,65 @@ internal DatabaseSchemaResult ValidateSchema(IEnumerable<Type> orderedTables)
...
+
+        var foreignKeysInSchema = result.TableDefinitions
+            .SelectMany(def =>
+                def.ForeignKeys
+                .Where(fk => fk is not null)
+                .Select(fk => SqlSyntax.TruncateConstraintName<ForeignKeyDefinition>(fk.Name)))
+            .ToList();
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Migrations/Install/DatabaseSchemaCreator.cs:263]:
```suggestion
        var foreignKeysInSchema = result.TableDefinitions
            .SelectMany(def =>
                def.ForeignKeys
                    .Where(fk => fk is not null)
                    .Select(fk => SqlSyntax.TruncateConstraintName<ForeignKeyDefinition>(fk.Name)))
            .ToList();
```

File: src/Umbraco.Infrastructure/Migrations/Install/DatabaseSchemaCreator.cs [hunk 13]
```diff
@@ -223,25 +223,65 @@ internal DatabaseSchemaResult ValidateSchema(IEnumerable<Type> orderedTables)
...
+
+        var primaryKeysInSchema = result.TableDefinitions
+            .SelectMany(def =>
+                def.Columns
+                .Where(col => col.PrimaryKeyName.IsNullOrWhiteSpace() == false)
+                .Select(col => SqlSyntax.TruncateConstraintName<ColumnDefinition>(col.PrimaryKeyName)))
+            .ToList();
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Migrations/Install/DatabaseSchemaCreator.cs:270]:
```suggestion
        var primaryKeysInSchema = result.TableDefinitions
            .SelectMany(def =>
                def.Columns
                    .Where(col => col.PrimaryKeyName.IsNullOrWhiteSpace() == false)
                    .Select(col => SqlSyntax.TruncateConstraintName<ColumnDefinition>(col.PrimaryKeyName)))
            .ToList();
```

File: src/Umbraco.Infrastructure/Persistence/SqlSyntax/ISqlSyntaxProvider.cs [hunk 14]
```diff
@@ -115,6 +115,21 @@ DatabaseType GetUpdatedDatabaseType(DatabaseType current, string? connectionStri
...
+    /// This method is useful when generating SQL queries that require explicit type casting of NULL values,
+    /// such as in PostgreSQL. The returned string can be used directly in SQL statements for type-safe
+    /// comparisons or assignments (for example, <c>::integer</c> or <c>::text</c>).
+    /// </remarks>
+    /// <typeparam name="T">The type for which to retrieve the SQL null type annotation.</typeparam>
+    /// <returns>
+    /// A string containing the SQL type cast extension (null type annotation) that represents a null value for type
+    /// <typeparamref name="T"/>, or an empty string if no extension is defined.
+    /// </returns>
+    string GetNullExtension<T>() => throw new NotImplementedException();
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/SqlSyntax/ISqlSyntaxProvider.cs]: I think the default implementation here could be the same as used for SQL and SQLite, which is `string.Empty`.  In this case, this seems a sensible default, which is better than throwing an exception.

File: src/Umbraco.Infrastructure/Migrations/Install/DatabaseSchemaCreator.cs [hunk 15]
```diff
@@ -223,25 +223,65 @@ internal DatabaseSchemaResult ValidateSchema(IEnumerable<Type> orderedTables)
...
+        var allConstraintsInDatabase = SqlSyntax
+            .GetConstraintsPerColumn(_database)
+            .DistinctBy(x => x.Item3)
+            .Select(x => x.Item3)
+            .ToList();
+
+        if (allConstraintsInDatabase.Count == 0)
+        {
+            return;
+        }
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Migrations/Install/DatabaseSchemaCreator.cs]: This seems sensible, but is actually a behavioural change by the looks of it:

If the database has 0 constraints but the schema defines constraints:
  - Current behaviour: Would report schema constraints as errors (missing from database)
  - New behaviour: Exits early, reports nothing

So I think we need to remove this early return that you have added.

File: src/Umbraco.Infrastructure/Migrations/Install/DatabaseSchemaCreator.cs [hunk 16]
```diff
@@ -223,25 +223,65 @@ internal DatabaseSchemaResult ValidateSchema(IEnumerable<Type> orderedTables)
...
+            .Where(
+            x => x.InvariantStartsWith("FK_") == false
+                && x.InvariantStartsWith("PK_") == false
+                && x.InvariantStartsWith("IX_") == false).ToList();
+
+        var foreignKeysInSchema = result.TableDefinitions
+            .SelectMany(def =>
+                def.ForeignKeys
+                .Where(fk => fk is not null)
+                .Select(fk => SqlSyntax.TruncateConstraintName<ForeignKeyDefinition>(fk.Name)))
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Migrations/Install/DatabaseSchemaCreator.cs]: This has been swapped around from the previous logic - so the null check is on the object, whereas previously it was on the name.  Seems like it should work the same, but unless this was a deliberate change, suggest we revert back.

File: src/Umbraco.Infrastructure/Persistence/SqlSyntax/ISqlSyntaxProvider.cs [hunk 17]
```diff
@@ -228,4 +265,12 @@ Sql<ISqlContext>.SqlJoinClause<ISqlContext> LeftJoinWithNestedJoin<TDto>(
...
         Func<Sql<ISqlContext>, Sql<ISqlContext>> nestedJoin,
         string? alias = null);
+
+    /// <summary>
+    /// Some databases have a maximum length for constraint names, this method truncates the name if necessary.
+    /// </summary>
+    /// <typeparam name="T">type of the entity.</typeparam>
+    /// <param name="constraintName">unlimited name.</param>
+    /// <returns>truncated name.</returns>
+    string? TruncateConstraintName<T>(string? constraintName) => throw new NotImplementedException();
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/SqlSyntax/ISqlSyntaxProvider.cs]: The default here could be to return the provided name unchanged I would say.

File: src/Umbraco.Infrastructure/Persistence/SqlSyntax/ISqlSyntaxProvider.cs (hunk 14 above)
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/SqlSyntax/ISqlSyntaxProvider.cs]: For all the default interface implementations in this interface, please can you add a comment like the following:

```
// TODO (V18): Remove the default implementations in this interface.
```

There can just be one, at the top of the file.

Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/SqlSyntax/ISqlSyntaxProvider.cs]: Can you think on the name here?  `GetNullExtension` doesn't feel quite right to me, but then again, I'm not familiar with this feature, so maybe it's OK in your view.  But reading the comments would `GetNullCastSuffix` be better?  As I say, I'm not sure, here, so just want to make sure we get the name right before it's added to the interface and then "baked in".

File: src/Umbraco.Infrastructure/Persistence/SqlSyntax/SqlSyntaxProviderBase.cs [hunk 18]
```diff
@@ -684,4 +696,6 @@ protected virtual string FormatDefaultValue(ColumnDefinition column)
     protected abstract string? FormatSystemMethods(SystemMethods systemMethod);
 
     protected abstract string FormatIdentity(ColumnDefinition column);
+
+    public virtual string? TruncateConstraintName<T>(string? constraintName) => constraintName;
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/SqlSyntax/SqlSyntaxProviderBase.cs]:
```suggestion
    /// <inheritdoc />
    public virtual string? TruncateConstraintName<T>(string? constraintName) => constraintName;
```

**Review by AndyButland — CHANGES_REQUESTED** [review]
Looks good to me @idseefeld.  I think it'll be fine to merge these in to support your efforts, but there are a few small things I flagged to consider and fix, if you could take a look please.

File: src/Umbraco.Infrastructure/Migrations/Install/DatabaseSchemaCreator.cs (hunk 9 above)
Comment (idseefeld) [reply src/Umbraco.Infrastructure/Migrations/Install/DatabaseSchemaCreator.cs]: Ok, was done before v17, now it has to wait until v18. I don't really care about this.

File: src/Umbraco.Infrastructure/Migrations/Install/DatabaseSchemaCreator.cs (hunk 16 above)
Comment (idseefeld) [reply src/Umbraco.Infrastructure/Migrations/Install/DatabaseSchemaCreator.cs]: You are right. The null check was on the name. But I think it should happen before the `Select` with the new `TruncateConstraintName` method to avoid unnecessary method calls.

So I change it to:
```
.Where(fk => fk.Name is not null)
.Select(fk => SqlSyntax.TruncateConstraintName<ForeignKeyDefinition>(fk.Name)))
```

File: src/Umbraco.Infrastructure/Persistence/SqlSyntax/ISqlSyntaxProvider.cs (hunk 17 above)
Comment (idseefeld) [reply src/Umbraco.Infrastructure/Persistence/SqlSyntax/ISqlSyntaxProvider.cs]: My intention was to make clear that this needs to be implemented as virtual in `class SqlSyntaxProviderBase`.
These default implementations caused me some trouble. 😉
So I am happy about your next comment to remove these in v18. I personally think this interface extension was not a good idea - may be I just not used to it. 🤔

File: src/Umbraco.Infrastructure/Persistence/SqlSyntax/ISqlSyntaxProvider.cs (hunk 14 above)
Comment (idseefeld) [reply src/Umbraco.Infrastructure/Persistence/SqlSyntax/ISqlSyntaxProvider.cs]: `GetNullCastSuffix`sounds better to me too.

**Comment by idseefeld** [comment]
@AndyButland I'll do a final check that the review change will work...

File: src/Umbraco.Infrastructure/Migrations/Install/DatabaseSchemaCreator.cs (hunk 15 above)
Comment (idseefeld) [reply src/Umbraco.Infrastructure/Migrations/Install/DatabaseSchemaCreator.cs]: Right, I remove the early exit.

File: src/Umbraco.Infrastructure/Migrations/Install/DatabaseSchemaCreator.cs [hunk 19]
```diff
@@ -517,9 +569,16 @@ internal void CreateTable(bool overwrite, Type modelType, DatabaseDataCreator da
...
-            _database.Execute(new Sql($"SET IDENTITY_INSERT {SqlSyntax.GetQuotedTableName(tableName)} OFF;"));
+            if (SqlSyntax.SupportsIdentityInsert())
+            {
+                _database.Execute(new Sql($"SET IDENTITY_INSERT {SqlSyntax.GetQuotedTableName(tableName)} OFF;"));
+            }
+            else if (SqlSyntax.SupportsSequences())
+            {
+                SqlSyntax.AlterSequences(_database, tableName);
+            }
         }
```
[the remark this answers is not in the document]
Comment (idseefeld) [reply src/Umbraco.Infrastructure/Migrations/Install/DatabaseSchemaCreator.cs:596]: ok, currently only SupportsIdentityInsert or SupportsSequences is possible, but maybe other database need both independently - so just in case.

File: src/Umbraco.Infrastructure/Migrations/Install/DatabaseSchemaCreator.cs [hunk 20]
```diff
@@ -224,28 +224,64 @@ internal DatabaseSchemaResult ValidateSchema(IEnumerable<Type> orderedTables)
...
+
+        AddErrorsForInvalidPrimaryKeys(result, primaryKeysInDatabase, primaryKeysInSchema);
+    }
+
+    private static void HandleUnknownConstraints(DatabaseSchemaResult result, List<string> unknownConstraintsInDatabase, List<string> foreignKeysInSchema)
+    {
+        foreach (string unknown in unknownConstraintsInDatabase)
         {
-            if (foreignKeysInSchema!.InvariantContains(unknown) || primaryKeysInSchema!.InvariantContains(unknown))
+            if (foreignKeysInSchema.InvariantContains(unknown) || foreignKeysInSchema.InvariantContains(unknown))
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Migrations/Install/DatabaseSchemaCreator.cs]: Looks like there's a bug here - the original code checked both `foreignKeysInSchema` and `primaryKeysInSchema`. The second check should be `primaryKeysInSchema`, but `primaryKeysInSchema` is not passed to this method.

File: src/Umbraco.Infrastructure/Persistence/SqlSyntax/ISqlSyntaxProvider.cs [hunk 21]
```diff
@@ -157,6 +174,41 @@ DatabaseType GetUpdatedDatabaseType(DatabaseType current, string? connectionStri
...
+    /// Determines whether the current database provider supports sequence objects for generating numeric values like PostgreSQL.
+    /// </summary>
+    /// <returns>true if the provider supports sequences; otherwise, false.</returns>
+    bool SupportsSequences() => false;
+
+    /// <summary>
+    /// Alters the database sequences to match the current schema requirements.
+    /// </summary>
+    /// Alters the database sequences to match the current schema requirements for providers that support sequences.
+    /// </summary>
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/SqlSyntax/ISqlSyntaxProvider.cs]:
```suggestion
    /// <summary>
    /// Alters the database sequences to match the current schema requirements.
    /// </summary>
```

File: src/Umbraco.Infrastructure/Persistence/SqlSyntax/ISqlSyntaxProvider.cs [hunk 22]
```diff
@@ -157,6 +174,41 @@ DatabaseType GetUpdatedDatabaseType(DatabaseType current, string? connectionStri
...
+    /// <remarks>
+    /// This is an optional extension point for SQL providers that support database sequences. Providers that support
+    /// sequences should override this method to update sequences associated with the specified table when schema changes
+    /// require it. Callers should typically check <see cref="SupportsSequences"/> before invoking this method. The default
+    /// implementation throws <see cref="NotImplementedException"/>.
+    /// </remarks>
+    /// <param name="database">The database connection to use for altering the sequences.</param>
+    /// <param name="tableName">The name of the table whose sequences will be altered.</param>
+    void AlterSequences(IUmbracoDatabase database, string tableName)
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/SqlSyntax/ISqlSyntaxProvider.cs]: We should align the default implementation here with the other overload of `AlterSequences`.  Currently one throws a `NotImplementedException` and the other just has a no-operation, which is inconsistent.  I think `NotImplementedException` is the right approach here (especially as the intention is that you call `SupportsSequences` before invoking the method.

File: src/Umbraco.Infrastructure/Persistence/SqlSyntax/SqlSyntaxProviderBase.cs [hunk 23]
```diff
@@ -257,6 +260,15 @@ public abstract Sql<ISqlContext>.SqlJoinClause<ISqlContext> LeftJoinWithNestedJo
...
     public virtual bool SupportsIdentityInsert() => true;
 
+    /// <inheritdoc />
+    public virtual bool SupportsSequences() => false;
+
+    /// <inheritdoc />
+    public virtual void AlterSequences(IUmbracoDatabase database) { }
+
+    /// <inheritdoc />
+    public virtual void AlterSequences(IUmbracoDatabase database, string tableName) { }
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/SqlSyntax/SqlSyntaxProviderBase.cs]: I think these should throw a `NotSupportedException`.  Again, as the intention is to use them after calling `SupportsSequences`.

File: src/Umbraco.Infrastructure/Migrations/Install/DatabaseSchemaCreator.cs (hunk 20 above)
Comment (idseefeld) [reply src/Umbraco.Infrastructure/Migrations/Install/DatabaseSchemaCreator.cs]: Indeed looks like a bug. I think integration test should find it, but seems not. 🤔

Comment (idseefeld) [reply src/Umbraco.Infrastructure/Migrations/Install/DatabaseSchemaCreator.cs]: I have fixed it to the previous behaviour!
Actually I cannot see which use case gets addressed here. 
When a constraint is in the desired schema, why should it be unknown?
But I do not care for my project. So it's ok.

File: src/Umbraco.Infrastructure/Persistence/SqlSyntax/SqlSyntaxProviderBase.cs [hunk 24]
```diff
@@ -257,6 +260,15 @@ public abstract Sql<ISqlContext>.SqlJoinClause<ISqlContext> LeftJoinWithNestedJo
 
     public virtual bool SupportsIdentityInsert() => true;
 
+    /// <inheritdoc />
+    public virtual bool SupportsSequences() => false;
+
+    /// <inheritdoc />
+    public virtual void AlterSequences(IUmbracoDatabase database) => throw new NotImplementedException();
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/SqlSyntax/SqlSyntaxProviderBase.cs]:
```suggestion
    public virtual void AlterSequences(IUmbracoDatabase database) => throw new NotSupportedException();
```

As suggested in previous comment, I think `NotSupportedException` makes most sense on a method like this, intended to be used only after checking for support.

File: src/Umbraco.Infrastructure/Persistence/SqlSyntax/SqlSyntaxProviderBase.cs [hunk 25]
```diff
@@ -257,6 +260,15 @@ public abstract Sql<ISqlContext>.SqlJoinClause<ISqlContext> LeftJoinWithNestedJo
...
+
+    /// <inheritdoc />
+    public virtual void AlterSequences(IUmbracoDatabase database, string tableName) => throw new NotImplementedException();
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/SqlSyntax/SqlSyntaxProviderBase.cs]:
```suggestion
    public virtual void AlterSequences(IUmbracoDatabase database, string tableName) => throw new NotSupportedException();
```
