### PR TITLE
Content Version Cleanup: Optimize for large datasets (closes #22224)

### LINKED ISSUE #22224: Cleanup job ineffective with very large history
### Which Umbraco version are you using?

16.5.0

### Bug summary

When you have a massive history, the history cleanup job fails because it's unable to complete the cleanup because of SQL timeouts. I could increase the timeout, but I feel like the cleanup is rather inefficient.

### Specifics

We've had multiple sites where we made the mistake to update nodes in a background job every 5 minutes. Instead of checking if the content changes, we always updates the nodes using save and save and publish. This causes a massive backlog of revision and history.

The issue is that with that many records, the cleanup job simply can't run correctly anymore and gets timeouts. It also puts quite some load on the database.

Now I agree that we made a mistake with the node updates, but on the other hand, I feel like the cleanup job should handle this better. I understand it's a heavy operation, but when the situation is the most dire and we need the cleanup the hardest, it fails. And maybe, the cleanup will always be slow and stress the database, but a quick check uncovered at least a number of inefficiencies that could be improved to make it faster:

- **`GetDocumentVersionsEligibleForCleanup()` loads every eligible row into .NET memory with no limit** ([`DocumentVersionRepository.cs` L32–58](https://github.com/umbraco/Umbraco-CMS/blob/51b7fbf5ee89709385f38f082fa3c3c6cb117487/src/Umbraco.Infrastructure/Persistence/Repositories/Implement/DocumentVersionRepository.cs#L32-L58)). The SQL query has no `TOP`, no date pre-filter, and no row cap. On a high-frequency save site this can be millions of rows fetched in a single `Fetch<ContentVersionMeta>` call.

- **All policy filtering happens in C# memory, not in SQL** ([`DefaultContentVersionCleanupPolicy.cs` L53–91](https://github.com/umbraco/Umbraco-CMS/blob/51b7fbf5ee89709385f38f082fa3c3c6cb117487/src/Umbraco.Core/Services/DefaultContentVersionCleanupPolicy.cs#L53-L91)). Every row is iterated in a `foreach`, date arithmetic is computed per-row in C#, and a `GroupBy` + `OrderByDescending().Skip(1)` is applied entirely in application memory — logic that SQL Server could execute as a single indexed set operation.

- **A `ContentDeletingVersionsNotification` is fired individually for every single version before any deletion begins** ([`ContentVersionService.cs` L267–282](https://github.com/umbraco/Umbraco-CMS/blob/51b7fbf5ee89709385f38f082fa3c3c6cb117487/src/Umbraco.Core/Services/ContentVersionService.cs#L267-L282)). This allocates a new `EventMessages` object and dispatches a cancellable notification per version in a tight loop, all in a single scope before any rows are deleted.

- **Each delete batch issues 4 separate `DELETE` statements** ([`DocumentVersionRepository.cs` L137–173](https://github.com/umbraco/Umbraco-CMS/blob/51b7fbf5ee89709385f38f082fa3c3c6cb117487/src/Umbraco.Infrastructure/Persistence/Repositories/Implement/DocumentVersionRepository.cs#L137-L173)): one each against `umbracoPropertyData`, `umbracoContentVersionCultureVariation`, `umbracoDocumentVersion`, and `umbracoContentVersion` — 4 round-trips per batch of up to 2,000 IDs.

- **The slow approach of batching with `WHERE id IN (...)` is explicitly acknowledged in the code as a SQL CE workaround** ([`ContentVersionService.cs` L226–229](https://github.com/umbraco/Umbraco-CMS/blob/51b7fbf5ee89709385f38f082fa3c3c6cb117487/src/Umbraco.Core/Services/ContentVersionService.cs#L226-L229)): _"If we weren't supporting SQL CE we could do TVP, or use temp tables to bulk delete with joins to our list of version ids to nuke (much nicer, we can kill 100k in sub second time-frames). However we are supporting SQL CE"_ — **SQL CE was removed in Umbraco 9 and this code was never updated**.

- **`ContentVersionCleanupJob.ExecuteAsync()` is not actually async** ([`ContentVersionCleanupJob.cs` L39–55](https://github.com/umbraco/Umbraco-CMS/blob/51b7fbf5ee89709385f38f082fa3c3c6cb117487/src/Umbraco.Infrastructure/BackgroundJobs/Jobs/DistributedJobs/ContentVersionCleanupJob.cs#L39-L55)). It calls `_service.PerformContentVersionCleanup(DateTime.UtcNow).Count` synchronously and returns `Task.CompletedTask`. There is no `CancellationToken`, so the job cannot be interrupted if it runs too long.

- **There is no cap on how many versions are processed per run.** The entire eligible set is fetched, filtered, and deleted in one execution with no `maxVersionsPerRun` setting, meaning a large backlog always produces a run proportional to its size with no mechanism to spread work across multiple hourly executions.

### Steps to reproduce

There is not much more to say than have a massive history. I think the size of the umbracoPropertyData is actually the biggest issue. Is houses a record for each property for each version and this table gets MASSIVE.

### Expected result / actual result

I expect the cleanup to eventually succeed. It's OK if it takes a little longer and it's OK if it stresses the database a little. But it shouldn't fail under normal conditions, making the problem worse and worse.

### PR DESCRIPTION
**Pull request by AndyButland**
## Description

https://github.com/umbraco/Umbraco-CMS/issues/22224 reports some practical issues with the content version clean-up background job when there are very large amounts of versions to handle.  As noted in response, whilst the clean-up job doesn't often have much to do when running regularly every hour, on first usage, particularly on a site that has built up many versions, it will run slowly, use a lot of memory, and risk timeouts and locking issues.

The issue reporter points out some areas where we can optimise, which I've looked at in this PR.

### Optimizations

**SQL date pre-filtering**: The `GetDocumentVersionsEligibleForCleanup` query now accepts an `olderThan` date parameter, pushing the `KeepAllVersionsNewerThanDays` cut-off into SQL.  Previously the job loaded **all** eligible versions into memory with no limit, and applied filtering in memory.

The effective cut-off is computed as the minimum across global and all per-content-type override policies.

**Per-run cap** (`MaxVersionsToDeletePerRun`): New configuration setting (default 50,000) limits how many versions are processed per hourly run. Large version histories are cleaned up incrementally across multiple runs instead of attempting everything at once and timing out. A value of 0 can be configured still, to mean no limit.

This value is passed to the repository method that now accepts an optional `maxCount` parameter using the existing cross-database `SelectTop` extension, with `ORDER BY versionDate ASC` to process oldest versions first.

**Temp table bulk deletes**: `DeleteVersions` now inserts version IDs into a temporary table and runs 4 `DELETE ... WHERE id IN (SELECT Id FROM temp)` statements instead of batched `WHERE IN (@0, @1, ..., @1999)`. This lets the database engine use indexed joins against the temp table PK, which is significantly faster for large sets — especially against `umbracoPropertyData` which has multiple rows per version.

The optimisation was noted as an option once we no longer support SQL CE, which didn't support temp tables.  As we now don't, there seems no reason not to use this approach.

### Automated

Before making any changes I extended the integration test coverage so we can verify that the new functionality works as expected.

### Manual

_AB: I've gone through all of the following in my own testing of the work in this PR_.

#### Prerequisites

- A running Umbraco instance with SQL Server or SQLite
- Access to the database for running queries
- Access to the Umbraco log files (typically `umbraco/Logs/UmbracoTraceLog.*.json`)

#### Setup: Create test content with version history

1. In the backoffice, create a document type "Test Page" with a single text property.
2. Create a content node "Test Content" using this type.
3. Save and publish it, then make 20+ further publishes to build up version history.
4. Verify version count:
   ```sql
   SELECT COUNT(*)
   FROM umbracoContentVersion cv
   INNER JOIN umbracoContent c ON cv.nodeId = c.nodeId
   INNER JOIN cmsContentType ct ON c.contentTypeId = ct.nodeId
   INNER JOIN umbracoNode n ON ct.nodeId = n.id
   WHERE n.uniqueId = '<document-type-guid>'
   ```
   You should see 20+ rows.

#### Test 1: Basic cleanup with default settings

**Goal**: Verify the cleanup job works end-to-end with the default configuration.

1. Enable cleanup in `appsettings.json`:
   ```json
   {
     "Umbraco": {
       "CMS": {
         "Content": {
           "ContentVersionCleanupPolicy": {
             "EnableCleanup": true,
             "KeepAllVersionsNewerThanDays": 7,
             "KeepLatestVersionPerDayForDays": 90
           }
         }
       }
     }
   }
   ```
2. Backdate most versions so they exceed the 7-day window:
   ```sql
   -- Keep the 2 most recent (current draft + published), backdate the rest
   UPDATE umbracoContentVersion
   SET versionDate = DATEADD(day, -30, GETUTCDATE())
   WHERE [current] = 0
     AND id NOT IN (
       SELECT TOP 2 id FROM umbracoContentVersion ORDER BY id DESC
     )
     AND nodeId IN (
       SELECT c.nodeId
       FROM umbracoContent c
       INNER JOIN cmsContentType ct ON c.contentTypeId = ct.nodeId
       INNER JOIN umbracoNode n ON ct.nodeId = n.id
       WHERE n.uniqueId =  '<document-type-guid>'
     )
   ```
   For SQLite use:
   ```sql
   UPDATE umbracoContentVersion
   SET versionDate = datetime('now', '-30 days')
   WHERE "current" = 0
     AND id NOT IN (
       SELECT id FROM umbracoContentVersion ORDER BY id DESC LIMIT 2
     )
     AND nodeId IN (
       SELECT c.nodeId
       FROM umbracoContent c
       INNER JOIN cmsContentType ct ON c.contentTypeId = ct.nodeId
       INNER JOIN umbracoNode n ON ct.nodeId = n.id
       WHERE n.uniqueId =  '<document-type-guid>'
     )
   ```
3. Wait for the cleanup job to run (runs every hour by default, so configure to run more frequently - line 17 of `ContentVersionCleanupJob`).
4. Check the logs for:
   ```
   Deleted {N} ContentVersion(s)
   ```
5. Verify versions were removed:
   ```sql
   SELECT COUNT(*)
   FROM umbracoContentVersion cv
   INNER JOIN umbracoContent c ON cv.nodeId = c.nodeId
   INNER JOIN cmsContentType ct ON c.contentTypeId = ct.nodeId
   INNER JOIN umbracoNode n ON ct.nodeId = n.id
   WHERE n.uniqueId = '<document-type-guid>'
   ```

Only the current draft, current published, and up to one version per calendar day within the `KeepLatestVersionPerDayForDays` window should remain.

6. Verify related tables were cleaned:
   ```sql
   SELECT COUNT(*)
   FROM umbracoPropertyData pd
   INNER JOIN umbracoContentVersion cv ON pd.versionId = cv.id
   INNER JOIN umbracoContent c ON cv.nodeId = c.nodeId
   INNER JOIN cmsContentType ct ON c.contentTypeId = ct.nodeId
   INNER JOIN umbracoNode n ON ct.nodeId = n.id
   WHERE n.uniqueId =  '<document-type-guid>'

   SELECT COUNT(*)
   FROM umbracoDocumentVersion dv
   INNER JOIN umbracoContentVersion cv ON dv.id = cv.id
   INNER JOIN umbracoContent c ON cv.nodeId = c.nodeId
   INNER JOIN cmsContentType ct ON c.contentTypeId = ct.nodeId
   INNER JOIN umbracoNode n ON ct.nodeId = n.id
   WHERE n.uniqueId =  '<document-type-guid>'

   SELECT COUNT(*)
   FROM umbracoContentVersionCultureVariation ccv
   INNER JOIN umbracoContentVersion cv ON ccv.versionId = cv.id
   INNER JOIN umbracoContent c ON cv.nodeId = c.nodeId
   INNER JOIN cmsContentType ct ON c.contentTypeId = ct.nodeId
   INNER JOIN umbracoNode n ON ct.nodeId = n.id
   WHERE n.uniqueId = '<document-type-guid>'
   ```

#### Test 2: KeepLatestVersionPerDayForDays retains one per day

**Goal**: Verify that versions between 7 and 90 days old are rolled up to one per day.

1. Create a content node and publish it 10+ times.
2. Backdate versions across multiple calendar days with several versions per day:
   ```sql
   -- Put 3 versions on day -20 and 3 on day -40
   UPDATE umbracoContentVersion
   SET versionDate = DATEADD(day, -20, GETUTCDATE())
   WHERE id IN (
       SELECT TOP 3 cv.id
       FROM umbracoContentVersion cv
       INNER JOIN umbracoContent c ON cv.nodeId = c.nodeId
       INNER JOIN cmsContentType ct ON c.contentTypeId = ct.nodeId
       INNER JOIN umbracoNode n ON ct.nodeId = n.id
       WHERE n.uniqueId = '<document-type-guid>' AND cv.[current] = 0
      ORDER BY cv.id ASC
   )

   UPDATE umbracoContentVersion
   SET versionDate = DATEADD(day, -40, GETUTCDATE())
   WHERE id IN (
       SELECT cv.id
       FROM umbracoContentVersion cv
       INNER JOIN umbracoContent c ON cv.nodeId = c.nodeId
       INNER JOIN cmsContentType ct ON c.contentTypeId = ct.nodeId
       INNER JOIN umbracoNode n ON ct.nodeId = n.id
       WHERE n.uniqueId = '<document-type-guid>' AND cv.[current] = 0
       ORDER BY cv.id ASC
       OFFSET 3 ROWS FETCH NEXT 3 ROWS ONLY
   )
   ```
3. Enable cleanup with `KeepAllVersionsNewerThanDays = 0` and `KeepLatestVersionPerDayForDays = 90`.
4. Wait for cleanup to run.
5. Verify: for each calendar day older than `KeepAllVersionsNewerThanDays`, only the newest version (highest id) per content node should survive. Versions within the `KeepAllVersionsNewerThanDays` window are all preserved. Check::
   ```sql
   SELECT cv.id, cv.nodeId, cv.versionDate, cv.[current]
   FROM umbracoContentVersion cv
   INNER JOIN umbracoContent c ON cv.nodeId = c.nodeId
   INNER JOIN cmsContentType ct ON c.contentTypeId = ct.nodeId
   INNER JOIN umbracoNode n ON ct.nodeId = n.id
   WHERE n.uniqueId = '<document-type-guid>'
   ORDER BY cv.versionDate, cv.id
   ```

#### Test 3: MaxVersionsToDeletePerRun caps the work

**Goal**: Verify the per-run cap limits how many versions are deleted in a single run.

1. Create a content node and publish it 20+ times to create many versions.
2. Backdate all historic versions:
   ```sql
   UPDATE umbracoContentVersion
   SET versionDate = DATEADD(day, -30, GETUTCDATE())
   WHERE [current] = 0
     AND nodeId IN (
       SELECT c.nodeId FROM umbracoContent c
       INNER JOIN cmsContentType ct ON c.contentTypeId = ct.nodeId
       INNER JOIN umbracoNode n ON ct.nodeId = n.id
       WHERE n.uniqueId = '<document-type-guid>'
     )
   ```
3. Set a low cap in `appsettings.json`:
   ```json
   {
     "Umbraco": {
       "CMS": {
         "Content": {
           "ContentVersionCleanupPolicy": {
             "EnableCleanup": true,
             "KeepAllVersionsNewerThanDays": 0,
             "KeepLatestVersionPerDayForDays": 0,
             "MaxVersionsToDeletePerRun": 5
           }
         }
       }
     }
   }
   ```
4. Wait for the cleanup job to run.
5. Check the logs for **both** messages:
   ```
   Deleted 5 ContentVersion(s)
   Reached per-run cap of 5. Remaining versions will be cleaned up in subsequent runs
   ```
6. Verify exactly 5 versions were removed:
   ```sql
   SELECT count(*)
   FROM umbracoContentVersion cv
   INNER JOIN umbracoContent c ON cv.nodeId = c.nodeId
   INNER JOIN cmsContentType ct ON c.contentTypeId = ct.nodeId
   INNER JOIN umbracoNode n ON ct.nodeId = n.id
   WHERE n.uniqueId = '<document-type-guid>'
   ```
7. Wait for the next run (or restart). Verify another batch is deleted.
8. Repeat until all historic versions are gone. Final run should log fewer than 5 deleted and **no** cap-reached message.

#### Test 4: Content type override with PreventCleanup

**Goal**: Verify per-content-type overrides are respected.

1. Create two document types: "Cleanable Page" and "Protected Page".
2. In the backoffice under each document type's settings, set history cleanup:
   - "Cleanable Page": PreventCleanup = false, KeepAllVersionsNewerThanDays = 0, KeepLatestVersionPerDayForDays = 0
   - "Protected Page": PreventCleanup = true
3. Create content of each type and publish several times.
4. Backdate all versions to 30 days ago (same SQL as Test 1).
5. Wait for cleanup to run.
6. Verify:
   ```sql
   -- Should have only 2 remaining (draft + published)
   SELECT COUNT(*)
   FROM umbracoContentVersion cv
   INNER JOIN umbracoContent c ON cv.nodeId = c.nodeId
   WHERE c.contentTypeId = <cleanable-document-type-guid>

   -- Should have all versions preserved
   SELECT COUNT(*)
   FROM umbracoContentVersion cv
   INNER JOIN umbracoContent c ON cv.nodeId = c.nodeId
   WHERE c.contentTypeId = <protected-document-type-guid>
   ```

#### Test 5: Pinned versions are preserved

**Goal**: Verify that versions marked with "prevent cleanup" (pinned) are never deleted.

1. Create a content node, publish 5+ times.
2. In the backoffice, go to the content's version history (Info tab → Rollback) and pin one of the historic versions.
3. Backdate all versions and enable aggressive cleanup (KeepAllVersionsNewerThanDays = 0, KeepLatestVersionPerDayForDays = 0).
4. Wait for cleanup to run.
5. Verify the pinned version still exists:
   ```sql
   SELECT id, preventCleanup FROM umbracoContentVersion WHERE preventCleanup = 1
   ```

#### Test 6: Cleanup disabled

**Goal**: Verify the job does nothing when disabled.

1. Set `EnableCleanup = false` in `appsettings.json`.
2. Wait for the job to run.
3. Check logs for:
   ```
   ContentVersionCleanup task will not run as it has been globally disabled via configuration
   ```
4. Verify no versions were deleted.

## Documentation

The configuration setting `MaxVersionsToDeletePerRun` should be documented.

### CODE REVIEW

File: src/Umbraco.Infrastructure/BackgroundJobs/Jobs/DistributedJobs/ContentVersionCleanupJob.cs [hunk 1]
```diff
@@ -14,7 +14,7 @@ internal class ContentVersionCleanupJob : IDistributedBackgroundJob
     public string Name => "ContentVersionCleanupJob";
 
     /// <inheritdoc />
-    public TimeSpan Period { get => TimeSpan.FromHours(1); }
+    public TimeSpan Period { get => TimeSpan.FromMinutes(1); }
```
Comment (kjac) [inline src/Umbraco.Infrastructure/BackgroundJobs/Jobs/DistributedJobs/ContentVersionCleanupJob.cs]: Is this an intentional change, or a remnant of manual testing?

File: src/Umbraco.Infrastructure/Persistence/Repositories/Implement/DocumentVersionRepository.cs [hunk 2]
```diff
@@ -53,6 +59,20 @@ public IReadOnlyCollection<ContentVersionMeta> GetDocumentVersionsEligibleForCle
             .Where<ContentVersionDto>(x => !x.PreventCleanup) // Never delete "pinned" versions
             .Where<DocumentVersionDto>(x => !x.Published); // Never delete published version
 
+        if (olderThan.HasValue)
+        {
+            query = query.Where<ContentVersionDto>(x => x.VersionDate < olderThan.Value);
```
Comment (kjac) [inline src/Umbraco.Infrastructure/Persistence/Repositories/Implement/DocumentVersionRepository.cs:64]: Should we consider a table index for the `versionDate` column to support this query and the subsequent order-by?

File: src/Umbraco.Infrastructure/Persistence/Repositories/Implement/DocumentVersionRepository.cs [hunk 3]
```diff
@@ -141,34 +164,40 @@ public void DeleteVersions(IEnumerable<int> versionIds)
...
+                    batch.Cast<object>().ToArray());
+            }
+
+            // Delete from all related tables using a subquery against the temp table.
+            db.Execute($"DELETE FROM {PropertyDataDto.TableName} WHERE versionId IN (SELECT Id FROM {tempTableName})");
+            db.Execute($"DELETE FROM {ContentVersionCultureVariationDto.TableName} WHERE versionId IN (SELECT Id FROM {tempTableName})");
+            db.Execute($"DELETE FROM {DocumentVersionDto.TableName} WHERE id IN (SELECT Id FROM {tempTableName})");
+            db.Execute($"DELETE FROM {ContentVersionDto.TableName} WHERE id IN (SELECT Id FROM {tempTableName})");
+        }
+        finally
```
Comment (kjac) [inline src/Umbraco.Infrastructure/Persistence/Repositories/Implement/DocumentVersionRepository.cs:198]: Maybe worth adding a `catch` here to log exception details and then rethrow the exception?

File: src/Umbraco.Infrastructure/Persistence/SqlSyntax/ISqlSyntaxProvider.cs [hunk 4]
```diff
@@ -578,4 +578,28 @@ Sql<ISqlContext>.SqlJoinClause<ISqlContext> LeftJoinWithNestedJoin<TDto>(
...
     /// <returns>truncated name.</returns>
     string TruncateConstraintName<T>(string constraintName) => constraintName;
+
+    /// <summary>
+    /// Gets the SQL to create a temporary table with the given name and column definitions.
+    /// </summary>
+    /// <param name="tableName">The base name for the temporary table (without any provider-specific prefix).</param>
+    /// <param name="columnDefinitionSql">The SQL column definitions (e.g., "Id INT NOT NULL PRIMARY KEY").</param>
+    /// <returns>A SQL statement that creates the temporary table.</returns>
+    string CreateTempTable(string tableName, string columnDefinitionSql)
```
Comment (kjac) [inline src/Umbraco.Infrastructure/Persistence/SqlSyntax/ISqlSyntaxProvider.cs:589]:
```suggestion
    // TODO (V19): Remove default implementation.
    string CreateTempTable(string tableName, string columnDefinitionSql)
```

File: src/Umbraco.Infrastructure/Persistence/SqlSyntax/ISqlSyntaxProvider.cs [hunk 5]
```diff
@@ -578,4 +578,28 @@ Sql<ISqlContext>.SqlJoinClause<ISqlContext> LeftJoinWithNestedJoin<TDto>(
...
+        => $"CREATE TEMP TABLE {tableName} ({columnDefinitionSql})";
+
+    /// <summary>
+    /// Gets the properly qualified name for a temporary table, applying any provider-specific prefix.
+    /// </summary>
+    /// <param name="baseName">The base name for the temporary table.</param>
+    /// <returns>The qualified temporary table name.</returns>
+    string TempTableName(string baseName) => baseName;
```
Comment (kjac) [inline src/Umbraco.Infrastructure/Persistence/SqlSyntax/ISqlSyntaxProvider.cs:598]:
```suggestion
    // TODO (V19): Remove default implementation.
    string TempTableName(string baseName) => baseName;
```

File: src/Umbraco.Infrastructure/Persistence/SqlSyntax/ISqlSyntaxProvider.cs [hunk 6]
```diff
@@ -578,4 +578,28 @@ Sql<ISqlContext>.SqlJoinClause<ISqlContext> LeftJoinWithNestedJoin<TDto>(
...
+
+    /// <summary>
+    /// Gets the SQL to drop a temporary table if it exists.
+    /// </summary>
+    /// <param name="tableName">The base name for the temporary table (without any provider-specific prefix).</param>
+    /// <returns>A SQL statement that drops the temporary table if it exists.</returns>
+    string DropTempTable(string tableName)
```
Comment (kjac) [inline src/Umbraco.Infrastructure/Persistence/SqlSyntax/ISqlSyntaxProvider.cs:606]:
```suggestion
    // TODO (V19): Remove default implementation.
    string DropTempTable(string tableName)
```

File: src/Umbraco.Infrastructure/BackgroundJobs/Jobs/DistributedJobs/ContentVersionCleanupJob.cs (hunk 1 above)
Comment (AndyButland) [reply src/Umbraco.Infrastructure/BackgroundJobs/Jobs/DistributedJobs/ContentVersionCleanupJob.cs]: No - as you guessed, just from testing.  Thanks for catching - that slipping through would have rather negated some of the effort here!

File: src/Umbraco.Infrastructure/Persistence/Repositories/Implement/DocumentVersionRepository.cs (hunk 2 above)
Comment (AndyButland) [reply src/Umbraco.Infrastructure/Persistence/Repositories/Implement/DocumentVersionRepository.cs:64]: Yes, very good idea. Now we are filtering and sorting on this column, we should have an index on it.  I've added one for new installs and a migration for upgrades.

File: src/Umbraco.Infrastructure/Persistence/Repositories/Implement/DocumentVersionRepository.cs (hunk 3 above)
Comment (AndyButland) [reply src/Umbraco.Infrastructure/Persistence/Repositories/Implement/DocumentVersionRepository.cs:198]: I don't think we need this.  Any exception would bubble up still (finally doesn't swallow it), so a catch, log and re-throw would only duplicate the log entry.

I've checked this, and throwing an exception in the `try` part of this does bubble up so I see this in the log:

```
[08:37:18 ERR] An exception occurred while running distributed background job 'ContentVersionCleanupJob'.
System.ApplicationException: My test exception
   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.DocumentVersionRepository.DeleteVersions(IEnumerable`1 versionIds) in ...
```

**Comment by kjac** [comment]
Two more test cases worth running (I have verified both):

#### Test 7: Content type override of KeepAllVersionsNewerThanDays

**Goal:** Verify per-content-type overrides are respected.

Configure cleanup in `appsettings.json` with `"KeepAllVersionsNewerThanDays": 10` and `"KeepLatestVersionPerDayForDays": 0`.

1. Set "Keep all versions newer than days" to 50 on the test content type.
2. Create some content versions and backdate them 30 days (SQL from Test 1).
3. Verify that none of the backdated content versions are cleaned up (use verification SQL from Test 1).
4. Revert (remove) the "Keep all versions newer than days" configuration.
5. Verify that the backdated content versions are cleaned up.

#### Test 8: Content type override of KeepAllVersionsNewerThanDays

**Goal:** Verify per-content-type overrides are respected.

Configure cleanup in `appsettings.json` with `"KeepAllVersionsNewerThanDays": 10` and `"KeepLatestVersionPerDayForDays": 0`.

1. Set "Keep latest version per day for days" to 50 on the test content type.
2. Create some content versions and backdate some of them 20 days, some 30 days (SQL from Test 2).
3. Verify that one content version from each backdated date is retained after clean-up (use verification SQL from Test 2).
4. Revert (remove) the "Keep latest version per day for days" configuration.
5. Verify that the remaining backdated content versions are cleaned up.
6. Verify that the content versions that were _not_ backdated remain throughout the test.

File: src/Umbraco.Infrastructure/Persistence/Repositories/Implement/DocumentVersionRepository.cs (hunk 2 above)
Comment (AndyButland) [reply src/Umbraco.Infrastructure/Persistence/Repositories/Implement/DocumentVersionRepository.cs:64]: In testing I see this is added for a table with 140,000 rows in 100ms.  Nonetheless I'll ensure this is a migration that extends the command timeout like we've done for some others that could take some time to run.

**Comment by kjac** [comment]
**Test 2** yields a slight weirdness.

I ran the test with `KeepAllVersionsNewerThanDays` configured to 10. After the initial clean-up I had these versions (as expected):

image

I then reconfigured `KeepAllVersionsNewerThanDays` configured to 0. After the next clean-up, I had these versions:

image

Notice the "extra" version for `2026-03-25` (ID 44). I would have expected that to be removed. 

 I then configured `KeepLatestVersionPerDayForDays` to 0, which caused the version to be cleaned up:

image

**Comment by kjac** [comment]
Whoa. Not sure why I closed this one. That was not intentional 🙈

**Comment by AndyButland** [comment]
I've repeated "Test 2" and am seeing the expected results.

Before:

```
id	nodeId	versionDate	            current
-------------------------------------------
204	1207	2026-02-13 10:51:32.550	0
205	1207	2026-02-13 10:51:32.550	0
206	1207	2026-02-13 10:51:32.550	0
201	1207	2026-03-05 10:51:29.207	0
202	1207	2026-03-05 10:51:29.207	0
203	1207	2026-03-05 10:51:29.207	0
207	1207	2026-03-25 10:48:59.523	0
208	1207	2026-03-25 10:49:00.213	0
209	1207	2026-03-25 10:49:00.797	0
210	1207	2026-03-25 10:49:01.353	0
211	1207	2026-03-25 10:49:01.723	0
212	1207	2026-03-25 10:49:01.723	1
```

After:
```
id	nodeId	versionDate	            current
-------------------------------------------
206	1207	2026-02-13 10:51:32.550	0
203	1207	2026-03-05 10:51:29.207	0
210	1207	2026-03-25 10:49:01.353	0
211	1207	2026-03-25 10:49:01.723	0
212	1207	2026-03-25 10:49:01.723	1
```

Feb 13 - 3 versions, kept only 206 (the most recent for the day)
Mar 5 - 3 versions, kept only 203 (the most recent for the day)
Mar 25 - 5 versions, kept only 210 (newest historic for today) + 211 (current published) + 212 (current draft)

So this seems OK.

Wondering maybe in your test @kjac you still had a content type override (e.g. from your test 7 and 8)?

**Comment by kjac** [comment]
> Mar 25 - 5 versions, kept only 210 (newest historic for today) + 211 (current published) + 212 (current draft)

ID 210 in your test results is the same as ID 44 in mine. We're seeing the same thing. If it's expected, all is good 😄

**Comment by AndyButland** [comment]
Docs PR is here: https://github.com/umbraco/UmbracoDocs/pull/7923

**Comment by nielslyngsoe** [comment]
Review by our Work-In-Progress Claude Skill:

## PR Review

**Target:** `origin/main` · **Based on commit:** `a755617f99bfbed3fac9e147a0e93523689543dc` · **Files:** 16 changed, 0 skipped, 16 reviewed (4 full, 12 diff + header-only)

Optimizes the content version cleanup job for large datasets by adding SQL-level date filtering and a per-run cap (`MaxVersionsToDeletePerRun`), replacing batched `WHERE IN` deletes with a temp-table-based bulk delete, and adding a database index on `umbracoContentVersion.versionDate`.

- **Modified public API:** `IDocumentVersionRepository.GetDocumentVersionsEligibleForCleanup` (new overload with `olderThan` and `maxCount` parameters; original marked obsolete), `ISqlSyntaxProvider` (new default interface methods: `CreateTempTable`, `TempTableName`, `DropTempTable`), `SqlSyntaxProviderBase` (new virtual methods for temp table operations), `ContentVersionCleanupPolicySettings` (new `MaxVersionsToDeletePerRun` property)
- **Affected implementations (outside this PR):** Any third-party `ISqlSyntaxProvider` implementations gain the new temp table methods via default interface implementation. Any third-party `IDocumentVersionRepository` implementations gain the new overload via default interface implementation that delegates to the obsolete method.
- **Other changes:** New configuration option `Umbraco:CMS:Content:ContentVersionCleanupPolicy:MaxVersionsToDeletePerRun` (default 50,000) allows controlling how many versions are deleted per cleanup run. A value of 0 means no limit. A new database migration adds an index on `umbracoContentVersion.versionDate`. Log message casing normalized to structured logging conventions (`{Count}` instead of `{count}`).

---

### Critical

- **`src/Umbraco.Infrastructure/Persistence/Repositories/Implement/DocumentVersionRepository.cs:170-191`**: SQL injection risk in temp table batch insert. The `placeholders` string is built by interpolating index values (`$"(@{i})"`), which is safe since `i` is an integer loop counter. However, the `tableName` in `$"INSERT INTO {tempTableName}"` and the DELETE statements (`$"DELETE FROM {PropertyDataDto.TableName} WHERE versionId IN (SELECT Id FROM {tempTableName})"`) use string interpolation with table name constants, not parameterized queries. While `tempTableName` comes from `ISqlSyntaxProvider` (trusted code) and `PropertyDataDto.TableName` etc. are compile-time constants, this pattern bypasses NPoco's parameterized query builder (`Sql<ISqlContext>`). This is acceptable here since all interpolated values are from trusted internal sources (not user input), but it breaks the project's established convention of using `Sql<ISqlContext>` for all database queries.

  This is flagged as critical because the CLAUDE.md for Infrastructure explicitly states: "Never concatenate SQL strings. All queries via `Sql<ISqlContext>` builder." While the actual risk is low (all values are internal constants), future maintainers might copy this pattern with less safe inputs. Consider adding a code comment explaining why raw SQL is necessary here (NPoco's query builder does not support temp table operations) to prevent misuse of this pattern.

### Important

- **`src/Umbraco.Infrastructure/Persistence/Repositories/Implement/DocumentVersionRepository.cs:164-198`**: The `DeleteVersions` method materializes all version IDs into a `List<int>` (`versionIds.ToList()`) before processing. For very large cleanup operations (e.g., first run on a site with hundreds of thousands of historic versions), this could cause significant memory pressure. The previous implementation streamed through `InGroupsOf` without materializing the full list. Consider whether the enumerable could be consumed lazily, though note the temp table approach does require all IDs upfront, so this is a trade-off for the performance gains of bulk delete.

- **`src/Umbraco.Cms.Persistence.Sqlite/Services/SqliteSyntaxProvider.cs`**: The SQLite provider overrides `CreateTempTable` but does NOT override `TempTableName` or `DropTempTable`. The base class defaults return the bare name without prefix, and `DropTempTable` returns `DROP TABLE IF EXISTS {tableName}`. This works correctly because SQLite temp tables use the same namespace as regular tables and do not require a `#` prefix. However, the asymmetry between SQL Server (which overrides all three) and SQLite (which only overrides one) is worth a comment for clarity, since it is non-obvious to a reader why SQLite only needs to override `CreateTempTable`.

- **`src/Umbraco.Core/Services/ContentVersionService.cs:232-241`**: The `effectiveKeepAllDays` calculation opens a separate scope to call `GetCleanupPolicies()`, then iterates overrides to find the minimum `KeepAllVersionsNewerThanDays`. This query runs every cleanup cycle. Since `GetCleanupPolicies()` is also called inside `DefaultContentVersionCleanupPolicy.Apply()` (which is invoked later in the same method), the same data is fetched twice per cleanup run. This is a minor performance concern but worth noting -- the policies could be fetched once and shared.

- **`src/Umbraco.Infrastructure/Persistence/SqlSyntax/ISqlSyntaxProvider.cs:537-555`**: The TODO comments say `// TODO (V19): Remove default implementation.` which is correct for the removal version (current 17 + 2 = 19). However, the default implementations are not marked with `[Obsolete]` -- they are default interface implementations for backward compatibility, which is the correct Pattern 3 from the breaking changes policy. This is fine, but note that the `CreateTempTable` default uses `CREATE TEMP TABLE` syntax which is SQLite-specific. SQL Server does not support `CREATE TEMP TABLE` -- it uses `CREATE TABLE #name`. If a third-party provider inherits from neither `SqlSyntaxProviderBase` nor `SqlServerSyntaxProvider` and uses SQL Server semantics, the default would produce invalid SQL. The fallback is reasonable as a "best guess" default, but a `NotSupportedException` could be considered instead if there is concern about silent failure.

### Suggestions

- **`src/Umbraco.Core/Configuration/Models/ContentVersionCleanupPolicySettings.cs:38`**: The default value of `MaxVersionsToDeletePerRun` is `50_000`. The XML doc says "A value of 0 means no limit (process all eligible versions)." Consider whether negative values should be handled (e.g., treated as 0/no limit, or validated). The property is a plain `int` with no validation, so a negative config value would result in `fetchLimit` being `null` (because the check is `> 0`), effectively meaning no limit. This implicit behavior should be documented or explicitly validated.

- **`src/Umbraco.Infrastructure/Migrations/Upgrade/V_17_4_0/AddContentVersionDateIndex.cs:37-38`**: The migration creates the index using raw SQL with square-bracket escaping (`[{IndexName}]` and `[{ContentVersionDto.TableName}]`). Square brackets are SQL Server syntax for identifier quoting. SQLite also supports them, so this is portable. However, the comment on line 33 says "CREATE INDEX (without NONCLUSTERED) is portable" -- worth noting that the square brackets are also portable across both supported databases.

- **`src/Umbraco.Infrastructure/Persistence/Dtos/ContentVersionDto.cs:48`**: The `[Index]` attribute on the DTO is good for documentation, but the actual index creation happens in the migration (`AddContentVersionDateIndex`). If the NPoco schema creator also reads this attribute and tries to create the index on a fresh install, there could be a duplicate index attempt. Verify that the `IndexExists` check in the migration and the schema creator handle this gracefully.

- **`src/Umbraco.Core/Services/ContentVersionService.cs:329-334`**: The "Reached per-run cap" log message uses `LogInformation` level, which is appropriate for operational visibility. However, the `fetchWasCapped` flag is set based on `allHistoricVersions.Count >= fetchLimit.Value`, which could produce a false positive if the exact number of eligible versions happens to equal the cap (fetched exactly `maxCount` but there are no more). This is a minor cosmetic issue -- the message says "Remaining versions will be cleaned up in subsequent runs" which is harmlessly imprecise when no more remain.

---

## Approved with Suggestions for improvement

Good to go, but please carefully consider the importance of the suggestions. The PR is well-structured with proper obsolete patterns, default interface implementations, good test coverage (new unit tests for the cutoff logic and integration tests for the per-run cap), and a clean migration. The main area to watch is the raw SQL usage in `DeleteVersions` -- while safe in this context, it departs from the project's established NPoco query builder convention.
