### PR TITLE
Repositories: Introduce and use NPoco and custom extension methods for SQL syntax in ContentTypeRepositoryBase

### LINKED ISSUE #19985: SqlSyntax fix for ContentTypeRepositoryBase
### Which Umbraco version are you using?

v17/dev

### Bug summary

This is another sub task for issue #19897 and replaces raw SQL queries by type syntax methods.
I have also added one unit test to check MS SQL Server syntax. 
For SQLite was already an integration test.

### Specifics

_No response_

### Steps to reproduce

This is covered by unit- and integration tests.

### Expected result / actual result

_No response_

### PR DESCRIPTION
**Pull request by idseefeld**
Raw SQL queries are replaced by typed extension methods in class: `Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.ContentTypeRepositoryBase`

### Prerequisites

- [ x] I have added steps to test this contribution in the description below

This PR fixes #19985 which is a sub task for issue #19897.

### CODE REVIEW

**Comment by idseefeld** [comment]
The failing CodeScene issues are either not handled in this PR or in case of `SqlSyntaxProviderBase` it is not possible to avoid the heavy use of strings (or at least I have no idea how).

File: src/Umbraco.Infrastructure/Persistence/NPocoSqlExtensions.cs [hunk 1]
```diff
@@ -3,6 +3,7 @@
 using System.Reflection;
 using System.Text;
 using System.Text.RegularExpressions;
+using Newtonsoft.Json.Linq;
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/NPocoSqlExtensions.cs]: This shouldn't be being used.  If it's just your IDE being "helpful" and adding, please can you remove?  If it's needed, we'd need to look at a System.Text.Json alternative.

File: src/Umbraco.Infrastructure/Persistence/NPocoSqlExtensions.cs [hunk 2]
```diff
@@ -113,10 +119,12 @@ public static Sql<ISqlContext> WhereIn<TDto>(this Sql<ISqlContext> sql, Expressi
...
 
 
-        public static Sql<ISqlContext> WhereLike<TDto>(this Sql<ISqlContext> sql, Expression<Func<TDto, object?>> fieldSelector, Sql<ISqlContext>? valuesSql)
+        public static Sql<ISqlContext> WhereLike<TDto>(this Sql<ISqlContext> sql, Expression<Func<TDto, object?>> fieldSelector, Sql<ISqlContext>? valuesSql, string concatDefault = "")
         {
             var fieldName = sql.SqlContext.SqlSyntax.GetFieldName(fieldSelector);
-            sql.Where(fieldName + " LIKE (" + valuesSql?.SQL + ")", valuesSql?.Arguments);
+            var concat = sql.SqlContext.SqlSyntax.GetWildcardConcat(concatDefault);
+            var likeSelect = sql.SqlContext.SqlSyntax.GetConcat(valuesSql?.SQL ?? string.Empty, concat);
+            _ = sql.Where($"{fieldName} LIKE {likeSelect}", valuesSql?.Arguments);
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/NPocoSqlExtensions.cs]:
```suggestion
            sql.Where($"{fieldName} LIKE {likeSelect}", valuesSql?.Arguments);
```

File: src/Umbraco.Infrastructure/Persistence/NPocoSqlExtensions.cs [hunk 3]
```diff
@@ -149,7 +157,7 @@ public static Sql<ISqlContext> WhereLike<TDto>(this Sql<ISqlContext> sql, Expres
         public static Sql<ISqlContext> WhereNotIn<TDto>(this Sql<ISqlContext> sql, Expression<Func<TDto, object?>> field, IEnumerable values)
         {
             var fieldName = sql.SqlContext.SqlSyntax.GetFieldName(field);
-            sql.Where(fieldName + " NOT IN (@values)", new { values });
+            _ = sql.Where(fieldName + " NOT IN (@values)", new { values });
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/NPocoSqlExtensions.cs]:
```suggestion
            sql.Where(fieldName + " NOT IN (@values)", new { values });
```

File: src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs [hunk 4]
```diff
@@ -181,36 +182,43 @@ protected void PersistNewBaseContentType(IContentTypeComposition entity)
...
-        var level = parent.Level + 1;
-        var sortOrder =
-            Database.ExecuteScalar<int>(
-                "SELECT COUNT(*) FROM umbracoNode WHERE parentID = @ParentId AND nodeObjectType = @NodeObjectType",
-                new { entity.ParentId, NodeObjectType = NodeObjectTypeId });
+        sql = Sql()
+            .SelectAll()
+            .From<NodeDto>()
+            .Where<NodeDto>(x => x.NodeId == entity.ParentId);
+        NodeDto? parent = Database.Fetch<NodeDto>(sql.SelectTop(1)).FirstOrDefault();
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs]: Can we call `FirstOrDefault` here rather than retrieving a collection and taking the first one?

File: src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs [hunk 5]
```diff
@@ -181,36 +182,43 @@ protected void PersistNewBaseContentType(IContentTypeComposition entity)
...
+        sql = Sql()
+            .SelectCount()
+            .From<NodeDto>()
+            .Where<NodeDto>(x => x.ParentId == entity.ParentId && x.NodeObjectType == NodeObjectTypeId);
+        var sortOrder = Database.ExecuteScalar<int>(sql);
 
         // Create the (base) node data - umbracoNode
         NodeDto nodeDto = dto.NodeDto;
-        nodeDto.Path = parent.Path;
+        nodeDto.Path = parent?.Path ?? "-1";
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs]:
```suggestion
        nodeDto.Path = parent?.Path ?? Constants.System.RootString;
```

Might need a using statement.

File: src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs [hunk 6]
```diff
@@ -238,10 +246,11 @@ protected void PersistNewBaseContentType(IContentTypeComposition entity)
...
                 // Fallback for ContentTypes with no identity
-                ContentTypeDto? contentTypeDto =
-                    Database.FirstOrDefault<ContentTypeDto>(
-                        "WHERE alias = @Alias",
-                        new { composition.Alias });
+                sql = Sql()
+                    .SelectAll()
+                    .From<ContentTypeDto>()
+                    .Where<ContentTypeDto>(x => x.Alias == composition.Alias);
+                ContentTypeDto? contentTypeDto = Database.Fetch<ContentTypeDto>(sql.SelectTop(1)).FirstOrDefault();
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs]: Again, see if can use `FirstOrDefault` over `Fetch`

File: src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs [hunk 7]
```diff
@@ -269,7 +278,8 @@ protected void PersistNewBaseContentType(IContentTypeComposition entity)
         }
 
         // Insert Tabs
-        foreach (PropertyGroup propertyGroup in entity.PropertyGroups)
+        PropertyGroupCollection propertyGroups = entity.PropertyGroups ?? [];
+        foreach (PropertyGroup propertyGroup in propertyGroups)
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs]: Not sure if this is needed as it doesn't look like `entity.PropertyGroups` can be null.

File: src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs [hunk 8]
```diff
@@ -291,7 +301,8 @@ protected void PersistNewBaseContentType(IContentTypeComposition entity)
         }
 
         // Insert PropertyTypes
-        foreach (IPropertyType propertyType in entity.PropertyTypes)
+        IEnumerable<IPropertyType> propertyTypes = entity.PropertyTypes ?? [];
+        foreach (IPropertyType propertyType in propertyTypes)
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs]: Not sure if this is needed as it doesn't look like `entity.PropertyTypes` can be null.

File: src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs [hunk 9]
```diff
@@ -307,10 +318,17 @@ protected void PersistNewBaseContentType(IContentTypeComposition entity)
...
             // Update the current PropertyType with correct PropertyEditorAlias and DatabaseType
+            sql = Sql()
+                .SelectAll()
+                .From<DataTypeDto>()
+                .Where<DataTypeDto>(x => x.NodeId == propertyType.DataTypeId);
             DataTypeDto? dataTypeDto =
-                Database.FirstOrDefault<DataTypeDto>("WHERE nodeId = @Id", new { Id = propertyTypeDto.DataTypeId });
-            propertyType.PropertyEditorAlias = dataTypeDto.EditorAlias;
-            propertyType.ValueStorageType = dataTypeDto.DbType.EnumParse<ValueStorageType>(true);
+                Database.Fetch<DataTypeDto>(sql.SelectTop(1)).FirstOrDefault();
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs]: Again, see if can retain use of `FirstOrDefaullt`.

File: src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs [hunk 10]
```diff
@@ -307,10 +318,17 @@ protected void PersistNewBaseContentType(IContentTypeComposition entity)
...
+            if (dataTypeDto != null)
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs]:
```suggestion
            if (dataTypeDto is not null)
```

File: src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs [hunk 11]
```diff
@@ -344,15 +364,22 @@ protected void PersistUpdatedBaseContentType(IContentTypeComposition entity)
         // we NEED this: updating, so the .PrimaryKey already exists, but the entity does
         // not carry it and therefore the dto does not have it yet - must get it from db,
         // look up ContentType entry to get PrimaryKey for updating the DTO
-        ContentTypeDto? dtoPk = Database.First<ContentTypeDto>("WHERE nodeId = @Id", new { entity.Id });
+        sql = Sql()
+            .SelectAll()
+            .From<ContentTypeDto>()
+            .Where<ContentTypeDto>(x => x.NodeId == dto.NodeId);
+        ContentTypeDto? dtoPk = Database.Fetch<ContentTypeDto>(sql.SelectTop(1)).First();
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs]: See if can use `First`.

File: src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs [hunk 12]
```diff
@@ -344,15 +364,22 @@ protected void PersistUpdatedBaseContentType(IContentTypeComposition entity)
...
         // handle (delete then recreate) compositions
-        Database.Delete<ContentType2ContentTypeDto>("WHERE childContentTypeId = @Id", new { entity.Id });
+        sql = Sql()
+            .Delete<ContentType2ContentTypeDto>()
+            .Where<ContentType2ContentTypeDto>(x => x.ChildId == entity.Id);
+        _ = Database.Execute(sql);
         foreach (IContentTypeComposition composition in entity.ContentTypeComposition)
         {
-            Database.Insert(new ContentType2ContentTypeDto { ParentId = composition.Id, ChildId = entity.Id });
+            _ = Database.Insert(new ContentType2ContentTypeDto { ParentId = composition.Id, ChildId = entity.Id });
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs]:
```suggestion
            Database.Insert(new ContentType2ContentTypeDto { ParentId = composition.Id, ChildId = entity.Id });
```

File: src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs [hunk 13]
```diff
@@ -181,36 +182,43 @@ protected void PersistNewBaseContentType(IContentTypeComposition entity)
         ContentTypeDto dto = ContentTypeFactory.BuildContentTypeDto(entity);
 
         // Cannot add a duplicate content type
-        var exists = Database.ExecuteScalar<int>(
-            @"SELECT COUNT(*) FROM cmsContentType
-INNER JOIN umbracoNode ON cmsContentType.nodeId = umbracoNode.id
-WHERE cmsContentType." + SqlSyntax.GetQuotedColumnName("alias") + @"= @alias
-AND umbracoNode.nodeObjectType = @objectType",
-            new { alias = entity.Alias, objectType = NodeObjectTypeId });
+        Sql<ISqlContext> sql = Sql()
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs]: This `sql` variable gets reused a lot in this method.  I think it would be safer to create individual ones for each statement, so this one becomes `contentTypeByAliasSql` or similar, and so on throughout the method.

Just avoids unexpected bugs where a variable is updated that's already set etc.

File: src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs [hunk 14]
```diff
@@ -399,16 +430,20 @@ protected void PersistUpdatedBaseContentType(IContentTypeComposition entity)
                             .Where<PropertyTypeDto>(x => x.Id == propertyTypeId);
 
                         // finally delete the properties that match our criteria for removing a ContentType from the composition
-                        Database.Delete<PropertyDataDto>(new Sql(
-                            "WHERE id IN (" + propertySql.SQL + ")",
-                            propertySql.Arguments));
+                        sql = Sql()
+                            .Delete<PropertyDataDto>()
+                            .WhereIn<PropertyDataDto>(x => x.Id, propertySql.Arguments);
+                        _ = Database.Execute(sql);
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs]:
```suggestion
                        Database.Execute(sql);
```

File: src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs [hunk 15]
```diff
@@ -399,16 +430,20 @@ protected void PersistUpdatedBaseContentType(IContentTypeComposition entity)
...
                 }
             }
         }
 
         // delete the allowed content type entries before re-inserting the collection of allowed content types
-        Database.Delete<ContentTypeAllowedContentTypeDto>("WHERE Id = @Id", new { entity.Id });
+        sql = Sql()
+            .Delete<ContentTypeAllowedContentTypeDto>()
+            .Where<ContentTypeAllowedContentTypeDto>(x => x.Id == entity.Id);
+        _ = Database.Execute(sql);
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs]:
```suggestion
        Database.Execute(sql);
```

File: src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs [hunk 16]
```diff
@@ -481,16 +521,21 @@ protected void PersistUpdatedBaseContentType(IContentTypeComposition entity)
...
-                    new { ids = groupsToDelete });
+                sql = Sql()
+                    .Select<PropertyTypeDto>(x => x.Id)
+                    .From<PropertyTypeDto>()
+                    .WhereIn<PropertyTypeDto>(x => x.PropertyTypeGroupId, groupsToDelete);
+                orphanPropertyTypeIds = Database.Fetch<int>(sql);
+                sql = Sql()
+                    .Update<PropertyTypeDto>(u => u.Set(x => x.PropertyTypeGroupId, null))
+                    .WhereIn<PropertyTypeDto>(x => x.PropertyTypeGroupId, groupsToDelete);
+                _ = Database.Execute(sql);
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs]:
```suggestion
                Database.Execute(sql);
```

File: src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs [hunk 17]
```diff
@@ -823,7 +868,7 @@ private void Clear301Redirects(IContentTypeComposition contentType)
                 (Expression<Func<RedirectUrlDto, object?>>)(x => x.ContentKey),
                 sqlSelect);
 
-        Database.Execute(sqlDelete);
+        _ = Database.Execute(sqlDelete);
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs]:
```suggestion
        Database.Execute(sqlDelete);
```

File: src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs [hunk 18]
```diff
@@ -1196,9 +1241,9 @@ private void CopyPropertyData(int? sourceLanguageId, int? targetLanguageId,
                 .WhereIn<ContentDto>(x => x.ContentTypeId, contentTypeIds);
         }
 
-        Sql<ISqlContext>? sqlInsert = Sql($"INSERT INTO {PropertyDataDto.TableName} ({cols})").Append(sqlSelectData);
+        Sql<ISqlContext>? sqlInsert = Sql($"INSERT INTO {SqlSyntax.GetQuotedTableName(PropertyDataDto.TableName)} ({cols})").Append(sqlSelectData);
 
-        Database.Execute(sqlInsert);
+        _ = Database.Execute(sqlInsert);
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs]:
```suggestion
        Database.Execute(sqlInsert);
```

File: src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs [hunk 19]
```diff
@@ -1216,7 +1261,7 @@ private void CopyPropertyData(int? sourceLanguageId, int? targetLanguageId,
                 .Where<PropertyDataDto>(x => x.LanguageId == null)
                 .WhereIn<PropertyDataDto>(x => x.PropertyTypeId, propertyTypeIds);
 
-            Database.Execute(sqlDelete);
+            _ = Database.Execute(sqlDelete);
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs]:
```suggestion
            Database.Execute(sqlDelete);
```

File: src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs [hunk 20]
```diff
@@ -1412,25 +1457,35 @@ private void RenormalizeDocumentEditedFlags(
...
-            "'|%'");
-
-        Database.Delete<UserGroup2GranularPermissionDto>(
-            "WHERE uniqueId = @ContentTypeKey AND permission LIKE " + permissionSearchString,
-            new { ContentTypeKey = contentType.Key, PropertyTypeId = propertyTypeId });
+        // first clear dependencies
+        Sql<ISqlContext> sql = Sql()
+            .Delete<TagRelationshipDto>()
+            .Where<TagRelationshipDto>(x => x.PropertyTypeId == propertyTypeId);
+        _ = Database.Execute(sql);
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs]:
```suggestion
        Database.Execute(sql);
```

File: src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs [hunk 21]
```diff
@@ -1412,25 +1457,35 @@ private void RenormalizeDocumentEditedFlags(
...
-        var uniqueIdAsString = string.Format(SqlContext.SqlSyntax.ConvertUniqueIdentifierToString, "uniqueId");
-        var permissionSearchString = SqlContext.SqlSyntax.GetConcat(
-            "(SELECT " + uniqueIdAsString + " FROM " + Constants.DatabaseSchema.Tables.PropertyType + " WHERE id = @PropertyTypeId)",
-            "'|%'");
-
-        Database.Delete<UserGroup2GranularPermissionDto>(
-            "WHERE uniqueId = @ContentTypeKey AND permission LIKE " + permissionSearchString,
-            new { ContentTypeKey = contentType.Key, PropertyTypeId = propertyTypeId });
+        // first clear dependencies
+        Sql<ISqlContext> sql = Sql()
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs]: See earlier comment about reuse of `sql` variable.

File: src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs [hunk 22]
```diff
@@ -1412,25 +1457,35 @@ private void RenormalizeDocumentEditedFlags(
...
+            .Delete<TagRelationshipDto>()
+            .Where<TagRelationshipDto>(x => x.PropertyTypeId == propertyTypeId);
+        _ = Database.Execute(sql);
+
+        sql = Sql()
+            .Delete<PropertyDataDto>()
+            .Where<PropertyDataDto>(x => x.PropertyTypeId == propertyTypeId);
+        _ = Database.Execute(sql);
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs]:
```suggestion
        Database.Execute(sql);
```

File: src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs [hunk 23]
```diff
@@ -1412,25 +1457,35 @@ private void RenormalizeDocumentEditedFlags(
...
+            .Where<UserGroup2GranularPermissionDto>(c => c.UniqueId == contentType.Key)
+            .WhereLike<UserGroup2GranularPermissionDto>(
+                c => c.Permission,
+                Sql()
+                    .SelectClosure<PropertyTypeDto>(c => c.ConvertUniqueIdentifierToString(x => x.UniqueId))
+                    .From<PropertyTypeDto>()
+                    .WhereClosure<PropertyTypeDto>(c => c.Id == propertyTypeId),
+                $"'|{SqlSyntax.GetWildcardPlaceholder()}'");
+
+        _ = Database.Execute(delSql);
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs]:
```suggestion
        Database.Execute(delSql);
```

File: src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs [hunk 24]
```diff
@@ -1412,25 +1457,35 @@ private void RenormalizeDocumentEditedFlags(
...
 
         // Finally delete the property type.
-        Database.Delete<PropertyTypeDto>(
-            "WHERE contentTypeId = @Id AND id = @PropertyTypeId",
-            new { contentType.Id, PropertyTypeId = propertyTypeId });
+        sql = Sql()
+            .Delete<PropertyTypeDto>()
+            .Where<PropertyTypeDto>(x => x.ContentTypeId == contentType.Id && x.Id == propertyTypeId);
+        _ = Database.Execute(sql);
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs]:
```suggestion
        Database.Execute(sql);
```

File: src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs [hunk 25]
```diff
@@ -1515,13 +1568,14 @@ private void AssignDataTypeIdFromProvidedKeyOrPropertyEditor(IPropertyType prope
...
-            @"SELECT cmsContentType." + aliasColumn + @" FROM cmsContentType
-INNER JOIN umbracoNode ON cmsContentType.nodeId = umbracoNode.id
-WHERE cmsContentType." + aliasColumn + @" LIKE @pattern",
-            new { pattern = alias + "%", objectType = NodeObjectTypeId });
+        Sql<ISqlContext> sql = Sql()
+            .Select<ContentTypeDto>(c => c.Alias)
+            .From<ContentTypeDto>()
+            .InnerJoin<NodeDto>().On<ContentTypeDto, NodeDto>((ct, n) => ct.NodeId == n.NodeId)
+            .WhereLike<ContentTypeDto>(c => c.Alias, alias)
+            .Where<NodeDto>(x => x.NodeObjectType == NodeObjectTypeId);
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs]: This is no longer checking that alias is unique across all content types (as the removed comment indicated).  Is this deliberate?

File: src/Umbraco.Infrastructure/Persistence/NPocoSqlExtensions.cs [hunk 26]
```diff
@@ -29,6 +30,11 @@ public static Sql<ISqlContext> Where<TDto>(this Sql<ISqlContext> sql, Expression
             return sql.Where(s, a);
         }
 
+        public static Sql<ISqlContext> WhereClosure<TDto>(this Sql<ISqlContext> sql, Expression<Func<TDto, bool>> predicate, string? alias = null)
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/NPocoSqlExtensions.cs:41]: I know we don't have them for all methods already, but I think this would benefit from an XML header comment, explaining what it's for.

File: src/Umbraco.Infrastructure/Persistence/NPocoSqlExtensions.cs [hunk 27]
```diff
@@ -113,10 +119,12 @@ public static Sql<ISqlContext> WhereIn<TDto>(this Sql<ISqlContext> sql, Expressi
         }
 
 
-        public static Sql<ISqlContext> WhereLike<TDto>(this Sql<ISqlContext> sql, Expression<Func<TDto, object?>> fieldSelector, Sql<ISqlContext>? valuesSql)
+        public static Sql<ISqlContext> WhereLike<TDto>(this Sql<ISqlContext> sql, Expression<Func<TDto, object?>> fieldSelector, Sql<ISqlContext>? valuesSql, string concatDefault = "")
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/NPocoSqlExtensions.cs:140]: I know we don't have them for all methods already, but I think this would benefit from an XML header comment, explaining what each parameter is for (in particular the new one added).

File: src/Umbraco.Infrastructure/Persistence/SqlSyntax/ISqlSyntaxProvider.cs [hunk 28]
```diff
@@ -90,6 +90,8 @@ DatabaseType GetUpdatedDatabaseType(DatabaseType current, string? connectionStri
 
     string GetWildcardPlaceholder();
 
+    string GetWildcardConcat(string concatDefault = "");
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/SqlSyntax/ISqlSyntaxProvider.cs:98]: I know we don't have them for all methods already, but I think this would benefit from an XML header comment, explaining what it's for.

File: src/Umbraco.Infrastructure/Persistence/NPocoSqlExtensions.cs (hunk 1 above)
Comment (idseefeld) [reply src/Umbraco.Infrastructure/Persistence/NPocoSqlExtensions.cs]: `Newtonsoft.Json.Linq;` was not used, so I removed the using.

File: src/Umbraco.Infrastructure/Persistence/NPocoSqlExtensions.cs (hunk 2 above)
Comment (idseefeld) [reply src/Umbraco.Infrastructure/Persistence/NPocoSqlExtensions.cs]: In the entire solution I found 67 matches for `_ = `. But I have fixed only files in this PR.

File: src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs (hunk 5 above)
Comment (idseefeld) [reply src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs]: I always like constants too! 😁

But why do think we need a using statement? 
All my changes just replace raw sql. 🤔

File: src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs (hunk 4 above)
Comment (idseefeld) [reply src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs]: Actually this is done by the `.SelectTop(1)` extension method which has its specific implementations for each provider.
I have moved it behind the `.Where` clause to make it more obvious.
The final SQL query reduces the data to one record and the **Linq** extension `.FirstOrDefault()` does the rest.

File: src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs (hunk 7 above)
Comment (idseefeld) [reply src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs]: Hm, you are right. The definition does not allow null. Could it be a runtime issue? I don't think so. 🤔

File: src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs (hunk 8 above)
Comment (idseefeld) [reply src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs]: Same as above.

File: src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs (hunk 9 above)
Comment (idseefeld) [reply src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs]: See comment above.

File: src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs (hunk 10 above)
Comment (idseefeld) [reply src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs]: Okay

File: src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs (hunk 11 above)
Comment (idseefeld) [reply src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs]: Okay.

File: src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs (hunk 12 above)
Comment (idseefeld) [reply src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs]: Removed all `_ = `.

File: src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs (hunk 13 above)
Comment (idseefeld) [reply src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs]: Makes sense. I have given each object a _hopefully_ useful name.

File: src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs (hunk 14 above)
Comment (idseefeld) [reply src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs]: Done

File: src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs (hunk 15 above)
Comment (idseefeld) [reply src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs]: Done

File: src/Umbraco.Infrastructure/Persistence/NPocoSqlExtensions.cs (hunk 26 above)
Comment (idseefeld) [reply src/Umbraco.Infrastructure/Persistence/NPocoSqlExtensions.cs:41]: Added one.

File: src/Umbraco.Infrastructure/Persistence/NPocoSqlExtensions.cs (hunk 27 above)
Comment (idseefeld) [reply src/Umbraco.Infrastructure/Persistence/NPocoSqlExtensions.cs:140]: Added.

File: src/Umbraco.Infrastructure/Persistence/SqlSyntax/ISqlSyntaxProvider.cs (hunk 28 above)
Comment (idseefeld) [reply src/Umbraco.Infrastructure/Persistence/SqlSyntax/ISqlSyntaxProvider.cs:98]: Added.

File: src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs (hunk 6 above)
Comment (idseefeld) [reply src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs]: Ah, I see there is a `Database.FirstOrDefault<...>()` method!
I changed it everywhere.

File: src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs (hunk 25 above)
Comment (idseefeld) [reply src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs]: I have added the comment again and checked the typed sql with the raw sql. 
This is only used in one obsolete method `Umbraco.Cms.Core.ServicesContentTypeServiceBase`:
```
[Obsolete("Please use CopyAsync. Will be removed in V16.")]
public Attempt<OperationResult<MoveOperationStatusType, TItem>?> Copy(TItem copying, int containerId)
{
    ...
}
```
What do you think? 
Should we nevertheless care about the `IContentTypeRepositoryBase<TItem>.GetUniqueAlias(string alias);` ?
If so we need a test for this too.

**Comment by idseefeld** [comment]
@AndyButland I have fixed your comments, but there still open questions for you...

File: src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs (hunk 5 above)
Comment (AndyButland) [reply src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs]: I just meant you may need a using statement in order to reference `Constants.System.RootString` (i.e. accepting the suggestion I made in GitHub may not be enough).

File: src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs (hunk 25 above)
Comment (AndyButland) [reply src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs]: The problem as I see it is that you have added this clause:

```
.Where<NodeDto>(x => x.NodeObjectType == NodeObjectTypeId)
```

Which isn't there in the original SQL.  So seem now this will only guarantee a unique alias across a specific object type (e.g. document type, media type or member type) rather than a unique alias across all of them.

File: src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs (hunk 5 above)
Comment (idseefeld) [reply src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs]: Can this wait until 8. October?
Than I am back and can the change...

File: src/Umbraco.Infrastructure/Persistence/NPocoSqlExtensions.cs [hunk 29]
```diff
@@ -74,7 +88,31 @@ public static Sql<ISqlContext> Where<TDto1, TDto2, TDto3>(this Sql<ISqlContext>
...
+        /// </summary>
+        /// <typeparam name="TDto">The type of the first Dto.</typeparam>
+        /// <typeparam name="TDto2">The type of the second Dto.</typeparam>
+        /// <param name="sql">The Sql statement.</param>
+        /// <param name="field">An expression specifying the first field.</param>
+        /// <param name="values">First values.</param>
+        /// <param name="field2">An expression specifying the second field.</param>
+        /// <param name="values2">Second values.</param>
+        /// <returns>The Sql statement.</returns>
+        public static Sql<ISqlContext> WhereInOr<TDto, TDto2>(
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/NPocoSqlExtensions.cs]: This doesn't seem to be used.  If we don't need it, could we remove, just to avoid building up the code maintenance burden?

File: src/Umbraco.Infrastructure/Persistence/NPocoSqlExtensions.cs [hunk 30]
```diff
@@ -678,6 +726,85 @@ public static Sql<ISqlContext> SelectTop(this Sql<ISqlContext> sql, int count)
...
+        /// with the specified DTO type.
+        /// </summary>
+        /// <typeparam name="TDto">The type of the Data Transfer Object (DTO) that represents the table from which the maximum value will be
+        /// selected.</typeparam>
+        /// <param name="sql">The SQL query builder to which the SELECT statement will be appended. Cannot be <see langword="null"/>.</param>
+        /// <param name="field">An expression specifying the field for which the maximum value will be calculated. Cannot be <see
+        /// langword="null"/>.</param>
+        /// <returns>A modified SQL query builder that includes the SELECT statement for the maximum value of the specified
+        /// field.</returns>
+        public static Sql<ISqlContext> SelectMax<TDto>(this Sql<ISqlContext> sql, Expression<Func<TDto, object?>> field)
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/NPocoSqlExtensions.cs]: This doesn't seem to be used. If we don't need it, could we remove, just to avoid building up the code maintenance burden?

File: src/Umbraco.Infrastructure/Persistence/NPocoSqlExtensions.cs [hunk 31]
```diff
@@ -678,6 +726,85 @@ public static Sql<ISqlContext> SelectTop(this Sql<ISqlContext> sql, int count)
...
+        /// </summary>
+        /// <typeparam name="TDto">The type of the Data Transfer Object (DTO) that represents the table from which the maximum value will be
+        /// selected.</typeparam>
+        /// <param name="sql">The SQL query builder to which the SELECT statement will be appended. Cannot be <see langword="null"/>.</param>
+        /// <param name="field">An expression specifying the field for which the maximum value will be calculated. Cannot be <see
+        /// langword="null"/>.</param>
+        /// <param name="coalesceValue">COALESCE int value.</param>
+        /// <returns>A modified SQL query builder that includes the SELECT statement for the maximum value of the specified
+        /// field or the coalesceValue.</returns>
+        public static Sql<ISqlContext> SelectMax<TDto>(this Sql<ISqlContext> sql, Expression<Func<TDto, object?>> field, int coalesceValue)
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/NPocoSqlExtensions.cs]: This doesn't seem to be used. If we don't need it, could we remove, just to avoid building up the code maintenance burden?

File: src/Umbraco.Infrastructure/Persistence/NPocoSqlExtensions.cs [hunk 32]
```diff
@@ -678,6 +726,85 @@ public static Sql<ISqlContext> SelectTop(this Sql<ISqlContext> sql, int count)
...
+        /// </summary>
+        /// <typeparam name="TDto">The type of the Data Transfer Object (DTO) that represents the table from which the maximum value will be
+        /// selected.</typeparam>
+        /// <param name="sql">The SQL query builder to which the SELECT statement will be appended. Cannot be <see langword="null"/>.</param>
+        /// <param name="field">An expression specifying the field for which the maximum value will be calculated. Cannot be <see
+        /// langword="null"/>.</param>
+        /// <param name="coalesceValue">COALESCE string value.</param>
+        /// <returns>A modified SQL query builder that includes the SELECT statement for the maximum value of the specified
+        /// field or the coalesceValue.</returns>
+        public static Sql<ISqlContext> SelectMax<TDto>(this Sql<ISqlContext> sql, Expression<Func<TDto, object?>> field, string coalesceValue)
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/NPocoSqlExtensions.cs]: This doesn't seem to be used. If we don't need it, could we remove, just to avoid building up the code maintenance burden?

File: src/Umbraco.Infrastructure/Persistence/NPocoSqlExtensions.cs [hunk 33]
```diff
@@ -678,6 +726,85 @@ public static Sql<ISqlContext> SelectTop(this Sql<ISqlContext> sql, int count)
...
+        /// </summary>
+        /// </summary>
+        /// <typeparam name="TDto">The type of the Data Transfer Object (DTO) that represents the table from which the maximum value will be
+        /// selected.</typeparam>
+        /// <param name="sql">The SQL query builder to which the SELECT statement will be appended. Cannot be <see langword="null"/>.</param>
+        /// <param name="field">An expression specifying the field for which the maximum value will be calculated. Cannot be <see
+        /// langword="null"/>.</param>
+        /// <returns>A modified SQL query builder that includes the SELECT statement for the maximum value of the specified
+        /// field.</returns>
+        public static Sql<ISqlContext> SelectSum<TDto>(this Sql<ISqlContext> sql, Expression<Func<TDto, object?>> field)
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/NPocoSqlExtensions.cs]: This doesn't seem to be used. If we don't need it, could we remove, just to avoid building up the code maintenance burden?

File: src/Umbraco.Infrastructure/Persistence/NPocoSqlExtensions.cs [hunk 34]
```diff
@@ -1163,6 +1290,40 @@ public static string Columns<TDto>(this Sql<ISqlContext> sql, string alias, para
             return string.Join(", ", sql.GetColumns(columnExpressions: fields, withAlias: false, tableAlias: alias));
         }
 
+        public static Sql<ISqlContext> SelectClosure<TDto>(this Sql<ISqlContext> sql, Func<SqlConvert<TDto>, SqlConvert<TDto>> converts)
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/NPocoSqlExtensions.cs:1195]: Could you add a similar XML header comment on this method please?

File: src/Umbraco.Infrastructure/Persistence/NPocoSqlExtensions.cs [hunk 35]
```diff
@@ -1183,6 +1344,19 @@ public static Sql<ISqlContext> Delete<TDto>(this Sql<ISqlContext> sql)
...
         }
 
+        /// <summary>
+        /// Deletes records from a table based on a predicate.
+        /// </summary>
+        /// <typeparam name="TDto">Table definitio.</typeparam>
+        /// <param name="sql">SqlConext</param>
+        /// <param name="predicate">A predicate to transform and append to the Sql statement (WHERE clause).</param>
+        /// <returns></returns>
+        public static Sql<ISqlContext> Delete<TDto>(this Sql<ISqlContext> sql, Expression<Func<TDto, bool>> predicate)
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/NPocoSqlExtensions.cs]: This doesn't seem to be used. If we don't need it, could we remove, just to avoid building up the code maintenance burden?

Comment (idseefeld) [reply src/Umbraco.Infrastructure/Persistence/NPocoSqlExtensions.cs]: Hi @AndyButland, as far as I remember, this PR is an excerpt of my bigger PR about sql syntax which you asked me to split up in smaller issues. This might explain why some new methods are not used.
So for this PR I am fine to remove them.
Regarding the extra WHERE clause I can not judge via mobile Github. Pease feel free to take over as you have done lately for another PR.
Btw.: Could it be a solution to add you as a contributer to my repo? I would trust you to do this when you want that. Although I have check whether I can do it in mobile Github ...
Yours
Dirk

Comment (AndyButland) [reply src/Umbraco.Infrastructure/Persistence/NPocoSqlExtensions.cs]: OK - thanks. I've already got access to your PR (I pushed a change to update to the latest in `v17/dev`), so I can make these changes if you are happy with me doing so.

Comment (idseefeld) [reply src/Umbraco.Infrastructure/Persistence/NPocoSqlExtensions.cs]: Yes, I am👍🏻😁

File: src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs (hunk 25 above)
Comment (AndyButland) [reply src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs]: Have removed the additional clause.
