### PR TITLE
Media Querying: Fix `MediaAtRoot()` to use `IMediaNavigationQueryService` root keys

### LINKED ISSUE #21806: IPublishedContentQuery.MediaAtRoot() returns empty in v17.1.0 (uses document root keys)
### Which Umbraco version are you using?

17.1.0

### Bug summary

IPublishedContentQuery.MediaAtRoot() always returns an empty enumerable in Umbraco 17.1.0, even when there are media items/folders at the media root. ContentAtRoot() returns items as expected.

### Specifics

```
// Example:
var contentRoots = _publishedContentQuery.ContentAtRoot().ToList(); // returns items ✅
var mediaRoots   = _publishedContentQuery.MediaAtRoot().ToList();   // empty ❌
```

From the source, MediaAtRoot() delegates to ItemsAtRoot(_publishedMediaCache), but ItemsAtRoot(...) uses IDocumentNavigationQueryService.TryGetRootKeys(...) (document/content root keys) and then tries to resolve those keys against the provided cache. For the media cache this results in nulls and an empty list.

Relevant code in PublishedContentQuery (v17.1.0):

```
MediaAtRoot() => ItemsAtRoot(_publishedMediaCache);

ItemsAtRoot(...) => _documentNavigationQueryService.TryGetRootKeys(out ...) ... cache.GetById(false, key) ...

```
This suggests MediaAtRoot() is using document root keys rather than media root keys.

Workaround (confirmed)

Using IMediaNavigationQueryService.TryGetRootKeys(...) and resolving via IPublishedMediaCache.GetById(false, key) returns the expected root media items/folders.

Proposed fix
Inject and use IMediaNavigationQueryService for MediaAtRoot() (and keep IDocumentNavigationQueryService for ContentAtRoot()), or refactor ItemsAtRoot to accept an INavigationQueryService so the correct navigation service is used for each tree.

### Steps to reproduce

Create a clean Umbraco 17.1.0 install.

In the Media section, create a folder or upload an item at the media root (top level).

Add a controller (or view) that injects IPublishedContentQuery and calls:

_publishedContentQuery.ContentAtRoot() (returns items)

_publishedContentQuery.MediaAtRoot() (returns empty)

(Optional) Call IMediaNavigationQueryService.TryGetRootKeys(...) and resolve keys via IPublishedMediaCache.GetById(false, key) to confirm root media exists.

### Expected result / actual result

Expected: MediaAtRoot() returns the published media items/folders at the media root.
Actual: MediaAtRoot() returns an empty enumerable in v17.1.0, while root media exists and can be resolved via media navigation keys.

### PR DESCRIPTION
**Pull request by FabCodeDE**
### Summary
This PR fixes `IPublishedContentQuery.MediaAtRoot()` returning an empty list by ensuring it uses media root keys instead of document root keys.

### What changed
- Introduced `IMediaNavigationQueryService` as a dependency for `PublishedContentQuery`.
- Updated constructors to resolve `IMediaNavigationQueryService`.
- Refactored `ItemsAtRoot(...)` to accept an `INavigationQueryService` so the correct navigation service can be used.
- `ContentAtRoot()` now uses `IDocumentNavigationQueryService`.
- `MediaAtRoot()` now uses `IMediaNavigationQueryService`.

### Why
`MediaAtRoot()` previously delegated to `ItemsAtRoot(_publishedMediaCache)`, but `ItemsAtRoot(...)` retrieved root keys via `IDocumentNavigationQueryService` (document/content tree). Those keys do not correspond to media root keys, so resolving them against the published media cache results in `null` values and an empty enumerable.

### Prerequisites
- [x] I have added steps to test this contribution in the description below

### Fixes
Fixes #21806

### How to test (manual)
1. Create a clean Umbraco install (or use an existing site).
2. In the **Media** section, create a folder at the media root (top level), e.g. `TestRootFolder`.
3. Add a quick controller or view that calls `IPublishedContentQuery.MediaAtRoot()` and outputs the count/names.

Example (controller action):
```csharp
public IActionResult DebugMediaAtRoot(IPublishedContentQuery publishedQuery)
{
    var mediaRoots = publishedQuery.MediaAtRoot().ToList();
    return Ok(new
    {
        count = mediaRoots.Count,
        items = mediaRoots.Select(x => new { x.Id, x.Key, x.Name })
    });
}
```
Before this PR: MediaAtRoot() returns count = 0.

With this PR applied: MediaAtRoot() returns the root media items/folders (e.g. count >= 1 and includes TestRootFolder).

Sanity check: IPublishedContentQuery.ContentAtRoot() continues to work as before.

Notes

No automated tests were added in this PR (manual verification only).

### CODE REVIEW

**Comment by FabCodeDE** [comment]
Heads-up: CI currently fails due to APICompat because the PR changes/removes public constructor signatures (baseline 17.0.0). 
If maintainers prefer a non-breaking fix, I can update this PR to keep the existing public constructors and resolve `IMediaNavigationQueryService` internally (lazy/service provider) while still fixing `MediaAtRoot()`.

File: src/Umbraco.Infrastructure/PublishedContentQuery.cs [hunk 1]
```diff
@@ -236,9 +241,9 @@ private static IEnumerable<IPublishedContent> ItemsByIds(IPublishedCache? cache,
     private IEnumerable<IPublishedContent> ItemsByIds(IPublishedCache? cache, IEnumerable<Guid> ids)
         => ids.Select(eachId => ItemById(eachId, cache)).WhereNotNull();
 
-    private IEnumerable<IPublishedContent> ItemsAtRoot(IPublishedCache? cache)
-        => _documentNavigationQueryService.TryGetRootKeys(out IEnumerable<Guid> rootKeys) is false ? []
-            : rootKeys.Select(x => cache?.GetById(false, x)).WhereNotNull();
+    private static IEnumerable<IPublishedContent> ItemsAtRoot(IPublishedCache? cache, INavigationQueryService nav)
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/PublishedContentQuery.cs]: Maybe use `navigationQueryService` as the variable name, just to be a bit clearer than `nav`.

**Comment by FabCodeDE** [comment]
Thanks @AndyButland for the review!

I’ve now implemented the non-breaking constructor approach you described for both `PublishedContentQuery` and `ContentFinderByConfigured404`:

- Added new constructors including the additional dependency (`IMediaNavigationQueryService`).
- Kept the existing constructors, marked with `[Obsolete("Please use the constructor taking all parameters. Scheduled for removal in Umbraco 19")]`.
- Delegated from the obsolete constructors to the new ones, resolving the new dependency via `StaticServiceProvider`.
- Updated all call sites to use the new constructors.

Also applied the small naming tweak: renamed the `ItemsAtRoot` parameter from `nav` to `navigationQueryService` for clarity.

Finally, I’ve added automated tests (with help from Codex). I hope they cover the most important scenarios around this change (in particular verifying `MediaAtRoot()` uses the media navigation/root keys and resolves via the media cache), but please let me know if there are any additional edge cases you’d like me to include.

**Review by AndyButland — APPROVED** [review]
All looks good to me now @FabCodeDE and I've verified the fix too with manual testing.

I cleaned up the constructor obsoletion a little and adjusted the added tests.  I removed a few low value ones and moved many to be unit rather than integration tests so they no longer have a neglible cost to run.

**Comment by FabCodeDE** [comment]
Thank you very much @AndyButland ! Do you know when exactly 17.3 will be released so that we can continue or Umbraco 13 to 17 Upgrade?

**Comment by AndyButland** [comment]
See https://releases.umbraco.com/ for release dates of upcoming versions.
