### PR TITLE
Fixed missing null check in BlockEditorPropertyEditor

### LINKED ISSUE #10095: [NETCORE] Alpha 4 - Saving a nested block list with item limits (min/max) results in NullReferenceException
I created a block list schema including nested items - when I went to save a content node with the properties I received the following error:

```
Object reference not set to an instance of an object.

Exception Details
System.NullReferenceException, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e: Object reference not set to an instance of an object.
at Umbraco.Web.PropertyEditors.BlockEditorPropertyEditor.MinMaxValidator.Validate(Object value, String valueType, Object dataTypeConfiguration)+MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToList()
   at Umbraco.Cms.Core.PropertyEditors.DataValueEditor.Validate(Object value, Boolean required, String format)
   at Umbraco.Core.Services.PropertyValidationService.ValidatePropertyValue(IDataEditor editor, IDataType dataType, Object postedValue, Boolean isRequired, String validationRegExp, String isRequiredMessage, String validationRegExpMessage)+MoveNext()
   at Umbraco.Web.PropertyEditors.ComplexEditorValidator.GetNestedValidationResults(IEnumerable`1 elements)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Umbraco.Web.PropertyEditors.ComplexEditorValidator.Validate(Object value, String valueType, Object dataTypeConfiguration)
   at Umbraco.Cms.Core.PropertyEditors.DataValueEditor.<>c__DisplayClass23_0.<Validate>b__0(IValueValidator v)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToList()
   at Umbraco.Cms.Core.PropertyEditors.DataValueEditor.Validate(Object value, Boolean required, String format)
   at Umbraco.Core.Services.PropertyValidationService.ValidatePropertyValue(IDataEditor editor, IDataType dataType, Object postedValue, Boolean isRequired, String validationRegExp, String isRequiredMessage, String validationRegExpMessage)+MoveNext()
   at Umbraco.Web.PropertyEditors.ComplexEditorValidator.GetNestedValidationResults(IEnumerable`1 elements)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Umbraco.Web.PropertyEditors.ComplexEditorValidator.Validate(Object value, String valueType, Object dataTypeConfiguration)
   at Umbraco.Cms.Core.PropertyEditors.DataValueEditor.<>c__DisplayClass23_0.<Validate>b__0(IValueValidator v)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToList()
   at Umbraco.Cms.Core.PropertyEditors.DataValueEditor.Validate(Object value, Boolean required, String format)
   at Umbraco.Core.Services.PropertyValidationService.ValidatePropertyValue(IDataEditor editor, IDataType dataType, Object postedValue, Boolean isRequired, String validationRegExp, String isRequiredMessage, String validationRegExpMessage)+MoveNext()
   at Umbraco.Web.PropertyEditors.ComplexEditorValidator.GetNestedValidationResults(IEnumerable`1 elements)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Umbraco.Web.PropertyEditors.ComplexEditorValidator.Validate(Object value, String valueType, Object dataTypeConfiguration)
   at Umbraco.Cms.Core.PropertyEditors.DataValueEditor.<>c__DisplayClass23_0.<Validate>b__0(IValueValidator v)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToList()
   at Umbraco.Cms.Core.PropertyEditors.DataValueEditor.Validate(Object value, Boolean required, String format)
   at Umbraco.Core.Services.PropertyValidationService.ValidatePropertyValue(IDataEditor editor, IDataType dataType, Object postedValue, Boolean isRequired, String validationRegExp, String isRequiredMessage, String validationRegExpMessage)+MoveNext()
   at Umbraco.Cms.Web.BackOffice.Filters.ContentModelValidator`3.ValidatePropertyValue(TModelSave model, TModelWithProperties modelWithProperties, IDataEditor editor, ContentPropertyDto property, Object postedValue, ModelStateDictionary modelState)
   at Umbraco.Cms.Web.BackOffice.Filters.ContentModelValidator`3.ValidatePropertiesData(TModelSave model, TModelWithProperties modelWithProperties, ContentPropertyCollectionDto dto, ModelStateDictionary modelState)
   at Umbraco.Cms.Web.BackOffice.Filters.ContentSaveValidationAttribute.ContentSaveValidationFilter.OnActionExecutingAsync(ActionExecutingContext context)
   at Umbraco.Cms.Web.BackOffice.Filters.ContentSaveValidationAttribute.ContentSaveValidationFilter.OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
```

## Umbraco version

I am seeing this issue on Umbraco version: nightly build 9.0.0-beta001.20210222.10

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

I may need to provide a copy of the database... will be available on request privately :)

### PR DESCRIPTION
**Pull request by lauraneto**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes #10095

### Description
Added a null check to the `Validate` method of the `BlockEditorPropertyEditor`.

I was able to reproduce the issue mentioned in #10095 by doing the following steps:

1. Create a document type containing a block list property that has a minimum amount set.
2. Create a new block list, select any block as an available block and set the settings model to the document created in the previous step
3. Select `Inline editing mode`
4. Save
5. Add the block list you just created to a document type and try to add a block to a node of that type (without filling in the settings)
6. Try to publish and see the error reported in [#10095](https://github.com/umbraco/Umbraco-CMS/issues/10095)

### CODE REVIEW

File: src/Umbraco.Infrastructure/PropertyEditors/BlockEditorPropertyEditor.cs [hunk 1]
```diff
@@ -264,7 +263,7 @@ public IEnumerable<ValidationResult> Validate(object value, string valueType, ob
                         _textService.Localize("validation", "entriesShort", new[]
                         {
                             validationLimit.Min.ToString(),
-                            (validationLimit.Min - blockEditorData.Layout.Count()).ToString()
+                            (validationLimit.Min - (blockEditorData?.Layout.Count() ?? 0)).ToString()
```
Comment (bjarnef) [inline src/Umbraco.Infrastructure/PropertyEditors/BlockEditorPropertyEditor.cs:266]: I guess it potential need the same null check for `Max` as well here:
https://github.com/umbraco/Umbraco-CMS/pull/11184/files#diff-08b637d7d3f18c3bd184b2d3ebd9563ab2f72b70fde8aa34432404cb3185a99aR277

Comment (lauraneto) [reply src/Umbraco.Infrastructure/PropertyEditors/BlockEditorPropertyEditor.cs:266]: `Max` already has a null check for `blockEditorData` in [Line 271](https://github.com/umbraco/Umbraco-CMS/pull/11184/files#diff-08b637d7d3f18c3bd184b2d3ebd9563ab2f72b70fde8aa34432404cb3185a99aR271), so it shouldn't be needed.

Comment (bjarnef) [reply src/Umbraco.Infrastructure/PropertyEditors/BlockEditorPropertyEditor.cs:266]: Yes, it has a null check for `blockEditorData`:
https://github.com/umbraco/Umbraco-CMS/blob/f421fa72935aaa1dbcc5dbf7fc3926f21b1c2fc2/src/Umbraco.Infrastructure/PropertyEditors/BlockEditorPropertyEditor.cs#L271

but shouldn't this always a null for `blockEditorData` as well?
https://github.com/umbraco/Umbraco-CMS/blob/f421fa72935aaa1dbcc5dbf7fc3926f21b1c2fc2/src/Umbraco.Infrastructure/PropertyEditors/BlockEditorPropertyEditor.cs#L259-L269

Comment (lauraneto) [reply src/Umbraco.Infrastructure/PropertyEditors/BlockEditorPropertyEditor.cs:266]: Well, in my case I had no items so it was ending up `null` and causing the initial issue, so if it's returning `null` when there are no items I think it makes sense to show the entries short validation message.

**Review by OwainWilliams — APPROVED** [review]

**Comment by nul800sebastiaan** [comment]
Cherry picked for v8 in 3f0552d5d183a60f2ba6edc08855918b136501aa
