### PR TITLE
Redirect Tracking: Fix segment change detection and optimise descendant traversal (closes #22082)

### LINKED ISSUE #22082: V17 - Massive performance issue on publishing "home page" on larger sites
### Which Umbraco version are you using?

17.2.2

### Bug summary

If you have a largish site (in our case 33K+ nodes) and this is laid out (for example) in your traditional

Home Page
      --> About Us
      --> News
           --> Year 
           -->  ...
                --> Month
                -->  ...
                   --> Day
                   --> ...
                       -->  n x news articles

And you have several other large nested sections in addition to this, then publishing the home page can cause a lock error on -333.  This often then requires a recycling of the site in order to get the content tree back up and running.  It also can manifest itself when the site starts up, especially in a local development environment.

### Specifics

By using a clean Umbraco install, it removes the possibility of custom indexes, hangfire, custom stuff in general causing a problem.

I traced the problem though the Umbraco codebase and for publishing, it seems to manifest itself when the publishing process is updating the internal redirect values.  When content is published it will eventually get to the **RedirectTrackingHandler** which will, for the home page in this example, go to the **StoreOldRoute** method in the **RedirectTracker**.  Without wanting to write out the entire stack trace, this will eventually get to the **GetDescendantsRecursively** in the **ContentNavigationServiceBase**.

 ```
   private static void GetDescendantsRecursively(
        ConcurrentDictionary<Guid, NavigationNode> structure,
        NavigationNode node,
        List<Guid> descendants,
        Guid? contentTypeKey = null)
    {
        // Get all children regardless of contentType
        IReadOnlyList<Guid> childrenKeys = GetOrderedChildren(node, structure);
        foreach (Guid childKey in childrenKeys)
        {
            // Apply contentTypeKey filter
            if (contentTypeKey.HasValue is false || structure[childKey].ContentTypeKey == contentTypeKey.Value)
            {
                descendants.Add(childKey);
            }

            // Retrieve the child node and its descendants
            if (structure.TryGetValue(childKey, out NavigationNode? childNode))
            {
                GetDescendantsRecursively(structure, childNode, descendants, contentTypeKey);
            }
        }
    }
```
As you can see, this then calls itself for descendants, which in turn then calls it's own descendants and so on and so forth.  What I believe is happening, is that this is taking so long on a large site, that it's timing out and creating a lock issue which eventually manifests as a -333.

I've tried updating the config settings **DistributedLockingWriteLockDefaultTimeout** and **DistributedLockingReadLockDefaultTimeout** however this didn't make a difference.

**Workaround**
The only workaround I've found so far is to disable internal redirect tracking (**DisableRedirectUrlTracking**), but obviously this isn't really ideal!

### Steps to reproduce

1. Get a database from large site
2. Clean install of Umbraco (17.2.2 or any 17)
3. Publish the home page
4. Observer the "spinning icon" on the publish button for a while

Image

5. Get the -333 error

Image

### Expected result / actual result

Expected result: Home page to publish
Actual result: Timeout issue, page not published and content/media trees inoperable

### PR DESCRIPTION
**Pull request by AndyButland**
## Prerequisites

- [x] I have added steps to test this contribution in the description below

## Description

This PR addresses https://github.com/umbraco/Umbraco-CMS/issues/22082 by optimising the redirect tracker.

As part of that work, I've found and fixed a couple of bugs that would otherwise prevent URL redirects from being created when content is renamed.

### Changes

**1. Optimisation: Skip descendant traversal when URL segment is unchanged**

The main problem I feel is that we are currently checking to create redirects for the node and it's descendants on every save and publish.  In the vast majority of these cases, no redirects are needed and so this is wasteful.  On the other hand, we can't just simply check if the node name or `umbracoUrlName` property has changed, as whilst out of the box that's all that impacts the generated URL segment.  URL segment providers are extensible, so we can't know what factors might go into calculating the URL segment.

To resolve this I've used the segment providers themselves to find the new segment, compared it to the old, and if they are the same, early return to not carry out the unnecessary traversal of descendent nodes.  If the segment is unchanged, no descendant URLs can have changed either, so the entire traversal is skipped.

This is implemented via a new `IUrlSegmentProvider.HasUrlSegmentChanged` method with a default interface implementation, replacing a long-standing TODO comment.  The intention is that this a permanent default implementation, so only providers that need to update this behaviour need to implement it.

The `IRedirectTracker.StoreOldRoute` method has a new `bool isMove` overload  so the handler can distinguish publishes from moves — moves will still always traverse descendants since the parent path changes.

**2. Optimisation: Batch deduplication of already-processed descendants**

When multiple content items are published in a batch and a parent's traversal already processed a child, the child's subsequent `StoreOldRoute` call is skipped by checking if its ID is already in the `oldRoutes` dictionary.

**3. Bug fix: `DocumentUrlService.GetUrlSegment` returned null for invariant content**

`GetUrlSegment` and `GetUrlSegments` returned null/empty when called with an empty culture string for invariant content. Invariant content is stored with a null language ID in the cache, but `TryGetLanguageIdFromCulture("")` fails — the code previously returned early at that point. Now it falls through to the invariant (null language ID) cache lookup. `TryGetPrimaryUrlSegment` had the same issue and is fixed identically.

**4. Bug fix: `DefaultUrlSegmentProvider` ignored `published` parameter in name fallback**

When content has no `umbracoUrlName` property, `GetUrlSegmentSource` falls back to the content name. The fallback had a special case: if `document.Edited` is true and a published name exists, always return the published name — regardless of the `published` parameter. This meant `GetUrlSegment(content, published: false, culture)` returned the *old* published name instead of the current draft name.

This broke redirect tracking: `HasUrlSegmentChanged` compares the currently-published segment against what the segment *will* be after publishing (draft values), but both sides returned the published name, so no change was ever detected for invariant content.

The fix adds `published &&` to the condition so the published-name preference only applies when `published: true` is requested. When `published: false`, the current (draft) name is returned — consistent with how the `umbracoUrlName` property path already behaved.

### Automated

The various unit and integration tests added in this PR, plus existing ones for these classes, should pass.

#### Invariant content — rename and publish

1. Create a document type with no culture variation (invariant)
2. Create and publish a content node (e.g. "Original Name")
3. Verify URL works: `/original-name`
4. Rename the node to "New Name" and publish
5. **Expected**: A 301 redirect is created from `/original-name` → `/new-name`
6. Verify in Content → URL Redirects that the redirect appears
7. Browse to `/original-name` — should redirect to `/new-name`

#### Variant content — rename and publish

1. Create a document type with culture variation enabled
2. Create and publish a content node with at least one culture (e.g. "English Page" in en-US)
3. Rename the en-US variant to "Updated English Page" and publish
4. **Expected**: A 301 redirect is created from the old URL to the new URL
5. Verify in Settings → URL Redirects

#### Move operation — verify descendants are tracked

1. Create a parent node with a child node, both published
2. Note the child's URL (e.g. `/parent/child`)
3. Move the parent under a different node
4. **Expected**: Redirects are created for both the parent and child URLs

#### No-change publish — verify no unnecessary work

1. Publish a content node without changing its name
2. Verify no new redirects are created
3. Put a break point in `RedirectTracker` (line 89) and verify that the method early returns to avoid the unnecessary work.

## Documentation

We should document `MayAffectDescendantSegments` on `IUrlSegmentProvider`.

### CODE REVIEW

File: src/Umbraco.Infrastructure/Routing/RedirectTracker.cs [hunk 1]
```diff
@@ -50,17 +55,42 @@ public RedirectTracker(
...
         if (entityContent is null)
         {
             return;
         }
 
+        // If this entity was already processed by an ancestor's traversal in this batch,
+        // all its descendants will also have been processed — skip entirely to avoid redundant
+        // cache lookups, segment checks, and navigation queries.
+        if (oldRoutes.Keys.Any(k => k.ContentId == entityContent.Id))
+        {
```
[the remark this answers is not in the document]
Comment (AndyButland) [reply src/Umbraco.Infrastructure/Routing/RedirectTracker.cs:84]: This doesn't look to be an improvement, as it's creating a new HashSet on each call.

**Comment by AndyButland** [comment]
We've discussed an an edge case where the segment-unchanged optimization could break custom `IUrlSegmentProvider` implementations.  It may seem unlikely, but does show a flaw in the approach.

### Scenario

```
- Node1 (type1) has propertyA and propertyB
  - Node2 (type2) is a child of Node1
```

A custom segment provider uses `propertyA` to compute Node1's segment, but uses `propertyB` on the ancestor (Node1) to compute Node2's segment.

When `propertyB` on Node1 changes, Node2's URL segment changes — but Node1's own segment is unchanged. The optimization would incorrectly skip descendant traversal, missing the redirect for Node2.

### Proposed Solution

Added `IUrlSegmentProvider.MayAffectDescendantSegments(IContentBase content)` with a default of `false`. The skip condition now requires all the following to be true:

  1. Not a move operation
  2. Content's own URL segment is unchanged
  3. No registered provider reports that this content may affect descendant segments

Custom providers that derive descendant segments from ancestor data (or external sources) can override this, either returning true unconditionally, or using logic (e.g. checking the content type, level or property values) to limit traversal to affected subtrees. The built-in provider returns `false` (the default), so the optimization applies in the common case.

File: src/Umbraco.Infrastructure/Routing/RedirectTracker.cs [hunk 2]
```diff
@@ -50,17 +55,47 @@ public RedirectTracker(
...
+            return;
+        }
+
+        // For publishes (not moves), check if URL segment actually changed and whether any provider
+        // derives descendant segments from this content's data.
+        // If the segment is unchanged and no provider affects descendants, we don't need to traverse.
+        // For moves, we have to assume all descendant URLs may have changed since the parent path is part of the URL.
+        if (isMove is false
```
Comment (Migaroez) [inline src/Umbraco.Infrastructure/Routing/RedirectTracker.cs]: Not saying we have to but

We can fix the codesmell with an internal (for testing) method, or keep it private

```csharp
internal bool ShouldIgnoreForOldRouteStorage(IContent entity, bool isMove, IPublishedContent entityContent) =>
        isMove is false
        && HasUrlSegmentChanged(entity, entityContent) is false
        && HasProviderAffectingDescendantSegments(entity) is false;
```

File: src/Umbraco.Infrastructure/Routing/RedirectTracker.cs [hunk 3]
```diff
@@ -106,6 +142,71 @@ public void StoreOldRoute(IContent entity, Dictionary<(int ContentId, string Cul
...
+
+                if (provider.AllowAdditionalSegments is false)
+                {
+                    break;
+                }
+            }
+
+            // No fallback is needed here: if no registered provider produces a segment, then none would have produced
+            // one at publish time either, so there is no change.
+        }
```
Comment (Migaroez) [inline src/Umbraco.Infrastructure/Routing/RedirectTracker.cs:200]: We can fix the complex method by introducing a new one called EntityHasNoCurrentSegmentOrSegmentHasChangedForCulture (or something better 😅)

Or move the foreach (IUrlSegmentProvider provider in _urlSegmentProviders) into its own function AnySegmentProviderDetectsChangedSegment()

File: src/Umbraco.Infrastructure/Routing/RedirectTracker.cs (hunk 2 above)
Comment (AndyButland) [reply src/Umbraco.Infrastructure/Routing/RedirectTracker.cs]: Good idea, I've refactored that as you suggest.

File: src/Umbraco.Infrastructure/Routing/RedirectTracker.cs (hunk 3 above)
Comment (AndyButland) [reply src/Umbraco.Infrastructure/Routing/RedirectTracker.cs:200]: I've done some refactoring along these lines.
