### PR TITLE
Fix invariant redirect tracking

### LINKED ISSUE #11984: Redirect Url Management not working with Contenttypes(Allow vary by culture)
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.3

### Bug summary

See https://github.com/umbraco/Umbraco-CMS/issues/11695
Should be fixed in version 9.3 -> See https://our.umbraco.com/download/releases/930

Fix didn't work for documenttypes where 'Allow vary by culture' is checked!

### Specifics

_No response_

### Steps to reproduce

https://user-images.githubusercontent.com/15004685/153610609-6568e979-2a3e-4c8e-9c2e-5f816a90d6b6.mp4

### Expected result / actual result

_No response_

---
_This item has been added to our backlog [AB#17419](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/17419)_

### PR DESCRIPTION
**Pull request by nikolajlauridsen**
This closes #11984.

While testing the above issue I was unable to replicate the exact issue, and the original issue creator has returned and mentioned that they can no longer reproduce this. 

However when doing some testing I noticed that redirect tracking is broken for invariant content types, as is also confirmed by a commenter on issue #11695, this PR fixes this issue with invariant redirect tracking.

I found two problems, the first of which are that whenever you publish or move some content a notification is handled by a `RedirectTrackingHandler`, in this request the culture of an invariant content node will have a culture as an empty string `""`, and not null. This mean that when we tried to generate the route from the cache it looked for something with a culture of empty string, instead of null as it expected. To fix this I've updated `LangId` on `CacheKeys` to consider an empty string or null as invariant culture.

The second issue was now the other way around, when the request is incoming to a redirect URL we try to get the redirectUrl from the `RedirectUrlService` and because we save the culture as an empty string, the culture of the `IRedirectUrl` will also be an empty string, and this broke `DefaultUrlProvider` because it only checked the culture with `culture is null` now we instead check it with `string.IsNullOrEmpty`, resolving the issue. 

## Testing

Test this with both invariant and variant content 

* Create a document type
* Create a piece of root content and a child 
* Try and rename the child
* Ensure that a redirect URL is generated in the redirection dashboard and that this will redirect to the new URL

### CODE REVIEW

File: src/Umbraco.Infrastructure/Routing/RedirectTrackingHandler.cs [hunk 1]
```diff
@@ -99,25 +99,32 @@ private void StoreOldRoute(IContent entity, OldRoutesDictionary oldRoutes)
             {
                 return;
             }
-            var contentCache = publishedSnapshot.Content;
-            var entityContent = contentCache?.GetById(entity.Id);
+
+            IPublishedContentCache contentCache = publishedSnapshot.Content;
+            IPublishedContent entityContent = contentCache?.GetById(entity.Id);
             if (entityContent == null)
```
Comment (Zeegaan) [inline src/Umbraco.Infrastructure/Routing/RedirectTrackingHandler.cs:105]: might aswell change this while we're here
```suggestion
            if (entityContent is null)
```

**Review by Zeegaan — APPROVED** [review]
Tested this and it works! Had a small thing we might as well change when we're updating the class, but everything else looks good 🎉

File: src/Umbraco.Infrastructure/Routing/RedirectTrackingHandler.cs (hunk 1 above)
Comment (nikolajlauridsen) [reply src/Umbraco.Infrastructure/Routing/RedirectTrackingHandler.cs:105]: Good point 👍
