### PR TITLE
Block Variance: Ensure de-duplication and removal of orphaned expose entries in `BlockEditorVarianceHandler`

### LINKED ISSUE #21799: BlockEditorVarianceHandler doesn't deduplicate expose entries when no alignment is needed
# Issue: BlockEditorVarianceHandler doesn't deduplicate expose entries when no alignment is needed

## Description

The `AlignExposeVariance` method in `BlockEditorVarianceHandler` only performs deduplication when variance alignment is needed. If all expose entries are already correctly aligned, the method returns early and skips the deduplication step, leaving duplicate entries in the `Expose` collection.

## Current Behavior

When `contentDataToAlign.Any() is false`, the method returns early at line 200-202, skipping the deduplication logic at line 217. This means duplicate expose entries remain in the collection.

## Expected Behavior

Deduplication should always run, regardless of whether variance alignment is needed.

## Reproduction Steps

1. Create a block list with a block item that has duplicate expose entries with the same `ContentKey`, `Culture`, and `Segment`
2. Ensure the expose entries are already correctly aligned (no variance mismatch)
3. Call `AlignExposeVariance` on the block value
4. Observe that duplicate entries remain in `blockValue.Expose`

## Code Location

`src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/BlockEditorVarianceHandler.cs`
- Method: `AlignExposeVariance`
- Problematic code: Early return at lines 200-202 prevents deduplication at line 217

## Proposed Fix

Move the deduplication logic outside the conditional block so it always executes, even when no alignment is needed.

## Test Case

```csharp
[Test]
public void AlignExposeVariance_Deduplicates_Expose_Entries()
{
    var owner = PublishedElement(ContentVariation.Culture);
    var contentDataKey = Guid.NewGuid();
    var values = CreateBlockPropertyValues(
        ("one", "da-DK", null, "Value one"),
        ("two", "da-DK", null, "Value two"));
    var expose = CreateBlockItemVariations(
        (contentDataKey, "da-DK", null),
        (contentDataKey, "da-DK", null)); // Duplicate entry
    var blockValue = CreateBlockListValue(contentDataKey, owner.ContentType.Key, values, expose);
    ExecuteAlignExposeVariance(owner, blockValue);
    Assert.AreEqual(1, blockValue.Expose.Count); // Should be 1, not 2
}
```

### LINKED ISSUE #21800: BlockEditorVarianceHandler doesn't remove orphaned expose entries when ContentData is missing
# Issue: BlockEditorVarianceHandler doesn't remove orphaned expose entries when ContentData is missing

## Description

When block items are deleted from `ContentData`, their corresponding entries in the `Expose` collection are not removed. This leaves orphaned `BlockItemVariation` entries that reference non-existent content, causing potential issues in rendering and data consistency.

## Current Behavior

The `AlignExposeVariance` method iterates through `blockValue.Expose` and skips entries where `contentData is null` (line 178-180), but it doesn't remove these orphaned entries from the collection. This results in `Expose` entries that reference `ContentKey`s that don't exist in `ContentData`.

## Expected Behavior

Any `Expose` entry whose `ContentKey` doesn't have a corresponding entry in `ContentData` should be removed from the `Expose` collection.

## Reproduction Steps

1. Create a block list with block items in both `ContentData` and `Expose`
2. Manually remove a block item from `ContentData` (simulating deletion)
3. Keep the corresponding entry in `Expose` (this simulates the bug scenario)
4. Call `AlignExposeVariance` on the block value
5. Observe that the orphaned expose entry remains in `blockValue.Expose`

## Code Location

`src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/BlockEditorVarianceHandler.cs`
- Method: `AlignExposeVariance`
- Problematic code: Lines 178-180 skip orphaned entries but don't remove them

## Proposed Fix

Track valid `ContentData` keys and remove any `Expose` entries whose `ContentKey` is not found in the `ContentData` collection.

## Test Case

```csharp
[Test]
public void AlignExposeVariance_Removes_Expose_When_ContentData_Is_Missing()
{
    var owner = PublishedElement(ContentVariation.Culture);
    var blockValue = CreateBlockListValue(Guid.NewGuid(), owner.ContentType.Key, [], 
        [new() { ContentKey = Guid.NewGuid(), Culture = "da-DK" }]); // Orphaned expose entry
    ExecuteAlignExposeVariance(owner, blockValue);
    Assert.IsEmpty(blockValue.Expose); // Should be empty
}
```

### PR DESCRIPTION
**Pull request by kiannidev**
## Summary

Fixes two bugs in `BlockEditorVarianceHandler.AlignExposeVariance`:
1. Deduplication not running when no alignment is needed
2. Orphaned expose entries not removed when ContentData is missing

## Related Issues

- Fixes #21799 - BlockEditorVarianceHandler doesn't deduplicate expose entries when no alignment is needed
- Fixes #21800 - BlockEditorVarianceHandler doesn't remove orphaned expose entries when ContentData is missing

## What Changed

**Bug Fix 1: Deduplication Always Runs**
- Moved deduplication logic outside the early return condition
- Deduplication now always executes, even when no variance alignment is needed
- Fixes issue where duplicate expose entries remained when entries were already correctly aligned

**Bug Fix 2: Remove Orphaned Expose Entries**
- Added cleanup to remove `Expose` entries whose `ContentKey` doesn't exist in `ContentData`
- Prevents orphaned references when block items are deleted
- Improves data consistency and prevents rendering issues

### CODE REVIEW

**Comment by emmagarland** [comment]
Hi @kiannidev 

Thanks for your PR to fix #21799 and #21800, fixing `BlockEditorVairanceHandler` deduplication and orphaned expose entries. 

One of the Core Collaborators team or HQ team will review this as soon as possible :)

Thanks,

Emma

File: src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/BlockEditorVarianceHandler.cs [hunk 1]
```diff
@@ -197,11 +198,11 @@ public void AlignExposeVariance(BlockValue blockValue)
...
 
-        if (contentDataToAlign.Any() is false)
-        {
-            return;
-        }
+        // Remove expose entries that don't have matching ContentData
+        blockValue.Expose.RemoveAll(v => !validContentKeys.Contains(v.ContentKey));
 
+        if (contentDataToAlign.Any())
+        {
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/BlockEditorVarianceHandler.cs:205]: The indentation is off here - could you correct it such that the if block is nested as would be expected for C# code please?

File: src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/BlockEditorVarianceHandler.cs [hunk 2]
```diff
@@ -197,11 +198,11 @@ public void AlignExposeVariance(BlockValue blockValue)
             }
         }
 
-        if (contentDataToAlign.Any() is false)
-        {
-            return;
-        }
+        // Remove expose entries that don't have matching ContentData
+        blockValue.Expose.RemoveAll(v => !validContentKeys.Contains(v.ContentKey));
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/BlockEditorVarianceHandler.cs]:
```suggestion
        blockValue.Expose.RemoveAll(v => validContentKeys.Contains(v.ContentKey) is false);
```

This is the usual syntax we use for new code.

File: src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/BlockEditorVarianceHandler.cs (hunk 1 above)
Comment (kiannidev) [reply src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/BlockEditorVarianceHandler.cs:205]: thanks for your feedback.
I fixed this

**Comment by kiannidev** [comment]
> Looks good @kiannidev, and I can see the at least potential issues you've found, and the fixes to resolve them.
> 
> Please could you look at my inline comments and also move the specific tests - and only those tests - that verify these fixes into this PR (so we have the fix with the test code as part of a single commit)? The tests should fail before the fix and pass after. Thanks.

Hi, @AndyButland 
I added tests to verify the bug fix.
please review it again

Thanks

**Review by AndyButland — APPROVED** [review]
Looks good to me now, thanks @kiannidev.
