### PR TITLE
Fix media tracking of items added via macro parameters in RTE and Grid 

### LINKED ISSUE #8131: Media Tracking - Media isn't tracked as being 'in use' if picked in a Macro Parameter
Quite often a Macro is used to allow an editor to pick a selection of media files, and then the selection is written out in a nice list, with some custom HTML, eg icons representing the file types and the size of the file to download...

This is a big time saver for editors, and also gives you central consistent control over the markup used for these lists.

image

image

The macro would have a multiple media picker as a parameter - and allow either a 'folder' to be picked or individual media items.

I wouldn't necessarily expect media to be tracked if a 'folder' has been picked, something would need to be done with the paths and that seems a bit niche..

.. but I would expect (hope) individual media items 'picked' in a macro parameter multi media picker would be registered and tracked as being 'in use'?

image

Using Umbraco 8.6.1

To replicate create a new Macro called Insert Files - Give it a Macro Parameter of Multiple Media Picker... allow it to be used in Rich Text Area and the grid.

image

Visit a page, with a Rich Text Area, on it, insert the macro and pick some media files...

save and publish

visit the media item in the back office ... no media references tracked :-( 

so and editor cannot be super confident whether something actually is or is not used...

---
_This item has been added to our backlog [AB#6755](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/6755)_

### PR DESCRIPTION
**Pull request by elit0451**
## Details

Fixes #8131 for Umbraco 9

After adding the [item tracking improvements](https://github.com/umbraco/Umbraco-CMS/pull/11919), there was still the issue that media items were not tracked when added via macro parameters in Rich Text Editor and Grid layout. @marcemarc had made a [PR](https://github.com/umbraco/Umbraco-CMS/pull/8614) for Umbraco 8 resolving the issue (🎉 H5YR! 💪 ) and this is the fix for Umbraco 9. 

## Test
- Have the SK installed
  - Create a Partial View Macro File called `InsertFiles.cshtml` ( ❗ _Note: code below_)
  - Allow the macro with the same name to be used in Rich Text Editor and the Grid
  - Add a macro parameter (ex: `Files (files) :  Umbraco.MultipleMediaPicker`)
  - In a **Rich Text area** on a content node, insert the macro and pick a media item as the macro param
    - It should result in the following: 
image

  - Save and Publish
  - View the media item in the backoffice, and you should see that this is now referenced from this page
    - If you pick a folder from the Media section, all its contents will be listed in the macro, but the reference is made to the folder itself and therefore can be found on the folder's info app
  - You can do the same thing with the **Grid**
      - Either pick a Macro directly
      - Or add a RTE in a Grid and reference the macro from there 

---
Contents of `InsertFiles.cshtml`: 
```cshtml
@inherits Umbraco.Cms.Web.Common.Macros.PartialViewMacroPage
@using Umbraco.Cms.Core.Models.PublishedContent
@using Umbraco.Cms.Core
@using Umbraco.Cms.Core.Routing
@using Umbraco.Extensions

@inject IPublishedContentQuery PublishedContentQuery
@inject IVariationContextAccessor VariationContextAccessor
@inject IPublishedUrlProvider PublishedUrlProvider


@{ var mediaIds = Model?.MacroParameters["files"] as string; }

@if (mediaIds != null)
{
    <div class="row">
        @foreach (var mediaId in mediaIds.Split(','))
        {
            var media = PublishedContentQuery.Media(mediaId);

            @* a single image *@
            if (!media.IsDocumentType("Folder"))
            {
                <div class="col-xs-6 col-md-3">
                    <a href="@media.Url(PublishedUrlProvider)" class="thumbnail">@media.Name</a> [@System.IO.Path.GetExtension(@media.Url(PublishedUrlProvider).ToString()).Substring(1)]
                </div>
            }

            @* a folder with images under it *@
            foreach (var image in media.Children(VariationContextAccessor))
            {
                <div class="col-xs-6 col-md-3">
                    <a href="@image.Url(PublishedUrlProvider)" class="thumbnail">@image.Name</a> [@System.IO.Path.GetExtension(@image.Url(PublishedUrlProvider).ToString()).Substring(1)]
                </div>
            }
        }
    </div>
} 
```

### CODE REVIEW

File: src/Umbraco.Infrastructure/Services/Implement/MacroService.cs [hunk 1]
```diff
@@ -61,6 +64,20 @@ public IEnumerable<IMacro> GetAll(params Guid[] ids)
             }
         }
 
+        public IEnumerable<IMacro> GetAll(params string[] aliases)
+        {
+            if (_macroRepository is not IMacroWithAliasRepository macroWithAliasRepository)
+            {
+                var hashset = new HashSet<string>(aliases);
+                return GetAll().Where(x=> hashset.Contains(x.Alias));
```
Comment (Zeegaan) [inline src/Umbraco.Infrastructure/Services/Implement/MacroService.cs:72]:
```suggestion
                return GetAll().Where(x => hashset.Contains(x.Alias));
```

File: src/Umbraco.Infrastructure/Templates/HtmlMacroParameterParser.cs [hunk 2]
```diff
@@ -0,0 +1,155 @@
...
+        public IEnumerable<UmbracoEntityReference> FindUmbracoEntityReferencesFromGridControlMacros(IEnumerable<GridValue.GridControl> macroGridControls)
+        {
+            var foundMacros = new List<Tuple<string, Dictionary<string, string>>>();
+
+            foreach (var macroGridControl in macroGridControls)
+            {
+                // Deserialise JSON of Macro Grid Control to a class
+                var gridMacro = macroGridControl.Value.ToObject<GridMacro>();
+                // Collect any macro parameters that contain the media udi format
+                if (gridMacro != null && gridMacro.MacroParameters != null && gridMacro.MacroParameters.Any())
```
Comment (Zeegaan) [inline src/Umbraco.Infrastructure/Templates/HtmlMacroParameterParser.cs:61]:
```suggestion
                if (gridMacro is not null && gridMacro.MacroParameters is not null && gridMacro.MacroParameters.Any())
```

File: src/Umbraco.Infrastructure/Templates/HtmlMacroParameterParser.cs [hunk 3]
```diff
@@ -0,0 +1,155 @@
...
+            foreach (var macro in macros)
+            {
+                var macroConfig = macroConfigs.FirstOrDefault(f => f.Alias == macro.Item1);
+                if (macroConfig is null)
+                {
+                    continue;
+                }
+                foundMacroUmbracoEntityReferences.Add(new UmbracoEntityReference(Udi.Create(Constants.UdiEntityType.Macro, macroConfig.Key)));
+                // Only do this if the macros actually have parameters
+                if (macroConfig.Properties != null && macroConfig.Properties.Keys.Any(f => f != "macroAlias"))
```
Comment (Zeegaan) [inline src/Umbraco.Infrastructure/Templates/HtmlMacroParameterParser.cs:97]:
```suggestion
                if (macroConfig.Properties is not null && macroConfig.Properties.Keys.Any(f => f != "macroAlias"))
```

File: src/Umbraco.Infrastructure/Templates/HtmlMacroParameterParser.cs [hunk 4]
```diff
@@ -0,0 +1,155 @@
...
+        {
+            var foundUmbracoEntityReferences = new List<UmbracoEntityReference>();
+            foreach (var parameter in macroConfig.Properties)
+            {
+                if (macroParameters.TryGetValue(parameter.Alias, out string parameterValue))
+                {
+                    var parameterEditorAlias = parameter.EditorAlias;
+                    // Lookup propertyEditor from the registered ParameterEditors with the implmementation to avoid looking up for each parameter
+                    var parameterEditor = parameterEditors.FirstOrDefault(f => string.Equals(f.Alias, parameterEditorAlias, StringComparison.OrdinalIgnoreCase));
+                    if (parameterEditor != null)
```
Comment (Zeegaan) [inline src/Umbraco.Infrastructure/Templates/HtmlMacroParameterParser.cs:124]:
```suggestion
                    if (parameterEditor is not null)
```

File: src/Umbraco.Infrastructure/Persistence/Repositories/Implement/MacroRepository.cs [hunk 5]
```diff
@@ -68,6 +70,38 @@ public bool Exists(Guid id)
...
         }
 
+        public IMacro GetByAlias(string alias)
+        {
+            return _macroByAliasCachePolicy.Get(alias, PerformGetByAlias, PerformGetAllByAlias);
+        }
+
+        public IEnumerable<IMacro> GetAllByAlias(string[] aliases)
+        {
+            if (aliases.Any() == false)
```
Comment (Zeegaan) [inline src/Umbraco.Infrastructure/Persistence/Repositories/Implement/MacroRepository.cs:80]:
```suggestion
            if (aliases.Any() is false)
```

File: src/Umbraco.Infrastructure/Persistence/Repositories/Implement/MacroRepository.cs [hunk 6]
```diff
@@ -68,6 +70,38 @@ public bool Exists(Guid id)
...
+
+        private IMacro PerformGetByAlias(string alias)
+        {
+            var query = Query<IMacro>().Where(x => x.Alias.Equals(alias));
+            return PerformGetByQuery(query).FirstOrDefault();
+        }
+
+        private IEnumerable<IMacro> PerformGetAllByAlias(params string[] aliases)
+        {
+            if (aliases.Any() == false)
```
Comment (Zeegaan) [inline src/Umbraco.Infrastructure/Persistence/Repositories/Implement/MacroRepository.cs:96]:
```suggestion
            if (aliases.Any() is false)
```

**Review by Zeegaan — CHANGES_REQUESTED** [review]
Pattern matching is the new hotness 🔥

**Comment by Zeegaan** [comment]
Great job! I've fixed up some of the small edge-cases but the rest LGTM! 👓

File: src/Umbraco.Infrastructure/Persistence/Repositories/Implement/MacroRepository.cs [hunk 7]
```diff
@@ -77,7 +77,7 @@ public IMacro GetByAlias(string alias)
 
         public IEnumerable<IMacro> GetAllByAlias(string[] aliases)
         {
-            if (aliases.Any() == false)
+            if (aliases.Any() is false)
             {
                 return base.GetMany();
             }
```
Comment (bjarnef) [inline src/Umbraco.Infrastructure/Persistence/Repositories/Implement/MacroRepository.cs:83]: @Zeegaan shouldn't it just use `Length` here since the aliases is `string[]`.

for example:

```
if (aliases?.Length == 0)
{
   
}
```

As far I know `Any()` check first item if collection, but with `Array`, `List`, `ICollection` etc,  `Length` or `Count` property already know the size of the collection.

Comment (Zeegaan) [reply src/Umbraco.Infrastructure/Persistence/Repositories/Implement/MacroRepository.cs:83]: Hey @bjarnef, thanks for your comment, i had to check how this works 👀  When it is an array, Any() will also use the Count property like this:
image
And because of that, i think its more readable if we use `Any()` instead of `Length`

**Comment by Zeegaan** [comment]
Cherry picked for 9.4

**Comment by marcemarc** [comment]
Thanks @elit0451 @Zeegaan !!!
