### PR TITLE
Attended Upgrades: Detect and display correct "from" version on the upgrade screen (closes #20980)

### LINKED ISSUE #20980: Upgrade screen shows wrong "detected" version
### Which Umbraco version are you using?

17.0.0

### Bug summary

The upgrade screen appears to show the wrong "detected version", where it shows the currently installed version, rather than the version detected from the database's `Umbraco.Core.Upgrader.State+Umbraco.Core` value.

Image

### Specifics

_No response_

### Steps to reproduce

- Create a v13 project using this script:
     - [Package Script Writer: v13.12.0 script](https://psw.codeshare.co.uk/?TemplateName=Umbraco.Templates&TemplateVersion=13.12.0&Packages=&UserEmail=admin%40example.com&ProjectName=13-12-0&CreateSolutionFile=false&SolutionName=13-12-0&UseUnattendedInstall=true&DatabaseType=SQLite&UserPassword=1234567890&UserFriendlyName=Administrator&IncludeStarterKit=false&IncludeDockerfile=false&IncludeDockerCompose=false&StarterKitPackage=clean+--version+4.1.0&OnelinerOutput=false&RemoveComments=false)
- Run it once to generate the database
- Create a v17 project using this script:
     - [Package Script Writer: v17.0.0 script](https://psw.codeshare.co.uk/?TemplateName=Umbraco.Templates&TemplateVersion=17.0.0&Packages=&UserEmail=admin%40example.com&ProjectName=17-0-0&CreateSolutionFile=false&SolutionName=17-0-0&UseUnattendedInstall=true&DatabaseType=SQLite&UserPassword=1234567890&UserFriendlyName=Administrator&IncludeStarterKit=false&IncludeDockerfile=false&IncludeDockerCompose=false&StarterKitPackage=clean+--version+4.1.0&OnelinerOutput=false&RemoveComments=false)
- Point the v17 project at the v13 database
- Run the project and observe the "Upgrading Umbraco" screen

### Expected result / actual result

**Expected Result**
I would've expected it to say:
```
Detected current version 13.5.0 ({CC47C751-A81B-489A-A2BC-0240245DB687}), which needs to be upgraded to 17.0.0+da502e0 ({1C38D589-26BB-4A46-9ABE-E4A0DF548A87}). 
```
As the Umbraco migration step GUID maps to the v13.5.0 update: https://github.com/umbraco/Umbraco-CMS/blob/f44e9328d7fdfe2bf3ad408ce045e43d6eeb606e/src/Umbraco.Infrastructure/Migrations/Upgrade/UmbracoPlan.cs#L66

**Actual Result**
But it actually just says the current installed version, even though that does not match the detected migration plan GUID.
```
Detected current version 17.0.0 ({CC47C751-A81B-489A-A2BC-0240245DB687}), which needs to be upgraded to 17.0.0+da502e0 ({1C38D589-26BB-4A46-9ABE-E4A0DF548A87}). 
```

**Thoughts**
I realise that not every minor/patch version has a matching migration plan step, so in my case, my database was actually from a v13.10.1 site, so maybe it would be better if it just stated the detected major version?

E.g:
```
Detected current version 13 ({CC47C751-A81B-489A-A2BC-0240245DB687}), which needs to be upgraded to 17.0.0+da502e0 ({1C38D589-26BB-4A46-9ABE-E4A0DF548A87}).
```

I just think that the current wording could be confusing to those who don't understand how Umbraco's migration plans work, or what the GUIDs shown actually mean.

**Edit:**
I just realised that this also causes the "View report" button to be useless, as it simply opens up a comparison page where it attempts to compare v17 to v17:
Image

### PR DESCRIPTION
**Pull request by AndyButland**
## Description

As reported in https://github.com/umbraco/Umbraco-CMS/issues/20980, when doing an attending upgrade, the the upgrade screen currently always displays the first version of the running major (e.g. **17.0.0**) as the "detected version", regardless of the actual database state. Upgrading from 17.2 → 17.3 showed "17.0.0"; upgrading from 13.5 → 17.x also showed "17.0.0".

This had been the case for a while, and was caused by `UpgradeSettingsFactory` constructing `OldVersion` from only `_umbracoVersion.SemanticVersion.Major`, ignoring the migration state entirely (a TODO acknowledged this).

The fix resolves the actual version by walking the `UmbracoPlan` transition chain and extracting version numbers from migration type namespaces (`V_{major}_{minor}_{patch}` convention).

It's based on a convention, but one that has been followed for all migration steps up to now, and there's no reason why it can't continue this way in the future.

### Automated tests (`UmbracoPlanTests`)

I've added automated tests to:

- Verify version resolution against the real `UmbracoPlan`:
- Verify and guard against future deviations from the naming convention the approach relies on.

```bash
dotnet test --filter "FullyQualifiedName~UmbracoPlanTests"
```

### Manual

1. Run the Web.UI project to create a database at the current version.
2. Set the migration state back to simulate an older version:

   **Simulate upgrading from 17.2:**
   ```sql
   UPDATE umbracoKeyValue
   SET [value] = '{A7B8C9D0-E1F2-4A5B-8C7D-9E0F1A2B3C4D}'
   WHERE [key] = 'Umbraco.Core.Upgrader.State+Umbraco.Core'
   ```

3. Restart the application, ensuring you have `UpgradeUnattended` set to `false` in configuration.
4. Verify the upgrade screen shows the correct detected version (**17.2.0**) instead of the old incorrect **17.0.0**

image

### CODE REVIEW

**Comment by simonech** [comment]
@AndyButland that was a fast fix 👍

File: src/Umbraco.Infrastructure/Migrations/Upgrade/UmbracoPlan.cs [hunk 1]
```diff
@@ -175,4 +180,53 @@ protected virtual void DefinePlan()
...
+    public SemVersion? GetVersionForState(string? state)
+    {
+        if (string.IsNullOrWhiteSpace(state))
+        {
+            return null;
+        }
+
+        // InitialState is the final migration state of 9.4 (lowest supported upgrade).
+        // TODO (V18): Update to the final migration state version of 17.4 when InitialState changes.
+        var initialVersion = new SemVersion(9, 4, 0);
```
Comment (Zeegaan) [inline src/Umbraco.Infrastructure/Migrations/Upgrade/UmbracoPlan.cs]: I think we should atleast have it as a private property, next to `InitialState`,
atleast then when we're updating one of them, we're less likely to forget the other 🤔

**Review by Zeegaan — CHANGES_REQUESTED** [review]
Overall looks and tests good, just 1 small thing 😁

File: src/Umbraco.Infrastructure/Migrations/Upgrade/UmbracoPlan.cs (hunk 1 above)
Comment (AndyButland) [reply src/Umbraco.Infrastructure/Migrations/Upgrade/UmbracoPlan.cs]: Good thinking, agreed.  I've made that update.

**Review by Zeegaan — APPROVED** [review]

File: src/Umbraco.Infrastructure/Migrations/Upgrade/UmbracoPlan.cs (hunk 1 above)
Comment (Zeegaan) [reply src/Umbraco.Infrastructure/Migrations/Upgrade/UmbracoPlan.cs]: Thank you 🙌
