### PR TITLE
Repositories: Use `FirstOrDefault` over `ExecuteScalar` for GUID and nullable types (closes #21448)

### LINKED ISSUE #21448: Use Database.FirstOrDefault instead of Database.ExecuteScalar
### Which Umbraco version are you using?

17.2.0-rc.preview

### Bug summary

Use `Database.FirstOrDefault` instead of `Database.ExecuteScalar`, because otherwise not all `ISqlSyntaxProvider` mappers get called.
This is documented inside NPoco.

### Specifics

_No response_

### Steps to reproduce

Some Integration tests will fail for new database providers e.g. for PostgreSQL 

### Expected result / actual result

_No response_

### PR DESCRIPTION
**Pull request by idseefeld**
All test should succeed.
See #21448 for details.

### Essentials:
Use `Database.FirstOrDefault` instead of `Database.ExecuteScalar`, because otherwise not all `ISqlSyntaxProvider` mappers get called.
This is documented inside _NPoco_.

PR #21447 should be merged before.

### CODE REVIEW

File: src/Umbraco.Infrastructure/Services/Implement/UserIdKeyResolver.cs [hunk 1]
```diff
@@ -121,7 +120,7 @@ public async Task<Attempt<Guid>> TryGetAsync(int id)
                 .From<UserDto>()
                 .Where<UserDto>(x => x.Id == id);
 
-            Guid? fetchedKey = scope.Database.ExecuteScalar<Guid?>(query);
+            Guid? fetchedKey = scope.Database.FirstOrDefault<Guid?>(query);
```
[the remark this answers is not in the document]
Comment (idseefeld) [reply src/Umbraco.Infrastructure/Services/Implement/UserIdKeyResolver.cs:125]: Ok

**Comment by AndyButland** [comment]
This looks OK to me Dirk, but I might look at just making sure these methods are covered by integration tests.  "All test should succeed" looks fine, but it could be these aren't part of coverage.  I'll take a look.

Firstly though, you say:

> This is documented inside NPoco.

Do you have a link for this please?

---

I also see there are many other instance of ExecuteScalar in the code base.  Why do you find it necessary to update the ones you've done in this PR, and not the others?

File: src/Umbraco.Infrastructure/Persistence/Repositories/Implement/IdKeyMapRepository.cs
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/Repositories/Implement/IdKeyMapRepository.cs:1]: There are two further instances of `ExecuteScalar` in this file - line 46 and 57.  Do they need updating too?

Comment (idseefeld) [reply src/Umbraco.Infrastructure/Persistence/Repositories/Implement/IdKeyMapRepository.cs:1]: @AndyButland The hint about `ExecuteScalar` was not in the Wiki, but in an answer from `schotime` within an issue:
https://github.com/schotime/NPoco/issues/653
Btw. Matt Brailsford has created a PR (still open) for this. And I have also an open PR regarding case sensitivity for PostgreSQL and there are other about .Net10 support. So, I am happy that you will replace this not well maintained project with EFCore.

And yes, there are more instance of `ExecuteScalar` and I have not replaced them, because there are no issues in the integration tests for my PostgreSQL provider. My manual testing of the main areas in a real Umbraco instance using the PostgreSQL provider have no issues shown yet. 
May be the test coverage is not sufficient. 

I remember there have been issue with replaced `ExecuteScalar` instances, but it took some time to understand which mappers I need in my provider implementation. So, I am not sure all instance could or should be replaced.

What do you think how we should procceed?
Better test coverage would be good anyways and I'll way what you find out...

Comment (AndyButland) [reply src/Umbraco.Infrastructure/Persistence/Repositories/Implement/IdKeyMapRepository.cs:1]: OK, then probably it makes sense to update only where we know you need to.  It's not really clear to me though why this fails:

```
            ((UmbracoDomain)entity).LanguageIsoCode = Database.ExecuteScalar<string>(
                $"SELECT {QuoteColumnName("languageISOCode")} FROM {QuoteTableName(Constants.DatabaseSchema.Tables.Language)} WHERE id = @langId",
                new { langId = entity.LanguageId });
```

I read in the issue you linked that there are problems with mapping GUIDs, but this is a string.  Can you share the exception you get when this code runs please?

I think it'll be fine to make the updates you are suggesting here, but I just want to make sure first that I understand what we are fixing.

Comment (idseefeld) [reply src/Umbraco.Infrastructure/Persistence/Repositories/Implement/IdKeyMapRepository.cs:1]: I have reverted this particular replacement. Test do not fail for this anymore. 
Mappers for Guid, nullables `int?`, `long?` and `Guid?` still required the change to `.FirstOrDefault<T>()`

Comment (idseefeld) [reply src/Umbraco.Infrastructure/Persistence/Repositories/Implement/IdKeyMapRepository.cs:1]: I have again checked the other cases and one of the exception messages is `Object must implement IConvertible.` in file `UserIdKeyResolver.cs line 124: Guid? fetchedKey = scope.Database.ExecuteScalar<Guid?>(query);` 

A lot of the test log just fail with `System.NullReferenceException : Object reference not set to an instance of an object.` and you have to dig deeper into the client API calls.

File: src/Umbraco.Infrastructure/Persistence/Repositories/Implement/IdKeyMapRepository.cs [hunk 2]
```diff
@@ -85,7 +85,7 @@ public class IdKeyMapRepository(IScopeAccessor scopeAccessor) : IIdKeyMapReposit
                 .Select<NodeDto>(c => c.UniqueId)
                 .From<NodeDto>()
                 .Where<NodeDto>(n => n.NodeId == id);
-            return database?.ExecuteScalar<Guid?>(sql);
+            return database?.FirstOrDefault<Guid?>(sql);
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/Repositories/Implement/IdKeyMapRepository.cs:91]:
```suggestion
            // We must use FirstOrDefault over ExecuteScalar when retrieving a nullable Guid, to ensure we go through the full NPoco mapping pipeline.
            // Without that, though it will succeed on SQLite and SQLServer, it could fail on other database providers.
            return database?.FirstOrDefault<Guid?>(sql);
```

File: src/Umbraco.Infrastructure/Persistence/Repositories/Implement/IdKeyMapRepository.cs [hunk 3]
```diff
@@ -96,7 +96,7 @@ public class IdKeyMapRepository(IScopeAccessor scopeAccessor) : IIdKeyMapReposit
                 n.NodeId == id
                 && (n.NodeObjectType == type
                     || n.NodeObjectType == Constants.ObjectTypes.IdReservation));
-        return database?.ExecuteScalar<Guid?>(sql);
+        return database?.FirstOrDefault<Guid?>(sql);
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/Repositories/Implement/IdKeyMapRepository.cs:105]:
```suggestion
            // We must use FirstOrDefault over ExecuteScalar when retrieving a nullable Guid, to ensure we go through the full NPoco mapping pipeline.
            // Without that, though it will succeed on SQLite and SQLServer, it could fail on other database providers.
        return database?.FirstOrDefault<Guid?>(sql);
```

File: src/Umbraco.Infrastructure/Persistence/Repositories/Implement/NotificationsRepository.cs [hunk 4]
```diff
@@ -171,7 +171,7 @@ public bool TryCreateNotification(IUser user, IEntity entity, string action, [No
             .SelectDistinct<NodeDto>(c => c.NodeObjectType)
             .From<NodeDto>()
             .Where<NodeDto>(nodeDto => nodeDto.NodeId == entity.Id);
-        Guid nodeType = AmbientScope.Database.ExecuteScalar<Guid>(sql);
+        Guid nodeType = AmbientScope.Database.FirstOrDefault<Guid>(sql);
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/Repositories/Implement/NotificationsRepository.cs:177]:
```suggestion
            // We must use FirstOrDefault over ExecuteScalar when retrieving a Guid, to ensure we go through the full NPoco mapping pipeline.
            // Without that, though it will succeed on SQLite and SQLServer, it could fail on other database providers.
        Guid nodeType = AmbientScope.Database.FirstOrDefault<Guid>(sql);
```

File: src/Umbraco.Infrastructure/Persistence/UmbracoDatabaseExtensions.cs [hunk 5]
```diff
@@ -82,15 +82,15 @@ public static long Count(this IUmbracoDatabase database, Sql sql)
         // We need to copy the sql into a new object, to avoid this method from changing the sql.
         var query = new Sql().Select("COUNT(*)").From().Append("(").Append(new Sql(sql.SQL, sql.Arguments)).Append(") as count_query");
 
-        return database.ExecuteScalar<long>(query);
+        return database.FirstOrDefault<long>(query);
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/UmbracoDatabaseExtensions.cs]:
```suggestion
            // We must use FirstOrDefault over ExecuteScalar when retrieving a long, to ensure we go through the full NPoco mapping pipeline.
            // Without that, though it will succeed on SQLite and SQLServer, it could fail on other database providers.
        return database.FirstOrDefault<long>(query);
```

File: src/Umbraco.Infrastructure/Persistence/UmbracoDatabaseExtensions.cs [hunk 6]
```diff
@@ -82,15 +82,15 @@ public static long Count(this IUmbracoDatabase database, Sql sql)
...
     }
 
     public static async Task<long> CountAsync(this IUmbracoDatabase database, Sql sql)
     {
         // We need to copy the sql into a new object, to avoid this method from changing the sql.
         Sql query = new Sql().Select("COUNT(*)").From().Append("(").Append(new Sql(sql.SQL, sql.Arguments)).Append(") as count_query");
 
-        return await database.ExecuteScalarAsync<long>(query);
+        return await database.FirstOrDefaultAsync<long>(query);
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/UmbracoDatabaseExtensions.cs]:
```suggestion
            // We must use FirstOrDefaultAsync over ExecuteScalarAsync when retrieving a nullable Guid, to ensure we go through the full NPoco mapping pipeline.
            // Without that, though it will succeed on SQLite and SQLServer, it could fail on other database providers.
        return await database.FirstOrDefaultAsync<long>(query);
```

File: src/Umbraco.Infrastructure/Services/Implement/UserIdKeyResolver.cs [hunk 7]
```diff
@@ -69,13 +69,12 @@ public async Task<Attempt<int>> TryGetAsync(Guid key)
                 .From<UserDto>()
                 .Where<UserDto>(x => x.Key == key);
 
-            int? fetchedId = await scope.Database.ExecuteScalarAsync<int?>(query);
+            int? fetchedId = await scope.Database.FirstOrDefaultAsync<int?>(query);
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Services/Implement/UserIdKeyResolver.cs]:
```suggestion
            // We must use FirstOrDefault over ExecuteScalar when retrieving a nullable int, to ensure we go through the full NPoco mapping pipeline.
            // Without that, though it will succeed on SQLite and SQLServer, it could fail on other database providers.
            int? fetchedId = await scope.Database.FirstOrDefaultAsync<int?>(query);
```

File: src/Umbraco.Infrastructure/Services/Implement/UserIdKeyResolver.cs (hunk 1 above)
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Services/Implement/UserIdKeyResolver.cs:125]:
```suggestion
            // We must use FirstOrDefault over ExecuteScalar when retrieving a nullable Guid, to ensure we go through the full NPoco mapping pipeline.
            // Without that, though it will succeed on SQLite and SQLServer, it could fail on other database providers.
            Guid? fetchedKey = scope.Database.FirstOrDefault<Guid?>(query);
```

File: src/Umbraco.Infrastructure/Persistence/UmbracoDatabaseExtensions.cs (hunk 5 above)
Comment (idseefeld) [reply src/Umbraco.Infrastructure/Persistence/UmbracoDatabaseExtensions.cs]: Double checked and turned out to be unnecessary. So I reverted the change.

File: src/Umbraco.Infrastructure/Persistence/UmbracoDatabaseExtensions.cs (hunk 6 above)
Comment (idseefeld) [reply src/Umbraco.Infrastructure/Persistence/UmbracoDatabaseExtensions.cs]: Double checked and turned out to be unnecessary. So I reverted the change.

File: src/Umbraco.Infrastructure/Services/Implement/UserIdKeyResolver.cs (hunk 7 above)
Comment (idseefeld) [reply src/Umbraco.Infrastructure/Services/Implement/UserIdKeyResolver.cs]: reverted

**Comment by idseefeld** [comment]
All integration test have been successful. But testing manually my setup, an exception occurs.
So, I have to investigate this before we can merge... 😥

**Comment by idseefeld** [comment]
It was an concurrency conflict and had nothing to do with this issue.
