### PR TITLE
Relations: Exclude the relate parent on delete relation type from checks for related documents and media on delete, when disable delete with references is enabled (closes #20803)

### LINKED ISSUE #20803: Unable to delete nodes when "DisableDeleteWhenReferenced" set to true
### Which Umbraco version are you using?

16.2.0

### Bug summary

When [DisableDeleteWhenReferenced](https://docs.umbraco.com/umbraco-cms/reference/configuration/contentsettings#disable-delete-when-referenced) is set to `true` you are unable to delete anything from the recycle bin because of the "Relate Parent Document On Delete" relation created when the node is deleted. This also affects media.

https://github.com/user-attachments/assets/fa02680e-5d4f-4428-aec9-aced3d35c482

### Specifics

When deleting a node, the ContentEditingServiceBase calls the RelationService which checks if there is any relation and cancels the delete.

[v13](https://github.com/umbraco/Umbraco-CMS/blob/23b09b1a7ec930491867a758f1026da14e3bb5c8/src/Umbraco.Core/Services/RelationService.cs#L415), [v16](https://github.com/umbraco/Umbraco-CMS/blob/4e74dbf218555e55227065500108e916a5a1787f/src/Umbraco.Core/Services/RelationService.cs#L445) and [v17](https://github.com/umbraco/Umbraco-CMS/blob/c60cf90ffe5c2dd005b75a7302e56b750e3e39b0/src/Umbraco.Core/Services/RelationService.cs#L492) all work the same way.

### Steps to reproduce

1. Create a fresh install of Umbraco 16.2.0 (I expect the same results for 13 -> 17)
2. Create a new document type, allow at root and allow it as a child
3. Create a "Parent" page at the root
4. Create a "Child" page under the parent
5. Delete the "Child" page
6. Try to delete the "Child" page from the recycle bin and the event will be cancelled due to the "relate to parent on delete "relation
7. Inspect the Relation Viewer and you will see the only relation is between the parent/child on delete

### Expected result / actual result

Expected result: If I delete a node I should be able to delete it from the recycle bin
Actual result: Deleting a node does not allow me to delete it from the recycle bin

If `DisableDeleteWhenReferenced` is `true` then perhaps there needs to be a check on the relation types as well, as if the only relation is an "on delete" relation then I should still be able to delete it from the recycle bin. It doesn't look like the RelationService uses the "IsDependency" property so perhaps that can be leveraged in some way.

### PR DESCRIPTION
**Pull request by AndyButland**
### Prerequisites

- [X] I have added steps to test this contribution in the description below

Fixes: https://github.com/umbraco/Umbraco-CMS/issues/20803

### Description
As the [linked issue](https://github.com/umbraco/Umbraco-CMS/issues/20803) shows, when the following configuration is in place, the relation that's made when a document or media item is moved to the recycle bin prevents the deletion of the item from the recycle bin.

```
  "Umbraco": {
    "CMS": {
      "Content": {
        "DisableDeleteWhenReferenced": true,
```

That shouldn't be the case, and relations of this type should be excluded from the check.

This PR makes that amend.

### Testing
See reproduction steps on the linked issue.  With this PR in place, you'll be able to delete the document or media item from the recycle bin.

### CODE REVIEW

File: src/Umbraco.Infrastructure/Persistence/Querying/Query.cs [hunk 1]
```diff
@@ -49,6 +49,22 @@ public virtual IQuery<T> WhereIn(Expression<Func<T, object>>? fieldSelector, IEn
         return this;
     }
 
+    /// <summary>
+    ///     Adds a where-not-in clause to the query.
+    /// </summary>
+    public virtual IQuery<T> WhereNotIn(Expression<Func<T, object>>? fieldSelector, IEnumerable? values)
+    {
+        if (fieldSelector == null)
```
Comment (Zeegaan) [inline src/Umbraco.Infrastructure/Persistence/Querying/Query.cs]:
```suggestion
        if (fieldSelector is null)
```

File: src/Umbraco.Core/Services/IRelationService.cs [hunk 2]
```diff
@@ -297,9 +297,21 @@ public interface IRelationService : IService
     /// </summary>
     /// <param name="id">Id of an object to check relations for</param>
     /// <param name="directionFilter">Indicates whether to check for relations as parent, child or in either direction.</param>
-    /// <returns>Returns <c>True</c> if any relations exists with the given Id, otherwise <c>False</c></returns>
+    /// <returns>Returns <c>True</c> if any relations exists with the given Id, otherwise <c>False</c>.</returns>
     bool IsRelated(int id, RelationDirectionFilter directionFilter);
```
Comment (Zeegaan) [inline src/Umbraco.Core/Services/IRelationService.cs:302]: I guess we could obsolete this, or add a comment to remove in a major, as it will only be binary breaking 🤔

File: src/Umbraco.Infrastructure/Persistence/Querying/Query.cs (hunk 1 above)
Comment (AndyButland) [reply src/Umbraco.Infrastructure/Persistence/Querying/Query.cs]: Have applied here and the other instances in the `Query.cs` file.

File: src/Umbraco.Core/Services/IRelationService.cs (hunk 2 above)
Comment (AndyButland) [reply src/Umbraco.Core/Services/IRelationService.cs:302]: I've marked as obsolete and for removal in 18.  As you say, now we have the overload it's not going to need any changes for anyone using this method other than recompiling.

**Review by Zeegaan — APPROVED** [review]
Looks good now 🚀
