### PR TITLE
Last Synced: Adding A File System Approach to Subscriber Servers

### LINKED ISSUE #21783: Subscriber servers - Read-only database access does not work
### Which Umbraco version are you using?

17.1.0 and 17.2.0-rc

### Bug summary

When running Umbraco as a Subscriber with a read only database, the application is throwing errors that it cannot write to the database and stops functioning.

```
[07:42:32 WRN] Last synced Id found 0 but was not found in the database. This generally means this server/install  has been idle for too long and the instructions in the database have been pruned. A cold boot will be triggered.
[07:42:32 ERR] Exception (23096368).
Microsoft.Data.SqlClient.SqlException (0x80131904): Failed to update database "UmbracoTest" because the database is read-only.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, SqlCommand command, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)Unhandled exception. Microsoft.Data.SqlClient.SqlException (0x80131904): Failed to update database "UmbracoTest" because the database is read-only.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, SqlCommand command, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteNonQuery() in C:\projects\dotnet\src\MiniProfiler.Shared\Data\ProfiledDbCommand.cs:line 263
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.<ExecuteNonQuery>b__32_0()
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.<>c__DisplayClass38_0`1.<Execute>b__0()
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.Execute[T](Func`1 f)
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.ExecuteNonQuery()
   at NPoco.Database.<>c__DisplayClass338_0.<ExecuteNonQueryHelper>b__0()
   at NPoco.Database.ExecutionHook[T](Func`1 action)
   at NPoco.Database.ExecuteNonQueryHelper(DbCommand cmd)
   at NPoco.Database.Execute(String sql, CommandType commandType, Object[] args)
   at NPoco.Database.Execute(Sql Sql)
   at NPoco.Database.Execute(String sql, Object[] args)
   at NPoco.Database.Update[T](String sql, Object[] args)
   at Umbraco.Extensions.NPocoDatabaseExtensions.InsertOrUpdateAsync[T](IUmbracoDatabase db, T poco, String updateCommand, Object updateArgs)
   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.LastSyncedRepository.SaveExternalIdAsync(Int32 id)
   at Umbraco.Cms.Core.Sync.LastSyncedManager.SaveLastSyncedExternalAsync(Int32 id)
   at Umbraco.Cms.Infrastructure.Sync.DatabaseServerMessenger.InitializeColdBootState()
   at Umbraco.Cms.Infrastructure.Sync.DatabaseServerMessenger.InitializeWithMainDom()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Umbraco.Cms.Infrastructure.Sync.DatabaseServerMessenger.EnsureInitialized()
   at Umbraco.Cms.Infrastructure.Sync.DatabaseServerMessenger.Sync()
   at Umbraco.Cms.Core.Cache.DatabaseServerMessengerNotificationHandler.Handle(UmbracoApplicationStartingNotification notification)
   at Umbraco.Cms.Core.Events.INotificationHandler`1.Handle(IEnumerable`1 notifications)
   at Umbraco.Cms.Core.Events.NotificationHandlerWrapperImpl`1.<>c__DisplayClass0_0`2.<Handle>b__2(IEnumerable`1 handlerNotifications)
   at Umbraco.Cms.Core.Events.EventAggregator.PublishCore[TNotification](IEnumerable`1 allHandlers, IEnumerable`1 notifications)
   at Umbraco.Cms.Core.Events.NotificationHandlerWrapperImpl`1.Handle[TNotification,TNotificationHandler](IEnumerable`1 notifications, ServiceFactory serviceFactory, Action`2 publish)
   at Umbraco.Cms.Core.Events.EventAggregator.PublishNotifications[TNotification,TNotificationHandler](IEnumerable`1 notifications)
   at Umbraco.Cms.Core.Events.EventAggregator.PublishAsync[TNotification,TNotificationHandler](IEnumerable`1 notifications, CancellationToken cancellationToken)
   at Umbraco.Cms.Core.Events.EventAggregator.PublishAsync[TNotification](TNotification notification, CancellationToken cancellationToken)
   at Umbraco.Cms.Infrastructure.Runtime.CoreRuntime.StartAsync(CancellationToken cancellationToken, Boolean isRestarting)
   at Umbraco.Cms.Infrastructure.Runtime.CoreRuntime.StartAsync(CancellationToken cancellationToken)
   at Umbraco.Extensions.WebApplicationExtensions.BootUmbracoAsync(WebApplication app)
   at Program.<Main>$(String[] args) in C:\data\temp\UmbracoTest\Program.cs:line 18
   at Program.<Main>(String[] args)
ClientConnectionId:8440e4e7-6ea0-4b39-99d9-6551ff08a901
Error Number:3906,State:1,Class:16

   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteNonQuery() in C:\projects\dotnet\src\MiniProfiler.Shared\Data\ProfiledDbCommand.cs:line 263
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.<ExecuteNonQuery>b__32_0()
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.<>c__DisplayClass38_0`1.<Execute>b__0()
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.Execute[T](Func`1 f)
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.ExecuteNonQuery()
   at NPoco.Database.<>c__DisplayClass338_0.<ExecuteNonQueryHelper>b__0()
   at NPoco.Database.ExecutionHook[T](Func`1 action)
   at NPoco.Database.ExecuteNonQueryHelper(DbCommand cmd)
   at NPoco.Database.Execute(String sql, CommandType commandType, Object[] args)
ClientConnectionId:8440e4e7-6ea0-4b39-99d9-6551ff08a901
Error Number:3906,State:1,Class:16
[07:42:32 DBG] At:
   at System.Environment.get_StackTrace()
   at Umbraco.Cms.Infrastructure.Persistence.UmbracoDatabase.OnException(Exception ex)
   at NPoco.Database.OnExceptionInternal(Exception exception)
   at NPoco.Database.Execute(String sql, CommandType commandType, Object[] args)
   at NPoco.Database.Execute(Sql Sql)
   at NPoco.Database.Execute(String sql, Object[] args)
   at NPoco.Database.Update[T](String sql, Object[] args)
   at Umbraco.Extensions.NPocoDatabaseExtensions.InsertOrUpdateAsync[T](IUmbracoDatabase db, T poco, String updateCommand, Object updateArgs)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Umbraco.Extensions.NPocoDatabaseExtensions.InsertOrUpdateAsync[T](IUmbracoDatabase db, T poco, String updateCommand, Object updateArgs)
   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.LastSyncedRepository.SaveExternalIdAsync(Int32 id)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.LastSyncedRepository.SaveExternalIdAsync(Int32 id)
   at Umbraco.Cms.Core.Sync.LastSyncedManager.SaveLastSyncedExternalAsync(Int32 id)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Umbraco.Cms.Core.Sync.LastSyncedManager.SaveLastSyncedExternalAsync(Int32 id)
   at Umbraco.Cms.Infrastructure.Sync.DatabaseServerMessenger.InitializeColdBootState()
   at Umbraco.Cms.Infrastructure.Sync.DatabaseServerMessenger.InitializeWithMainDom()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Umbraco.Cms.Infrastructure.Sync.DatabaseServerMessenger.EnsureInitialized()
   at Umbraco.Cms.Infrastructure.Sync.DatabaseServerMessenger.Sync()
   at Umbraco.Cms.Core.Cache.DatabaseServerMessengerNotificationHandler.Handle(UmbracoApplicationStartingNotification notification)
   at Umbraco.Cms.Core.Events.INotificationHandler`1.Handle(IEnumerable`1 notifications)
   at Umbraco.Cms.Core.Events.NotificationHandlerWrapperImpl`1.<>c__DisplayClass0_0`2.<Handle>b__2(IEnumerable`1 handlerNotifications)
   at Umbraco.Cms.Core.Events.EventAggregator.PublishCore[TNotification](IEnumerable`1 allHandlers, IEnumerable`1 notifications)
   at Umbraco.Cms.Core.Events.NotificationHandlerWrapperImpl`1.Handle[TNotification,TNotificationHandler](IEnumerable`1 notifications, ServiceFactory serviceFactory, Action`2 publish)
   at Umbraco.Cms.Core.Events.EventAggregator.PublishNotifications[TNotification,TNotificationHandler](IEnumerable`1 notifications)
   at Umbraco.Cms.Core.Events.EventAggregator.PublishAsync[TNotification,TNotificationHandler](IEnumerable`1 notifications, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Umbraco.Cms.Core.Events.EventAggregator.PublishAsync[TNotification,TNotificationHandler](IEnumerable`1 notifications, CancellationToken cancellationToken)
   at Umbraco.Cms.Core.Events.EventAggregator.PublishAsync[TNotification](TNotification notification, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Umbraco.Cms.Core.Events.EventAggregator.PublishAsync[TNotification](TNotification notification, CancellationToken cancellationToken)
   at Umbraco.Cms.Infrastructure.Runtime.CoreRuntime.StartAsync(CancellationToken cancellationToken, Boolean isRestarting)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Umbraco.Cms.Infrastructure.Runtime.CoreRuntime.StartAsync(CancellationToken cancellationToken, Boolean isRestarting)
   at Umbraco.Cms.Infrastructure.Runtime.CoreRuntime.StartAsync(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Umbraco.Cms.Infrastructure.Runtime.CoreRuntime.StartAsync(CancellationToken cancellationToken)
   at Umbraco.Extensions.WebApplicationExtensions.BootUmbracoAsync(WebApplication app)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Umbraco.Extensions.WebApplicationExtensions.BootUmbracoAsync(WebApplication app)
   at Program.<Main>$(String[] args) in C:\data\temp\UmbracoTest\Program.cs:line 18
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Program.<Main>$(String[] args)
   at Program.<Main>(String[] args)
[07:42:32 DBG] Sql:
UPDATE [umbracoLastSynced] SET lastSyncedExternalId=@0, lastSyncedDate=@1 WHERE machineId=@2
 -- @0:2 @1:17/02/2026 07:42:32 @2:MAARTEN-LENOVO
```

This seems to be introduced in https://github.com/umbraco/Umbraco-CMS/pull/19884 where the use of the FileProvider was deprecated in favor of the DatabaseServerMessenger.

### Specifics

_No response_

### Steps to reproduce

- Create an empty Umbraco Project using ```dotnet new umbraco -n MyCustomUmbracoProject```
- Start the project and make sure you select SQL Server as a database
- Finish the installation process and login
- Terminate the application
- Add the code to promote the instance to Subscriber as specified in the docs (https://docs.umbraco.com/umbraco-cms/fundamentals/setup/server-setup/load-balancing/flexible-advanced#explicit-schedulingpublisher-server)
- Set the database to read-only (ALTER DATABASE [YOURDB] SET READ_ONLY WITH NO_WAIT)
- Start the application and notice the errors.

### Expected result / actual result

The application should run without errors and should not require write access to the database.

---
_This item has been added to our backlog AB#65331_

### PR DESCRIPTION
**Pull request by NillasKA**
Closes #21783

### Description
An issue was reported with the recent changes to the way we save the Last Synced ID. Subscriber (read-only) servers cannot write to the database, so with the changes we had made for V17, subscriber servers would not be able to save the ID.

This PR aims to fix that, by re-implementing a file system approach, that will allow subscriber servers to read and write to a file, rather than the database, to save and retrieve the internal and external ID. Our previous file system approach, before we implemented the database approach in V17, did not have an internal and external last synced ID, this new file system approach creates and reads from two files, to support both an internal and external id. One file for each.

### The Automatic Approach
I was torn between two approaches. One that resolves to the file system repository automatically, based on the server role, and another that required a manual overwrite of the dependency injection. I decided to do the automatic approach.

This resulted in a new `ServerRoleAwareLastSyncedRepository.cs` class being created, that acts as a delegator. This class will check which server role is assigned, and then delegates the given task to the correct repository. The reason it has to be done this way, is that services are registered before the server role is assigned. 

This approach forces a lazy injection of the IServerRoleAccessor, otherwise circular dependencies would cause a deadlock.

### Testing
I have written unit tests to ensure the new `FileSystemLastSyncedRepository.cs` works.

For manually testing we need to test both the Subscriber angle, and the regular angle:

**Subscriber Testing**
1. Create an overwrite of the `IServerRoleAccessor`. I have pasted a composer below you could use.
2. Launch Umbraco and start performing actions
3. Ensure that two txt files are created in `Umbraco.Web.UI/umbraco/Data/TEMP/DistCache`
4. Ensure that the txt files contain the latest IDs

Heres the composer:
```
public class SubscriberTestComposer : IComposer
  {
      public void Compose(IUmbracoBuilder builder)
      {
          builder.Services.AddSingleton<IServerRoleAccessor>(
              new SingleServerRoleAccessorOverride());
      }
  }

  public class SingleServerRoleAccessorOverride : IServerRoleAccessor
  {
      public ServerRole CurrentServerRole => ServerRole.Subscriber;
  }
```

**Regular Testing**
1. Without the overwriting composer, launch the application.
2. Start performing some actions, create document types etc.
3. Open the LastSynced database table.
4. Ensure that the database gets updated with the recent LastSyncedIDs

### CODE REVIEW

File: src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ServerRoleAwareLastSyncedRepository.cs [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+
+/// <summary>
+/// A decorator around <see cref="ILastSyncedRepository"/> that delegates to either a database
+/// or file system repository based on the server role.
+/// </summary>
+/// <remarks>
+/// Subscriber servers cannot write to the database, so they use a file-system
+/// implementation instead. All other roles use the database implementation.
+/// </remarks>
+public class ServerRoleAwareLastSyncedRepository : ILastSyncedRepository
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ServerRoleAwareLastSyncedRepository.cs]: This looks a really nice approach, but we need to check something in case there's a flaw.  `LastSyncedManager` calls this after creating a scope, which isn't needed for the writing to file I believe.  The previous implementation using the file doesn't look like it did this - see [here](https://github.com/umbraco/Umbraco-CMS/blob/9517e7c621fb75c38877c0c6d5867eee04c829c2/src/Umbraco.Infrastructure/Sync/LastSyncedFileManager.cs).

If the scope is created and not used that's no big deal, but I'm concerned the scope creation itself might attempt to write to the database.  Maybe this is caught elsewhere and not a problem, but can you check if you make your database read-only that you definitely don't get an exception through trying to write to it please?

Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ServerRoleAwareLastSyncedRepository.cs]: Could be `internal sealed` and we make `public` only if it later proves necessary.

File: src/Umbraco.Infrastructure/Persistence/Repositories/Implement/FileSystemLastSyncedRepository.cs [hunk 2]
```diff
@@ -0,0 +1,132 @@
...
+using Umbraco.Cms.Core.Persistence.Repositories;
+using Umbraco.Extensions;
+
+namespace Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement;
+
+/// <summary>
+/// A file system based implementation of <see cref="ILastSyncedRepository"/> for use on
+/// subscriber servers that cannot write to the database.
+/// </summary>
+public class FileSystemLastSyncedRepository : ILastSyncedRepository
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/Repositories/Implement/FileSystemLastSyncedRepository.cs]: Could be `internal sealed` and we make `public` only if it later proves necessary.

File: src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ServerRoleAwareLastSyncedRepository.cs (hunk 1 above)
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ServerRoleAwareLastSyncedRepository.cs]: You could consider unit tests for this class.  It's not doing too much, but a unit test with a mocked `IServerRoleAccessor` returning `Subscriber` or `Single` would verify it delegates correctly.

**Review by AndyButland — CHANGES_REQUESTED** [review]
Looks good to me @NillasKA.  Main thing is if you can please confirm that when using this approach on a subscriber server, the database can be made read-only.

To set:

```sql
alter database current set read_only
```

Reset with:

```sql
alter database current set read_write
```

File: src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ServerRoleAwareLastSyncedRepository.cs (hunk 1 above)
Comment (NillasKA) [reply src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ServerRoleAwareLastSyncedRepository.cs]: So i just finished testing with a read-only database as suggested.

It throws no errors relevant to the Last Synced ID operations, just a good amount of distributed background jobs and one initial instance of OpenIdDict trying to write to the database. But nothing regarding Last Synced IDs.

Comment (AndyButland) [reply src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ServerRoleAwareLastSyncedRepository.cs]: Good to hear.  Then there's no problem here (at least with the approach in this PR).  I expect now we have lazy locks, we aren't going to hit the database unless we need to, and in this case, we don't.

**Review by AndyButland — COMMENTED** [review]
All looks good to me @NillasKA - thanks for this.  I've verified locally with the composer setup you provided and can confirm the older style approach to this of writing files to disk is restored for subscriber servers.

I have a final thought though - what if the subscriber database is not read-only?  Then there would be no need to fallback to the file based approach.  Would it be possible to use the discriminator to check if the database is read-only, and then only use the file based approach if it is?

You can likely query something in SQL Server to check for this, but it'll need an equivalent for SQLite too (or a fallback to assuming it's not read-only - as we wouldn't expect a significant setup using load balancing to not be using SQL Server).  Or you could do a test UPDATE statement and see if it fails.

We should avoid doing it on every check.  But given this is a fairly significant architectural choice, I would say it's OK to detect read-only on the first request and then cache the result in memory and use it for subsequent checks.

**Comment by NillasKA** [comment]
> All looks good to me @NillasKA - thanks for this. I've verified locally with the composer setup you provided and can confirm the older style approach to this of writing files to disk is restored for subscriber servers.
> 
> I have a final thought though - what if the subscriber database is not read-only? Then there would be no need to fallback to the file based approach. Would it be possible to use the discriminator to check if the database is read-only, and then only use the file based approach if it is?
> 
> You can likely query something in SQL Server to check for this, but it'll need an equivalent for SQLite too (or a fallback to assuming it's not read-only - as we wouldn't expect a significant setup using load balancing to not be using SQL Server). Or you could do a test UPDATE statement and see if it fails.
> 
> We should avoid doing it on every check. But given this is a fairly significant architectural choice, I would say it's OK to detect read-only on the first request and then cache the result in memory and use it for subsequent checks.

This could be done @AndyButland however this would require some sort of raw SQL. Given our current migration to EF Core and our wish to get rid of raw SQL wherever possible, this does seem like a step back to me. I might be wrong in my assumption, but isn't the purpose of a subscriber server to be read-only? So with that assumption, i think it's fine to disable this to be written to the database based on the server role. I think if we start differentiating if this is a read-only or read-write database, we might as well not have the server role check.

For SQLite, i agree with you that setups using a read-only database is most likely not using SQLite, therefore a default fallback to assuming a writeable database is fine. I think it would also be a hurdle to check if the SQLite database is read-only, since that is usually connection-based, I don't actually think you can lock a SQLite database down to be read-only, only specified connections, but i might be wrong.

**Comment by AndyButland** [comment]
> isn't the purpose of a subscriber server to be read-only?

No, this isn't necessarily true.  It's considered more of an advanced case (see docs [here](https://docs.umbraco.com/umbraco-cms/fundamentals/setup/server-setup/load-balancing/flexible-advanced#subscriber-servers-read-only-database-access)).

File: src/Umbraco.Infrastructure/Persistence/DatabaseReadOnlyAccessor.cs [hunk 3]
```diff
@@ -0,0 +1,54 @@
...
+        _appCaches.RuntimeCache.GetCacheItem(CacheKey, Check);
+
+    private bool Check()
+    {
+        try
+        {
+            IScope? scope = _scopeAccessor.AmbientScope;
+            if (scope is null)
+            {
+                return true;
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/DatabaseReadOnlyAccessor.cs]: I'd suggest throwing here.  It makes the requirements explicit (that we expect there to be an ambient scope), and means you don't have to arbitrarily guess at returning `true` or `false`.

```suggestion
                throw new InvalidOperationException(
                    "DatabaseReadOnlyAccessor requires an ambient scope.");
```

File: src/Umbraco.Infrastructure/Persistence/DatabaseReadOnlyAccessor.cs [hunk 4]
```diff
@@ -0,0 +1,54 @@
...
+            }
+
+            var result = scope.Database.ExecuteScalar<string>(
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/DatabaseReadOnlyAccessor.cs]: Just above here I'd suggest checking if we are working with SQL Server with:

```csharp
      if (scope.Database.DatabaseType.IsSqlServer() is false)
      {
          return false;
      }
```

Then you can remove the try/catch.  It's a little risky in that any exception will be caught here, not necessarily just the database check that you want.

File: src/Umbraco.Infrastructure/Persistence/DatabaseReadOnlyAccessor.cs [hunk 5]
```diff
@@ -0,0 +1,54 @@
...
+
+/// <summary>
+/// Checks whether the database is read-only by querying database.
+/// </summary>
+internal sealed class DatabaseReadOnlyAccessor : IDatabaseReadOnlyAccessor
+{
+    private const string CacheKey = "DatabaseReadOnly";
+
+    private readonly IScopeAccessor _scopeAccessor;
+    private readonly AppCaches _appCaches;
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/DatabaseReadOnlyAccessor.cs]: You probably don't need `AppCaches` here given we are just caching a boolean.  Instead something like:

```csharp
private bool? _isReadOnly;

public bool IsReadOnly()
    => _isReadOnly ??= Check();
```

**Review by AndyButland — CHANGES_REQUESTED** [review]
This looks a good approach to me @NillasKA.  Just a few tweaks I've left as suggestions.

**Review by AndyButland — APPROVED** [review]

**Review by nikolajlauridsen — APPROVED** [review]

**Comment by mwillebrands-caesar** [comment]
@NillasKA @AndyButland this checks if the full-database is readonly, but you can also have a specific user that might have only read-access to the database. Isn't it better to have a manual setting in the app settings that can force the instance to be in read-only database mode?

**Comment by AndyButland** [comment]
Might not be a bad idea @mwillebrands-caesar.  I'd also suggest though that you could register your own implementation of `IDatabaseReadOnlyAccessor` that implements `IsReadOnly` via whatever check makes most sense in your environment.  That might be a better approach that introducing another setting that could get out of sync with the actual database read-only status.
