### PR TITLE
Fixes RecurringHostServices leaking the execution context / ambient scope

### LINKED ISSUE #12022: Distributed Cache instructions not being processed
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.3.0

### Bug summary

Distributed Cache instructions not being processed.

### Specifics

`The Scope 79172c91-c5d3-4ff0-a35e-63db2d12bc09 being disposed is not the Ambient Scope 49df9006-f188-463c-98f2-2da0912d4235. This typically indicates that a child Scope was not disposed, or flowed to a child thread that was not awaited, or concurrent threads are accessing the same Scope (Ambient context) which is not supported. If using Task.Run (or similar) as a fire and forget tasks or to run threads in parallel you must suppress execution context flow with ExecutionContext.SuppressFlow() and ExecutionContext.RestoreFlow(). `

```
System.InvalidOperationException:
   at Umbraco.Cms.Core.Scoping.Scope.Dispose (Umbraco.Infrastructure, Version=9.3.0.0, Culture=neutral, PublicKeyToken=null)
   at Umbraco.Cms.Core.Services.Implement.CacheInstructionService.ProcessInstructions (Umbraco.Infrastructure, Version=9.3.0.0, Culture=neutral, PublicKeyToken=null)
   at Umbraco.Cms.Infrastructure.Sync.DatabaseServerMessenger.Sync (Umbraco.Infrastructure, Version=9.3.0.0, Culture=neutral, PublicKeyToken=null)
   at Umbraco.Cms.Infrastructure.HostedServices.ServerRegistration.InstructionProcessTask.PerformExecuteAsync (Umbraco.Infrastructure, Version=9.3.0.0, Culture=neutral, PublicKeyToken=null)

```

### Steps to reproduce

Make changes to content.
Stop the site
Delete umbraco's temp files
Start the site.

### Expected result / actual result

Distributed Cache instructions are processed.

### PR DESCRIPTION
**Pull request by vsilvar**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes #12022

### Description
`RecurringHostServices` used by Umbraco are currently implemented with the usage of Timers.
The problem is that, by default, the execution context will flow, resulting in the Ambient context scope being shared by different threads.

Compounding this issue is the fact that any exception in these services isn't being caught, causing the whole AppDomain to be terminated.

### CODE REVIEW

File: src/Umbraco.Infrastructure/Services/Implement/CacheInstructionService.cs [hunk 1]
```diff
@@ -247,6 +247,13 @@ private int ProcessDatabaseInstructions(CacheRefresherCollection cacheRefreshers
         /// </summary>
         private bool TryDeserializeInstructions(CacheInstruction instruction, out JArray jsonInstructions)
```
Comment (vsilvar) [inline src/Umbraco.Infrastructure/Services/Implement/CacheInstructionService.cs:248]: While debugging the original issue, I also came across a 
```
System.ArgumentNullException:
   at Newtonsoft.Json.JsonConvert.DeserializeObject (Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed)
   at Newtonsoft.Json.JsonConvert.DeserializeObject (Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed)
   at Newtonsoft.Json.JsonConvert.DeserializeObject (Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed)
   at Umbraco.Cms.Core.Services.Implement.CacheInstructionService.TryDeserializeInstructions (Umbraco.Infrastructure, Version=9.3.1.0, Culture=neutral, PublicKeyToken=null)
   at Umbraco.Cms.Core.Services.Implement.CacheInstructionService.ProcessDatabaseInstructions (Umbraco.Infrastructure, Version=9.3.1.0, Culture=neutral, PublicKeyToken=null)
   at Umbraco.Cms.Core.Services.Implement.CacheInstructionService.ProcessInstructions (Umbraco.Infrastructure, Version=9.3.1.0, Culture=neutral, PublicKeyToken=null)
   at Umbraco.Cms.Infrastructure.Sync.DatabaseServerMessenger.Sync (Umbraco.Infrastructure, Version=9.3.1.0, Culture=neutral, PublicKeyToken=null)
   at Umbraco.Cms.Infrastructure.HostedServices.ServerRegistration.InstructionProcessTask.PerformExecuteAsync (Umbraco.Infrastructure, Version=9.3.1.0, Culture=neutral, PublicKeyToken=null)
```
While I'm not sure how a `CacheInstruction` with null instructions can be generated, I've addressed it so the method behavior matches the name and what would be expected.

**Comment by vsilvar** [comment]
It would probably also be a good idea to catch and log any unhandled exceptions in `ExecuteAsync(object state)` to prevent the whole AppDomain to be restarted when error occur.

Please let me know if I should go ahead and add that as well.

**Comment by nzdev** [comment]
Awesome! Could we get this in 9.4.0?

File: src/Umbraco.Infrastructure/Services/Implement/CacheInstructionService.cs [hunk 2]
```diff
@@ -247,6 +247,13 @@ private int ProcessDatabaseInstructions(CacheRefresherCollection cacheRefreshers
...
         {
+            if (instruction.Instructions == null)
```
Comment (Zeegaan) [inline src/Umbraco.Infrastructure/Services/Implement/CacheInstructionService.cs:250]:
```suggestion
            if (instruction.Instructions is null)
```

**Review by Zeegaan — CHANGES_REQUESTED** [review]
Hey @vsilvar great job!
Yea i think adding a catch to the `ExecuteAsync(object state)` would be a great idea! Please add that 👍 
I'm having some trouble easily reproducing this locally, could you share what you are doing to force this error locally ? 🙈

File: src/Umbraco.Infrastructure/HostedServices/RecurringHostedServiceBase.cs [hunk 3]
```diff
@@ -40,7 +40,18 @@ protected RecurringHostedServiceBase(TimeSpan period, TimeSpan delay)
...
+            {
+                using (ExecutionContext.SuppressFlow())
+                {
+                    _timer = new Timer(ExecuteAsync, null, (int)_delay.TotalMilliseconds, (int)_period.TotalMilliseconds);
+                }
+            }
+            else
+            {
+                _timer = new Timer(ExecuteAsync, null, (int)_delay.TotalMilliseconds, (int)_period.TotalMilliseconds);
+            }
```
Comment (ronaldbarendse) [inline src/Umbraco.Infrastructure/HostedServices/RecurringHostedServiceBase.cs:53]: Instead of duplicating code, this can be rewritten as:
```suggestion
            using (!ExecutionContext.IsFlowSuppressed() ? (IDisposable)ExecutionContext.SuppressFlow() : null)
            {
                _timer = new Timer(ExecuteAsync, null, (int)_delay.TotalMilliseconds, (int)_period.TotalMilliseconds);
            }
```

**Comment by vsilvar** [comment]
@Zeegaan I've added the the catch statement to `ExecuteAsync`.
As for reproducing the issue locally, I was able using the following:
```
public void ConfigureServices(IServiceCollection services)
{
    // Activate ContentCleanup for example
    _config["Umbraco:CMS:Content:ContentVersionCleanupPolicy:EnableCleanup"] = "true";

    services.AddHostedService<TestHostedService>();

    services.AddUmbraco(_env, _config)
        .AddBackOffice()
        .AddWebsite()
        .AddComposers()
        .SetServerRegistrar<SingleServerRoleAccessor>() // Just to ensure the hosted services execute
        .Build();
}
```
```
public class TestHostedService : IHostedService
{
    private readonly IScopeProvider _scopeProvider;

    public TestHostedService(IScopeProvider scopeProvider) => _scopeProvider = scopeProvider;

    public Task StartAsync(CancellationToken cancellationToken)
    {
        // It's important this method actually runs synchronously to ensure it runs in the same thread as the other hosted services 
        // (StartAsync is actually called with ConfigureAwait(false))
        
        using (IScope scope = _scopeProvider.CreateScope(autoComplete: true))
        {
            // Dummy call
            _ = scope.Database.Query<object>("SELECT * FROM umbracoKeyValue").ToList();
        }

        return Task.CompletedTask;
    }

    public Task StopAsync(CancellationToken cancellationToken) => Task.CompletedTask;
}
```
As soon as any of the recurring timer tasks executes and tries to dispose a scope, it should throw.

**Review by Zeegaan — APPROVED** [review]
Tests out great, thanks for the code snippets 🙏 
Code LGTM 👓

**Comment by Zeegaan** [comment]
Chery picked for 9.4

File: src/Umbraco.Infrastructure/HostedServices/RecurringHostedServiceBase.cs [hunk 4]
```diff
@@ -29,18 +31,24 @@ public abstract class RecurringHostedServiceBase : IHostedService, IDisposable
         /// <summary>
         /// Initializes a new instance of the <see cref="RecurringHostedServiceBase"/> class.
         /// </summary>
-        /// <param name="period">Timepsan representing how often the task should recur.</param>
-        /// <param name="delay">Timespan represeting the initial delay after application start-up before the first run of the task occurs.</param>
-        protected RecurringHostedServiceBase(TimeSpan period, TimeSpan delay)
+        /// <param name="logger">Logger.</param>
+        /// <param name="period">Timespan representing how often the task should recur.</param>
+        /// <param name="delay">Timespan representing the initial delay after application start-up before the first run of the task occurs.</param>
+        protected RecurringHostedServiceBase(ILogger logger, TimeSpan period, TimeSpan delay)
```
Comment (p-m-j) [inline src/Umbraco.Infrastructure/HostedServices/RecurringHostedServiceBase.cs:37]: This is a breaking change, we need an alernate ctor without a logger.

Comment (Zeegaan) [reply src/Umbraco.Infrastructure/HostedServices/RecurringHostedServiceBase.cs:37]: I have amended this in my PR: https://github.com/umbraco/Umbraco-CMS/pull/12161

File: src/Umbraco.Infrastructure/HostedServices/ContentVersionCleanup.cs [hunk 5]
```diff
@@ -32,7 +32,7 @@ public class ContentVersionCleanup : RecurringHostedServiceBase
             IContentVersionService service,
             IMainDom mainDom,
             IServerRoleAccessor serverRoleAccessor)
-            : base(TimeSpan.FromHours(1), TimeSpan.FromMinutes(3))
+            : base(logger, TimeSpan.FromHours(1), TimeSpan.FromMinutes(1))
```
Comment (Zeegaan) [inline src/Umbraco.Infrastructure/HostedServices/ContentVersionCleanup.cs:35]: @vsilvar Is the Timespan.FromMinutes change here intentional ? 🤔

Comment (vsilvar) [reply src/Umbraco.Infrastructure/HostedServices/ContentVersionCleanup.cs:35]: @Zeegaan Oops, completely unintentional. 😅
