### PR TITLE
Performance: Optimize `ContentTypeRepository` deep-clone on cache reads (closes #22250)

### LINKED ISSUE #22250: Performance: ContentTypeRepository deep-clones entire IContentType object graph on every cache read
### Which Umbraco version are you using?

17.2.2

### Bug summary

The `ContentTypeRepository` uses a `FullDataSetRepositoryCachePolicy` that caches all content types in memory as a single collection. However, on every request that retrieves content types — even when only a few scalar properties like `Name`, `Icon`, `IsElement`, or `Description` are needed — the entire `IContentType` object graph is deep-cloned. This includes property groups, property types, compositions, allowed templates, and more. The performance cost scales _linearly_ with the total number of content types in the system and becomes a significant bottleneck in sites with many document types.

The source code itself acknowledges this with a "TODO" comment:

`// the filtering is highly inefficient as we deep-clone everything — there should be a way to GetMany(predicate) right from the cache policy!"`

### Specifics

**Affected files**:

- [src/Umbraco.Infrastructure/Cache/FullDataSetRepositoryCachePolicy.cs](https://github.com/umbraco/Umbraco-CMS/blob/main/src/Umbraco.Infrastructure/Cache/FullDataSetRepositoryCachePolicy.cs)
- [src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepository.cs](https://github.com/umbraco/Umbraco-CMS/blob/main/src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepository.cs)

**Root cause in `FullDataSetRepositoryCachePolicy`**:

The `GetAll()` method deep-clones every entity in the cached collection on every call:

```csharp
// FullDataSetRepositoryCachePolicy.GetAll()
return all.Select(x => (TEntity)x.DeepClone()).ToArray();
```

The `Get(id)` method also deep-clones the matched entity:

```csharp
// FullDataSetRepositoryCachePolicy.Get()
TEntity? entity = all.FirstOrDefault(x => _entityGetId(x)?.Equals(id) ?? false);
return (TEntity?)entity?.DeepClone();
```

**Root cause in `ContentTypeRepository`**:

Single-entity lookups (`PerformGet`) call `GetMany()` (which fetches the full cached set via `GetAll()`) just to filter by ID/Key/Alias afterwards:

```csharp
protected override IContentType? PerformGet(int id)
    => GetMany().FirstOrDefault(x => x.Id == id);

protected override IContentType? PerformGet(Guid id)
    => GetMany().FirstOrDefault(x => x.Key == id);
```

This means that looking up a single content type by ID triggers deep-cloning of ALL content types. The `IContentType` graph is expensive to clone because it contains collections of `PropertyGroup`, `PropertyType`, compositions, and `ITemplate` references.

**Impact**:

- The cost is O(n) in the number of content types for every individual lookup.
- In systems with 50–200+ document types (common in enterprise setups), this adds measurable CPU overhead on every request.
- The same repository pattern is used by `MediaTypeRepository` and `MemberTypeRepository`.

### Steps to reproduce

1. Set up an Umbraco 17+ instance with 50+ document types (including compositions).
2. Use any backoffice API endpoint or Delivery API call that resolves content types — e.g., the content type listing endpoint or any content fetch that triggers type resolution.
3. Profile the application (e.g., with dotTrace, Application Insights, or a `Stopwatch` around `IContentTypeService.Get()`).
4. Observe that a significant portion of CPU time is spent in `DeepClone()` calls originating from `FullDataSetRepositoryCachePolicy.GetAll()` and `FullDataSetRepositoryCachePolicy.Get()`.

### Expected result / actual result

**Expected result**:

- Read-only lookups that only need scalar properties (`Name`, `Icon`, `IsElement`, `Description`) should not trigger a full deep-clone of the entire `IContentType` object graph.
- Single-entity lookups by ID should not clone all cached entities.
- Cache reads for content types should have O(1) or at worst O(1)-clone cost for single lookups, not O(n)-clone.

**Actual result**:

- Every `Get(id)` call on `ContentTypeRepository` deep-clones the matched entity (including its full object graph) via `FullDataSetRepositoryCachePolicy`.
- Every `GetAll()` call deep-clones every entity in the cache.
- For `PerformGet(int id)`, the flow is: `GetMany()` → `GetAll()` → deep-clone all N entities → `FirstOrDefault(x => x.Id == id)` → discard N-1 clones.
- The TODO in the source ([ContentTypeRepository.cs](https://github.com/umbraco/Umbraco-CMS/blob/main/src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepository.cs#L143)) confirms this is a known inefficiency.

### PR DESCRIPTION
**Pull request by AndyButland**
## Description

Issue https://github.com/umbraco/Umbraco-CMS/issues/22250 reports on performance optimisations we could consider for the content type repository, where we lean on a "full dataset" cache (where, at the repository level, all content types are cached as a collection and lookups retrieve from that collection.

There are two places where we could optimise:

- **Single single-entity lookups via non-integer Id** (`Get(Guid)`, `Get(string)`, `Exists(Guid)`)** called `GetMany().FirstOrDefault(...)` using a predicate, which deep-cloned every cached content type to find the one. Now these uses new `FindCached`/`ExistsCached` methods on `FullDataSetRepositoryCachePolicy` that search the non-cloned cache and clone only the matched entity (or nothing for existence checks).

- **Batch lookups** (`GetMany(Guid[])`) used `PerformGetAll(Guid[])` and similarly cloned all N entities then filtered. Now this path uses `FindAllCached` to clone only the matched subset.

Fixes apply to `ContentTypeRepository`, `MediaTypeRepository`, and `MemberTypeRepository` via shared virtual methods in `ContentTypeRepositoryBase`.

### Automated

Existing integration tests should pass, as well as new unit tests that have been added to verify the new behaviour.

### Manual

Test retrieval and update of content types via the backoffice.

## Benchmarking

I added and ran a benchmark test using `AuditItem` (a lightweight entity — real `IContentType` with PropertyGroups, compositions, and templates would likely show larger gains) and saw positive results:

| Entities | GetAll then filter (old) | FindCached (new) | Speedup | Memory reduction |
|----------|--------------------------|------------------|---------|------------------|
| 10       | 1.95 μs / 2.4 KB        | 1.27 μs / 0.7 KB | 1.5x   | 70%              |
| 50       | 5.05 μs / 9.1 KB        | 1.31 μs / 1.0 KB | 3.9x   | 89%              |
| 200      | 17.3 μs / 34.3 KB       | 1.32 μs / 2.2 KB | 13x    | 93%              |

`ExistsCached` (zero clones) shows similar speedups with 94% memory reduction at 200 entities. `FindCached` and `ExistsCached` remain constant-time regardless of entity count.

### CODE REVIEW

File: src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs [hunk 1]
```diff
@@ -1559,7 +1566,20 @@ protected void ValidateAlias(TEntity entity)
...
+    /// <summary>
+    /// Gets a content type by its unique key (GUID), using the full-dataset cache policy
+    /// to clone only the matched entity rather than the entire cached collection.
+    /// </summary>
+    protected virtual TEntity? PerformGet(Guid id)
+    {
+        if (TypedCachePolicy is { } policy)
+        {
+            return policy.FindCached(x => x.Key == id, PerformGetAll);
+        }
```
Comment (Zeegaan) [inline src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs:1578]: I see this syntax a few places, which looks odd to me, but maybe I'm just not understanding it fully? 🤔 
Wouldn't it be better with:

```suggestion
        if (TypedCachePolicy is not null)
        {
            return TypedCachePolicy.FindCached(x => x.Key == id, PerformGetAll);
        }
```
Atleast thats more human readable to me 🙈 
But is there some performance optimization I'm not aware of 🤔

**Review by Zeegaan — COMMENTED** [review]
Overall looks good, just had a single comment before approving 😁

File: src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs (hunk 1 above)
Comment (AndyButland) [reply src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs:1578]: Similar to be honest, I've been seeing it more and more too.  But it is the marginally more correct thing to use here I understand, and likely we'll see it more and more.

They basically do the same thing - match a non-null value - but there is a subtle difference in thread safety. As `TypedCachePolicy` is a property: the property getter is invoked once, and the result is captured in `policy`. In your suggested case, `TypedCachePolicy` is read twice and so the value could theoretically become null or change between those two reads.

Comment (Zeegaan) [reply src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs:1578]: Ah okay, that makes sense to me, thanks for explaining, with that I'm happy 😁
