### PR TITLE
Better exception message when using ALTER TABLE and SQLite

### LINKED ISSUE #12676: SQLite Alter throws null
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

10.0.0

### Bug summary

In one of my packages, I have a migration that updates a column from non nullable to nullable. However, due to the limitations in SQLite, it'll throw an error.
image

I did read a bit on this as I am quite new to SQLite and I know this isn't really possible with SQLite, but wouldn't it be better for Umbraco to either handle that case or to throw an error itself. Would love to know what the consensus about this is!

### Specifics

_No response_

### Steps to reproduce

Try to alter a non-nullable column to a nullable column in a migration while running SQLite.

`Alter.Table("SeoToolkitSitemapPageType").AlterColumn("ChangeFrequency").AsString().Nullable().Do();`

### Expected result / actual result

Ideally, it would also work on SQLite, but that might be a bit difficult with the SQLite restrictions. Otherwise would be nice to provide a good way to work around it.

---
_This item has been added to our backlog [AB#20784](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/20784)_

### PR DESCRIPTION
**Pull request by bergmania**
Fixes #12676

Not pretty, but at least it is informative.
image

### CODE REVIEW

File: src/Umbraco.Infrastructure/Migrations/Expressions/Alter/Table/AlterTableBuilder.cs [hunk 1]
```diff
@@ -21,7 +22,20 @@ public AlterTableBuilder(IMigrationContext context, AlterTableExpression express
 
     public ForeignKeyDefinition CurrentForeignKey { get; set; } = null!;
 
-    public void Do() => Expression.Execute();
+    public void Do()
+    {
+        if (_context.Database.DatabaseType.IsSqlite())
+        {
+            throw new NotSupportedException(@"SQLite do not support ALTER TABLE operations.Instead you will have to:
```
Comment (bjarnef) [inline src/Umbraco.Infrastructure/Migrations/Expressions/Alter/Table/AlterTableBuilder.cs:29]: A minor thing is a missing space before "Instead".
Could it use `Environment.NewLine` to list  each step on a separate line?

Comment (bergmania) [reply src/Umbraco.Infrastructure/Migrations/Expressions/Alter/Table/AlterTableBuilder.cs:29]: Sure, we can use `Environment.NewLine`, but just a heads up, it will not be reflected into the error message on screen, but work in log messages.

Comment (bjarnef) [reply src/Umbraco.Infrastructure/Migrations/Expressions/Alter/Table/AlterTableBuilder.cs]: I guess it could handle replacements of newline here https://github.com/umbraco/Umbraco-CMS/blob/v10/contrib/src/Umbraco.Web.UI.Client/src/installer/steps/error.html#L4

Either a using a function, updating property value.

Comment (bjarnef) [reply src/Umbraco.Infrastructure/Migrations/Expressions/Alter/Table/AlterTableBuilder.cs]: It seems filters isn't injected into the install module. https://github.com/umbraco/Umbraco-CMS/blob/v10/contrib/src/Umbraco.Web.UI.Client/src/installer/_module.js

But alternatively it could probably be handled in the controller.

**Review by nikolajlauridsen — APPROVED** [review]
LGTM 👍
