### PR TITLE
Sort manifest file paths alphabetically

### LINKED ISSUE #14462: [v10+] Linux : Inconsistent ordering of package manifest resource loading
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.5.1

### Bug summary

A customer reported a Vendr bug here https://github.com/vendrhub/vendr-checkout/issues/39 but it turns out it boils down to the way manifest files are loaded / JS resources loaded in the back office.

Essentially Vendr Checkout is designed to run after Vendr and this is how it works on Windows, but on Linux Vendr Checkout was loading it's scripts first and thus throwing an error.

### Specifics

Fundamentally it boils down to the `IManifestParser.GetManifestFiles` method which calls `Directory.GetFiles(_path, "package.manifest", SearchOption.AllDirectories);` to load all manifests. The order of this list is what dictates the order in which manifests assets are loaded in the back office. The issue being `GetFiles` does not give a guaranteed order and so on Linux it was loading Vendr Checkout first.

For consistency across platforms we should update `GetManifestFiles` and sort the paths returned from `GetFiles` before returning them. This ensures consistency over the order in which assets are loaded.

### Steps to reproduce

See steps in this issue https://github.com/vendrhub/vendr-checkout/issues/39

### Expected result / actual result

We expected Vendr Checkout to load it's scripts after Vendr

### PR DESCRIPTION
**Pull request by mattbrailsford**
### Prerequisites

- [ ] I have added steps to test this contribution in the description below

This fixes #14462

### Description

Issue #14462 denotes that on Linux `Directory.GetFiles` as used by `GetManifestFiles` to load package manifest files from disk is not guaranteed to return the list of files in a set order. This is a problem because the order the manifests are loaded also dictates the order any manifest script files are loaded in the back office. This can become a problem if you have scripts that rely on scripts from another package to be loaded first, such as Vendr Checkout needing Vendr to be loaded first.

This PR updates the `GetManifestFiles` method to sort the list of retrieved file paths alphabetically before returning them thus ensuring a consistent and expected behabiour.

### CODE REVIEW

**Comment by georgebid** [comment]
Hey @mattbrailsford! Thanks for putting in a PR to fix this one 😸 Some on the core collaborators team will review this soon!

File: src/Umbraco.Infrastructure/Manifest/ManifestParser.cs [hunk 1]
```diff
@@ -250,6 +250,11 @@ private IEnumerable<string> GetManifestFiles()
             return Array.Empty<string>();
         }
 
-        return Directory.GetFiles(_path, "package.manifest", SearchOption.AllDirectories);
+        var files = Directory.GetFiles(_path, "package.manifest", SearchOption.AllDirectories);
+
+        // Ensure a consistent sorting of paths
+        Array.Sort(files);
```
Comment (ronaldbarendse) [inline src/Umbraco.Infrastructure/Manifest/ManifestParser.cs:256]: Might be good to include a more verbose explanation why this is needed, e.g.:

```suggestion
        // Ensure a consistent, alphabetical sorting of paths, because this is not guaranteed to be the same between file systems or OSes
        Array.Sort(files);
```

Also note that in most cases (sub)folders are returned before the files, but since this uses `SearchOption.AllDirectories` and sorts on the whole path, this might result in a different (maybe unexpected) ordering, e.g.:
1. `App_Plugins\MyPackage\BackOffice\MyEditor\package.manifest`
2. `App_Plugins\MyPackage\package.manifest`
3. `App_Plugins\MyPackage\Search\package.manifest`

And just for reference, the [Microsoft documentation](https://learn.microsoft.com/en-us/dotnet/api/system.io.directory.getfiles?view=net-7.0#system-io-directory-getfiles(system-string)) does mention this:
> The order of the returned file names is not guaranteed; use the [Sort](https://learn.microsoft.com/en-us/dotnet/api/system.array.sort?view=net-7.0) method if a specific sort order is required.

**Comment by iOvergaard** [comment]
Hey @mattbrailsford, do you have an interest in getting this PR up-to-date? I think it is a nice addition, if you could have a look at the comment from @ronaldbarendse.

**Comment by mattbrailsford** [comment]
@iOvergaard I've committed Ronald's comment update, but I'm not sure we need to do more than just sorting. I'm pretty sure packages tend to have a one-to-one relationship with package manifests so the likely hood of having multiple manifests in the same project is minimal. And even then, so long as there is consistency in ordering, folks have a means to control load order by changing file/folder names which is ultimately what this was trying to give.

If others don't agree, then I guess we'd need to decide on a rule as to whether folders have precedence over files or vica versa and then perform an alternative sort that sorts first by one and then the other.

**Comment by iOvergaard** [comment]
Many thanks, @mattbrailsford!

I merged it before noticing it targeted v10/dev. I will see if I can cherry-pick it!

**Comment by iOvergaard** [comment]
@mattbrailsford So already from V13, we are loading the manifests differently in an enumerator pattern. I am not sure where to insert the `Array.sort` call or if is it really needed. Do you have any idea if the original issue described in #14462 is reproducible in V13? And V15 for that matter, which uses the same algorithm more or less?

**Comment by mattbrailsford** [comment]
@iOvergaard probably not, but the key is ultimately "does someone have control over when a manifest is loaded" because if someone relies on some other package they will need to ensure it loads after it. So long as this is possible in some way, then this probably isn't necesarry
