### PR TITLE
Revert #14234 add update error message for DB connection failures

### LINKED ISSUE #14110: UnattendedInstaller broken
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.3.0

### Bug summary

In 11.2.2 everything is working as it should. On an empty database Umbraco tries to find the relevant database from the umbracoDbDSN env variable and when it isn't found the database is created, no problem.
In 11.3.0 something is now broken and I just get an error. The only thing I changed is the version. 

I know for sure the env variable is still used and is valid, as the error I get when changing it to something invalid is different. 

### Specifics

Output in terminal:
2023-04-17 15:22:23 Error Number:4060,State:1,Class:11
2023-04-17 15:22:23 Unhandled exception. Umbraco.Cms.Core.Exceptions.BootFailedException: A connection string is configured but Umbraco could not connect to the database.
2023-04-17 15:22:23    at Umbraco.Cms.Infrastructure.Runtime.RuntimeState.DetermineRuntimeLevel()
2023-04-17 15:22:23    at Umbraco.Cms.Infrastructure.Install.UnattendedInstaller.HandleAsync(RuntimeUnattendedInstallNotification notification, CancellationToken cancellationToken)
2023-04-17 15:22:23    at Umbraco.Cms.Core.Events.NotificationAsyncHandlerWrapperImpl`1.<>c__DisplayClass0_0.<HandleAsync>b__1(INotification theNotification, CancellationToken theToken)
2023-04-17 15:22:23    at Umbraco.Cms.Core.Events.EventAggregator.PublishCoreAsync(IEnumerable`1 allHandlers, INotification notification, CancellationToken cancellationToken)
2023-04-17 15:22:23    at Umbraco.Cms.Infrastructure.Runtime.CoreRuntime.StartAsync(CancellationToken cancellationToken, Boolean isRestarting)
2023-04-17 15:22:23    at Umbraco.Cms.Infrastructure.Runtime.CoreRuntime.StartAsync(CancellationToken cancellationToken)
2023-04-17 15:22:23    at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
2023-04-17 15:22:23    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
2023-04-17 15:22:23    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
2023-04-17 15:22:23    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
2023-04-17 15:22:23    at UmbracoPOC.Program.Main(String[] args) in /src/UmbracoPOC/Program.cs:line 8
2023-04-17 15:22:23 [13:22:23 ERR] Unhandled exception in AppDomain (terminating).
2023-04-17 15:22:23 Umbraco.Cms.Core.Exceptions.BootFailedException: A connection string is configured but Umbraco could not connect to the database.
2023-04-17 15:22:23    at Umbraco.Cms.Infrastructure.Runtime.RuntimeState.DetermineRuntimeLevel()
2023-04-17 15:22:23    at Umbraco.Cms.Infrastructure.Install.UnattendedInstaller.HandleAsync(RuntimeUnattendedInstallNotification notification, CancellationToken cancellationToken)
2023-04-17 15:22:23    at Umbraco.Cms.Core.Events.NotificationAsyncHandlerWrapperImpl`1.<>c__DisplayClass0_0.<HandleAsync>b__1(INotification theNotification, CancellationToken theToken)
2023-04-17 15:22:23    at Umbraco.Cms.Core.Events.EventAggregator.PublishCoreAsync(IEnumerable`1 allHandlers, INotification notification, CancellationToken cancellationToken)
2023-04-17 15:22:23    at Umbraco.Cms.Infrastructure.Runtime.CoreRuntime.StartAsync(CancellationToken cancellationToken, Boolean isRestarting)
2023-04-17 15:22:23    at Umbraco.Cms.Infrastructure.Runtime.CoreRuntime.StartAsync(CancellationToken cancellationToken)
2023-04-17 15:22:23    at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
2023-04-17 15:22:23    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
2023-04-17 15:22:23    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
2023-04-17 15:22:23    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
2023-04-17 15:22:23    at UmbracoPOC.Program.Main(String[] args) in /src/UmbracoPOC/Program.cs:line 8

### Steps to reproduce

Run Umbraco from scratch and use a MSSQL database.
I run it in docker and my docker compose state:
            ConnectionStrings__umbracoDbDSN: "Server=umbraco-db;Database=umbracoDb;User Id=sa;Password=yourStrong(!)Password;"
            ConnectionStrings__umbracoDbDSN_ProviderName: "Microsoft.Data.SqlClient"
 

### Expected result / actual result

Umbraco should recreate a new empty database allowing Usync to add content. 

---
_This item has been added to our backlog [AB#28820](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/28820)_

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes #14110

### Description

This PR reverts #14234 as we don't really want to force create MSSQL databases automatically.

To fix #14110, the error message for failed DB connections has been updated to include possible causes and also a mention of the `InstallMissingDatabase` in `GlobalSettings`:

image

### Testing this PR

Configure a MSSQL connection string in app settings. The connection string should point at a non-existing database. Verify that the resulting error message contains a hint about the `InstallMissingDatabase` setting.

### CODE REVIEW

File: src/Umbraco.Infrastructure/Runtime/RuntimeState.cs [hunk 1]
```diff
@@ -225,7 +225,12 @@ public void DetermineRuntimeLevel()
 
                     // else it is bad enough that we want to throw
                     Reason = RuntimeLevelReason.BootFailedCannotConnectToDatabase;
-                    BootFailedException = new BootFailedException("A connection string is configured but Umbraco could not connect to the database.");
+                    BootFailedException = new BootFailedException(
+                        $"""
+                         A connection string is configured but Umbraco could not connect to the database.
+                         Possible causes include network errors, a bad connection string or a missing database.
+                         Tip: Use {nameof(GlobalSettings)}:{nameof(GlobalSettings.InstallMissingDatabase)} to instruct Umbraco to create the database automatically.
```
Comment (ronaldbarendse) [inline src/Umbraco.Infrastructure/Runtime/RuntimeState.cs:232]: This should contain the complete setting name (including `Umbraco:CMS:`), which is available as a constant:
```suggestion
                         Tip: Use {Constants.Configuration.ConfigGlobal}:{nameof(GlobalSettings.InstallMissingDatabase)} to instruct Umbraco to create the database automatically.
```

**Comment by ronaldbarendse** [comment]
Also note that https://github.com/advisories/GHSA-h8wc-r4jh-mg7m changed the runtime level from `RuntimeLevel.Install` to `RuntimeLevel.BootFailed` when it has a connection failure on startup and either `ForceCreateDatabase` or `InstallMissingDatabase` is enabled: this did brake the attended install with a preconfigured connection string (as @JasonElkin mentioned in https://github.com/umbraco/Umbraco-CMS/issues/14956#issuecomment-2126000495).

This issue was actually the result of changing the `SqlServerDatabaseProviderMetadata.ForceCreateDatabase` value to `true`, as that would always put a website using SQL Server (which is used on most, if not all, production sites) into the install state when it had a intermittent connection issue on startup (and doesn't use unattended install). This bypassed the `InstallMissingDatabase` setting completely, which is mainly there to prevent you from opening up your site to this security issue (even though the conditions are very rare):

https://github.com/umbraco/Umbraco-CMS/blob/cbd4dc6e0dca40d5acde47fc43b280a3c1e3a9c5/src/Umbraco.Infrastructure/Runtime/RuntimeState.cs#L218-L224

This is also the reason why I suggested making the `InstallMissingDatabase` setting nullable, so a `null` value falls back to the providers `ForceCreateDatabase` value, but setting it to `false` will disable this for all providers: https://github.com/umbraco/Umbraco-CMS/issues/14956#issuecomment-1782533652.

**Comment by kjac** [comment]
So. We've changed this up a bit. After a few internal discussions, we've decided to obsolete the `InstallMissingDatabase` configuration option and remove it in V16. No matter what we do, it will always pose a security risk, so it has to go. 

Bonus info: The option has not worked since July 2023 😄

**Comment by Zeegaan** [comment]
LGTM 👍
