### PR TITLE
Persistence Models: DTO attribute fixes (closes #21675, #22304)

### LINKED ISSUE #21675: More Sql Syntax Issues to Fix
### Which Umbraco version are you using?

17.3.0-rc.preview

### Bug summary

This "reopens" issue #20453, because that was closed to early.

### Specifics

_No response_

### Steps to reproduce

The issue are only visible in an unsupported custom database provider for PostgreSQL.
But all tests must succeed and no changes to current behaviour is allowed.

### Expected result / actual result

_No response_

### PR DESCRIPTION
**Pull request by idseefeld**
This is another PR for issue #21675.
For DTOs without autoIncrement columns and multi-column primary keys attributes need updates to be fully compatible with NPoco. Especially an PostgreSQL provider has otherwise issues.

The created table sql stays unchanged!

All test must succeed and must not be any changes for existing database providers.

### CODE REVIEW

File: src/Umbraco.Infrastructure/Persistence/Dtos/ContentNuDto.cs [hunk 1]
```diff
@@ -6,24 +6,25 @@
...
 
 [TableName(TableName)]
-[PrimaryKey(PrimaryKeyColumnName, AutoIncrement = false)]
+[PrimaryKey([NodeIdColumnName, PublishedColumnName], AutoIncrement = false)]
 [ExplicitColumns]
 public class ContentNuDto
 {
     public const string TableName = Constants.DatabaseSchema.Tables.NodeData;
-    public const string PrimaryKeyColumnName = Constants.DatabaseSchema.Columns.NodeIdName;
+    public const string PrimaryKeyColumnName = "PK_cmsContentNu";
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/Dtos/ContentNuDto.cs]: The naming here is a bit confusing.  You have `PrimaryKeyColumnName` - but this isn't (now) describing the primary key column's name, rather it's describing the name of the primary key constraint.  This comment applies to various DTOs updated in this PR.

A name like `PrimaryKeyConstraintName` would be clearer here.

File: src/Umbraco.Infrastructure/Persistence/Dtos/ContentVersionCleanupPolicyDto.cs [hunk 2]
```diff
@@ -5,15 +5,15 @@
...
 
 [TableName(TableName)]
-[PrimaryKey(PrimaryKeyName, AutoIncrement = false)]
+[PrimaryKey(PrimaryKeyColumnName, AutoIncrement = false)]
 [ExplicitColumns]
 internal sealed class ContentVersionCleanupPolicyDto
 {
     public const string TableName = Constants.DatabaseSchema.Tables.ContentVersionCleanupPolicy;
-    public const string PrimaryKeyName = "contentTypeId";
+    public const string PrimaryKeyColumnName = "contentTypeId";
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/Dtos/ContentVersionCleanupPolicyDto.cs:13]: Here `PrimaryKeyColumnName` remains the name of a column - which isn't consistent, and will be confusing if this is referring to a constraint name in other DTOs.

Comment (idseefeld) [reply src/Umbraco.Infrastructure/Persistence/Dtos/ContentVersionCleanupPolicyDto.cs:13]: The only difference I see to other DTOs e.g. `ContentDto` is the explicit name in the `PrimaryKeyColumn` attribute. I remove it, because it is not necessary.

File: src/Umbraco.Infrastructure/Persistence/Dtos/Webhook2HeadersDto.cs [hunk 3]
```diff
@@ -6,18 +6,20 @@
...
-    internal const string ReferenceMemberName = "WebhookId"; // should be WebhookIdColumnName, but for database compatibility we keep it like this
+    internal const string ReferenceMemberName = "WebhookId"; // should be "webhookId" like const WebhookIdColumnName, but for database compatibility we keep it like this
 
     private const string WebhookIdColumnName = "webhookId";
     private const string KeyColumnName = "Key";
     private const string ValueColumnName = "Value";
 
     [Column(WebhookIdColumnName)]
-    [PrimaryKeyColumn(AutoIncrement = false, Name = "PK_headers2WebhookDto", OnColumns = $"{WebhookIdColumnName}, {KeyColumnName}")]
+    [PrimaryKeyColumn(AutoIncrement = false, Name = PrimaryKeyConstraintName, OnColumns = $"{WebhookIdColumnName},{KeyColumnName}")]
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/Dtos/Webhook2HeadersDto.cs]:
```suggestion
    [PrimaryKeyColumn(AutoIncrement = false, Name = PrimaryKeyConstraintName, OnColumns = $"{WebhookIdColumnName}, {KeyColumnName}")]
```

File: src/Umbraco.Infrastructure/Persistence/Dtos/ContentNuDto.cs [hunk 4]
```diff
@@ -6,24 +6,25 @@
...
 [TableName(TableName)]
-[PrimaryKey(PrimaryKeyColumnName, AutoIncrement = false)]
+[PrimaryKey([NodeIdColumnName, PublishedColumnName], AutoIncrement = false)]
 [ExplicitColumns]
 public class ContentNuDto
 {
     public const string TableName = Constants.DatabaseSchema.Tables.NodeData;
-    public const string PrimaryKeyColumnName = Constants.DatabaseSchema.Columns.NodeIdName;
+    public const string PrimaryKeyConstraintName = "PK_cmsContentNu";
+    public const string NodeIdColumnName = Constants.DatabaseSchema.Columns.NodeIdName;
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/Dtos/ContentNuDto.cs:14]: This change, and similar in other DTO updates in this PR, from `PrimaryKeyColumnName` to `NodeIdColumnName`, is strictly breaking - as the class is public and we introduced this constant in 17.2.  So if merged, this would be a breaking change from 17.2 to 17.3.  It's also inconsistent in naming between DTOs.  E.g. you've introduced it in `AccessDto` but have not updated it in this PR.

I think you'll need to revert these updates back so we keep the originally named constant (so they are consistent across DTOs, and we avoid breaking changes).

If you think it's clearer with the name you have here, which it probably is, I think you'll need to have:

```
public const string NodeIdColumnName = Constants.DatabaseSchema.Columns.NodeIdName;
public const string PrimaryKeyColumnName = NodeIdColumnName;
```

**Review by AndyButland — CHANGES_REQUESTED** [review]

**Comment by AndyButland** [comment]
I've tested the schema generation for `main` branch and this PR, and they are identical.  So no concerns on that front.

File: src/Umbraco.Infrastructure/Persistence/Dtos/ContentNuDto.cs (hunk 4 above)
Comment (idseefeld) [reply src/Umbraco.Infrastructure/Persistence/Dtos/ContentNuDto.cs:14]: Yes, you are right. There should not be breaking changes between minor versions.
I need some time and shall postpone this PR after version 17.2 is released

**Comment by idseefeld** [comment]
I have now also compared to version 17.1 and the PrimaryKey attribute are either completely new on some DTOs or fix wrong attributes. I have also made this compatible with next release of version 17.2, in case it is to late to roll out this PR in v17.2 next week. And I think now all changes are consistent.

File: src/Umbraco.Infrastructure/Persistence/Dtos/ContentTypeAllowedContentTypeDto.cs [hunk 5]
```diff
@@ -5,25 +5,25 @@
 namespace Umbraco.Cms.Infrastructure.Persistence.Dtos;
 
 [TableName(TableName)]
-[PrimaryKey(PrimaryKeyColumnName, AutoIncrement = false)]
+[PrimaryKey([PrimaryKeyColumnName, AllowedIdColumnName], AutoIncrement = false)] // fix wrong PrimaryKey attribute
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/Dtos/ContentTypeAllowedContentTypeDto.cs]:
```suggestion
[PrimaryKey([PrimaryKeyColumnName, AllowedIdColumnName], AutoIncrement = false)]
```

This comment is useful in the PR itself to understand what has changed, but it'll be confusing down the line in the code itself, as it looks like it's indicating something "to fix"

File: src/Umbraco.Infrastructure/Persistence/Dtos/ContentTypeTemplateDto.cs [hunk 6]
```diff
@@ -5,14 +5,16 @@
 namespace Umbraco.Cms.Infrastructure.Persistence.Dtos;
 
 [TableName(TableName)]
-[PrimaryKey(PrimaryKeyName, AutoIncrement = false)]
+[PrimaryKey([PrimaryKeyName, TemplateNodeIdColumnName], AutoIncrement = false)] // fix wrong PrimaryKey attribute
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/Dtos/ContentTypeTemplateDto.cs]:
```suggestion
[PrimaryKey([PrimaryKeyName, TemplateNodeIdColumnName], AutoIncrement = false)]
```

File: src/Umbraco.Infrastructure/Persistence/Dtos/ContentVersionCleanupPolicyDto.cs [hunk 7]
```diff
@@ -11,9 +11,10 @@ internal sealed class ContentVersionCleanupPolicyDto
 {
     public const string TableName = Constants.DatabaseSchema.Tables.ContentVersionCleanupPolicy;
     public const string PrimaryKeyName = "contentTypeId";
+    public const string PrimaryKeyColumnName = PrimaryKeyName;
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/Dtos/ContentVersionCleanupPolicyDto.cs]: It would be OK to remove `PrimaryKeyName` here, as the class is internal so this wouldn't be a breaking change to correct to the clearer name of `PrimaryKeyColumnName`.

File: src/Umbraco.Infrastructure/Persistence/Dtos/Member2MemberGroupDto.cs [hunk 8]
```diff
@@ -5,12 +5,13 @@
 namespace Umbraco.Cms.Infrastructure.Persistence.Dtos;
 
 [TableName(TableName)]
-[PrimaryKey(PrimaryKeyColumnName, AutoIncrement = false)]
+[PrimaryKey([PrimaryKeyColumnName, MemberGroupColumnName], AutoIncrement = false)] // fix wrong PrimaryKey attribute
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/Dtos/Member2MemberGroupDto.cs]:
```suggestion
[PrimaryKey([PrimaryKeyColumnName, MemberGroupColumnName], AutoIncrement = false)]
```

File: src/Umbraco.Infrastructure/Persistence/Dtos/TagRelationshipDto.cs [hunk 9]
```diff
@@ -5,12 +5,13 @@
 namespace Umbraco.Cms.Infrastructure.Persistence.Dtos;
 
 [TableName(TableName)]
-[PrimaryKey(PrimaryKeyColumnName, AutoIncrement = false)]
+[PrimaryKey([PrimaryKeyColumnName, PropertyTypeIdColumnName, TagIdColumnName], AutoIncrement = false)] // fix wrong PrimaryKey attribute
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/Dtos/TagRelationshipDto.cs]:
```suggestion
[PrimaryKey([PrimaryKeyColumnName, PropertyTypeIdColumnName, TagIdColumnName], AutoIncrement = false)]
```

File: src/Umbraco.Infrastructure/Persistence/Dtos/User2ClientIdDto.cs [hunk 10]
```diff
@@ -5,13 +5,14 @@
 namespace Umbraco.Cms.Infrastructure.Persistence.Dtos;
 
 [TableName(TableName)]
-[PrimaryKey(PrimaryKeyColumnName, AutoIncrement = false)]
+[PrimaryKey([PrimaryKeyColumnName, ClientIdColumnName], AutoIncrement = false)] // fix wrong PrimaryKey attribute
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/Dtos/User2ClientIdDto.cs]:
```suggestion
[PrimaryKey([PrimaryKeyColumnName, ClientIdColumnName], AutoIncrement = false)]
```

File: src/Umbraco.Infrastructure/Persistence/Dtos/User2NodeNotifyDto.cs [hunk 11]
```diff
@@ -5,14 +5,15 @@
 namespace Umbraco.Cms.Infrastructure.Persistence.Dtos;
 
 [TableName(TableName)]
-[PrimaryKey(PrimaryKeyColumnName, AutoIncrement = false)]
+[PrimaryKey([PrimaryKeyColumnName, NodeIdColumnName, ActionColumnName], AutoIncrement = false)] // fix wrong PrimaryKey attribute
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/Dtos/User2NodeNotifyDto.cs]:
```suggestion
[PrimaryKey([PrimaryKeyColumnName, NodeIdColumnName, ActionColumnName], AutoIncrement = false)]
```

File: src/Umbraco.Infrastructure/Persistence/Dtos/User2UserGroupDto.cs [hunk 12]
```diff
@@ -5,6 +5,7 @@
 namespace Umbraco.Cms.Infrastructure.Persistence.Dtos;
 
 [TableName(TableName)]
+[PrimaryKey([UserIdColumnName, UserGroupIdColumnName], AutoIncrement = false)] // fix wrong PrimaryKey attribute
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/Dtos/User2UserGroupDto.cs]:
```suggestion
[PrimaryKey([UserIdColumnName, UserGroupIdColumnName], AutoIncrement = false)]
```

File: src/Umbraco.Infrastructure/Persistence/Dtos/UserGroup2AppDto.cs [hunk 13]
```diff
@@ -5,15 +5,16 @@
 namespace Umbraco.Cms.Infrastructure.Persistence.Dtos;
 
 [TableName(TableName)]
-[PrimaryKey(PrimaryKeyColumnName, AutoIncrement = false)]
+[PrimaryKey([PrimaryKeyColumnName, AppAliasColumnName], AutoIncrement = false)] // fix wrong PrimaryKey attribute
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/Dtos/UserGroup2AppDto.cs]:
```suggestion
[PrimaryKey([PrimaryKeyColumnName, AppAliasColumnName], AutoIncrement = false)]
```

File: src/Umbraco.Infrastructure/Persistence/Dtos/UserGroup2NodePermissionDto.cs [hunk 14]
```diff
@@ -4,11 +4,14 @@
 
 namespace Umbraco.Cms.Infrastructure.Persistence.Dtos;
 
-[Obsolete("Scheduled for removal in Umbraco 18.")]
-[TableName(Constants.DatabaseSchema.Tables.UserGroup2NodePermission)]
+[Obsolete("Will be removed in Umbraco 18.")]
```
Comment (AndyButland) [inline src/Umbraco.Infrastructure/Persistence/Dtos/UserGroup2NodePermissionDto.cs]:
```suggestion
[Obsolete("Scheduled for removal in Umbraco 18.")]
```

**Review by AndyButland — CHANGES_REQUESTED** [review]
Just a few tiny tweaks @idseefeld, then I think this is all good to merge in.

**Comment by AndyButland** [comment]
I pushed a few updates @idseefeld.  Please can you have a look over and let me know if anything doesn't seem sensible to you.  On a review alongside the other DTOs I could see some inconsistencies creeping in, along with some unnecessary/confusing constant use and invalid comments.  So I've looked to align that and clean it up.

I've verified again that the generated schema is unchanged following the updates in this PR.

**Comment by idseefeld** [comment]
@AndyButland I'll have look over your updates right now...

**Comment by idseefeld** [comment]
... I have updated my PostgreSQL provider project, run all unit and integration test based on PostgreSQL database version 18 and all were successful.
So, from my point of view all your updates are fine.
Btw. @AndyButland here are some interesting statistics for PostgreSQL 18 vs. Sql Server 2025 Developer Edition on 
```
Windows 11
Prozessor	        Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz (3.00 GHz)
Installierter RAM	32,0 GB (31,8 GB verwendbar)
Systemtyp	        64-Bit-Betriebssystem, x64-basierter Prozessor

Integration Tests
"PrepareThreadCount": 10,
"SchemaDatabaseCount": 10,
"EmptyDatabasesCount": 5

PostgreSQL
Execution time: ~58 minutes (75%)
max. RAM:        ~1 GB (33%)

Sql Server
Execution time: ~77 minutes
max. RAM:        ~3 GB
```

There are only a few fixes left until Umbraco CMS will be ready for PostgreSQL. 😁

**Comment by AndyButland** [comment]
Good to hear.  Is there a reason you've put this into draft though?

**Comment by idseefeld** [comment]
@AndyButland only for the time of my validation. This is now ready for merge. Maybe Github had an issue in its status?
