### PR TITLE
Run both cms and package migrations in upgrader

### LINKED ISSUE #17436: Unattended migrations of CMS and packages require a restart for the package ones to run
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13+

### Bug summary

We've had a couple of reports of people looking to run both a CMS and a package unattended migration at the same time.  What's found is that on start-up the CMS migration runs, but the package migration doesn't.  When you restart the application, the package migrations run,

### Specifics

See [this issue on the Forms tracker](https://github.com/umbraco/Umbraco.Forms.Issues/issues/1176) that discusses the problem.

And specifically [this comment](https://github.com/umbraco/Umbraco.Forms.Issues/issues/1176#issuecomment-2249868576) where I've detailed a little digging I've done into the problem.

Also [this (internal) discussion](https://umbraco.slack.com/archives/C02JJQU9B/p1730806029980859).

### Steps to reproduce

Update your CMS and a package's dependency in your `.csproj` file such that both new versions will require database migrations.  Start Umbraco and you will see that only the CMS migrations have run.

### Expected result / actual result

Ideally both the CMS and package migrations would run in one step.

---
_This item has been added to our backlog AB#46066_

### PR DESCRIPTION
**Pull request by nikolajlauridsen**
Fixes #17436 

The problem was that the upgrader only ever ran either CMS upgrades or package upgrades, this has been updated so both are run if needed. 

Not that the CMS and package upgrades run in their own separate scopes, so it's safe to do it in a single notification handler 😄 

## Testing

Add both a CMS NoopMigration in `UmbracoPlan` and a package plan, unable unattended upgrades, and ensure both are run if needed. 

Example package migration plan 

```C#
using Umbraco.Cms.Core.Packaging;
using Umbraco.Cms.Infrastructure.Migrations;

namespace Umbraco.Cms.Web.UI;

public class MyMigrationPlan : PackageMigrationPlan
{
    public MyMigrationPlan() : base("MyPackage")
    {
    }

    protected override void DefinePlan() {
        To<NoopMigration>(Guid.Parse("AD8AF4BF-9AE1-42BC-9709-CA64891BA92D"));
    }
}
````

### CODE REVIEW

File: src/Umbraco.Infrastructure/Install/UnattendedUpgrader.cs [hunk 1]
```diff
@@ -46,55 +70,26 @@ public Task HandleAsync(RuntimeUnattendedUpgradeNotification notification, Cance
...
                     {
-                        throw new InvalidOperationException(
-                            $"The required key {RuntimeState.PendingPackageMigrationsStateKey} does not exist in startup state");
+                        return Task.CompletedTask;
                     }
 
-                    if (pendingMigrations.Count == 0)
+                    // It's entirely possible that there's both a core upgrade and package migrations to run, so try and run package migrations too.
+                    // but only if upgrade unattended is enabled.
+                    if (_unattendedSettings.UpgradeUnattended)
```
Comment (bergmania) [inline src/Umbraco.Infrastructure/Install/UnattendedUpgrader.cs:83]: This should have been PackageMigrationsUnattended, right?

**Review by bergmania — CHANGES_REQUESTED** [review]

**Review by bergmania — APPROVED** [review]
